### ISSUE TITLE
Evaluation method in template of evolutionary algorithm

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#106]
OK, so let's open a dedicated discussion about `AbstractEvolutionaryAlgorithm.evaluatePopulation(population)`.

Summary of the perspectives so far:
- this method is misleading because it returns a population instead of evaluations
- if the methods aims only at evaluating the individuals in the population, so the returned population is conceptually the same, then this method is useless in the template because it does not provide added value for it
- this method makes sense because usual evolutionary algorithm description speak about evaluation the solutions of the population

Additionally, the current documentation states that:

> `evaluatePopulation(population)`: All the solutions in the `population` argument are evaluated and a population, which can be the same one passed as a parameter or a new one, is returned as a result.

This is counter-intuitive: changing the population is not a feature that one would usually expect from an evaluation method, and I doubt that any well known pseudo-code of an evolutionary algorithm would describe an evaluation process with such a feature. So it seems that there is a strong refinement to do here.

I would ask to see some of these pseudo-codes as examples, in order to ground the discussion with some concrete cases. But the best idea I have so far in order to fulfil all the perspectives listed would be to have a template which explicitly use the evaluations:

``` java
Population population = createInitialPopulation();

initProgress();
Map<S, Evaluation> evaluations = evaluate(population);
while (!isStoppingConditionReached()) {
    List<S> selectedIndividuals = selection(population);
    List<S> offsprings = reproduction(selectedIndividuals);
    evaluations.putAll(evaluate(offsprings));
    population = replacement(population, offsprings, evaluations);
    updateProgress();
}
```

where we have `Map<S, Evaluation> evaluate(Iterable individuals)`. The advantage is that it is close to the initial idea, but it enforces to have `Population extends Iterable<S>` and it enforces to return a `Map` which can be modified. If we want to get rid of the second constraint, we may create the map by ourselves:

``` java
Population population = createInitialPopulation();
Map<S, Evaluation> evaluations = new WeakHashMap<>();

initProgress();
evaluations.putAll(evaluate(population));
while (!isStoppingConditionReached()) {
    List<S> selectedIndividuals = selection(population);
    List<S> offsprings = reproduction(selectedIndividuals);
    evaluations.putAll(evaluate(offsprings));
    population = replacement(population, offsprings, evaluations);
    updateProgress();
}
```

The choice of the `WeakHashMap` is to avoid performance issues due to storing obsolete solutions: the keys are weak references, so if nothing else stores a solution, the map will not forbid it to be garbage collected, and if it is then the entry itself will be garbage collected. In particular, the individuals stored in `population` and `offsprings` will not be garbage-collected during the iteration, while any individual which is not stored in the population at the end of the iteration may be garbage-collected after the iteration.

If we want to allow any kind of population, the problem arises that `population` and `offsprings` have a different type, so we cannot use the same evaluation method on both. One could think that we could evaluate the individuals separately, because they are of the same type `S`, so we have `Evaluation evaluate(S solution)` to apply to each individual (initial population + offsprings), but to obtain the solutions contained in the population, we need it to be at least `Iterable` again (or to have an additional method which provides an `Iterable` from the population, but I think it is too much). So it won't solve the problem. The point is that we anyway ask to have evaluations for each individual, so it could make sense to restrict the evaluation method to a single solution and have a more detailed process in the template:

``` java
Population population = createInitialPopulation();
Map<S, Evaluation> evaluations = new WeakHashMap<>();

initProgress();
for(S individual : population) {
    evaluations.put(individual, evaluate(individual));
}
while (!isStoppingConditionReached()) {
    List<S> selectedIndividuals = selection(population);
    List<S> offsprings = reproduction(selectedIndividuals);
    for(S individual : offsprings) {
        evaluations.put(individual, evaluate(individual));
    }
    population = replacement(population, offsprings, evaluations);
    updateProgress();
}
```

We may also directly optimize it by not asking the ones already evaluated:

``` java
Population population = createInitialPopulation();
Map<S, Evaluation> evaluations = new WeakHashMap<>();

initProgress();
for(S individual : population) {
    evaluations.put(individual, evaluate(individual));
}
while (!isStoppingConditionReached()) {
    List<S> selectedIndividuals = selection(population);
    List<S> offsprings = reproduction(selectedIndividuals);
    for(S individual : offsprings) {
        if (evaluations.contains(individual)) {
            // do not re-evaluate
        } else {
            evaluations.put(individual, evaluate(individual));
        }
    }
    population = replacement(population, offsprings, evaluations);
    updateProgress();
}
```

Thus, we might have a well monitored evaluation process if we keep the `Population extends Iterable<S>` constraint.

While this last version would seem fine to me (and it can be applied to `PESA2` as long as `Archive` extends `Iterable<S>`), I need more information about the cases where the population may be modified during the evaluation. So far, it seems it may happen in distributed environments, but for such an environment it may be that such a sequential template would not fit. So more information is needed to better understand the need here.

**Comment by Juanjdurillo** [comment]
I like very much the idea of having the evaluation information separated from the Solution itself. Actually, as far as I remember, it is not the first time you mention about having the separation between evaluated and non-evaluated solutions.
The WeakHashMap is awesome, I did not know about it.
