### ISSUE TITLE
Is the implementation of IGD metric correct?

### ISSUE THREAD

**Issue by White-Chen** [jMetal/jMetal#118]
I try to find some details in the reference which in the annotation of `InvertedGenerationalDistance.java`:
```
 * This class implements the inverted generational distance metric.
 * Reference: Van Veldhuizen, D.A., Lamont, G.B.: Multiobjective Evolutionary Algorithm Research:
 * A History and Analysis.
 * Technical Report TR-98-03, Dept. Elec. Comput. Eng., Air Force
 * Inst. Technol. (1998)
```
and just find something about the `GD metric` but nothing about the `IGD metic`. Then I find the right reference about `IGD metric`:
```
* Reference: Zhang, Qingfu, and Hui Li. "MOEA/D: A multiobjective evolutionary algorithm based 
* on decomposition." Evolutionary Computation, IEEE Transactions on 11.6 (2007): 712-731.
```
<center>![qq 20151026205917 =50](https://cloud.githubusercontent.com/assets/5842970/10729470/784d9982-7c24-11e5-83cb-181d01bed977.png)</center>
All paper using the IGD metric refer the above paper.

So after the read of reference paper, I think there is a little problem in the method:
```java
public double invertedGenerationalDistance(Front front, Front referenceFront) {
    double sum = 0.0;
    for (int i = 0 ; i < referenceFront.getNumberOfPoints(); i++) {
      sum += Math.pow(FrontUtils.distanceToClosestPoint(referenceFront.getPoint(i),
          front), POW);
    }

    sum = Math.pow(sum, 1.0 / POW);

    return sum / referenceFront.getNumberOfPoints();
  }
```
You sum the squre of distance and extract a root of the sum. But in `reference: MOEA/D`, we just need get the sum of distance and divide the sum by referenceFront size. Obviously, summing the squre of distance and extracting the sum `≠` directly summing the diatance .

In my eyes, the correct implementation is:
```java
public double invertedGenerationalDistance(Front front, Front referenceFront) {
    double sum = 0.0;
    for (int i = 0 ; i < referenceFront.getNumberOfPoints(); i++) {
      sum +=FrontUtils.distanceToClosestPoint(referenceFront.getPoint(i), front);
    }

    return sum / referenceFront.getNumberOfPoints();
  }
```
if you do like this, you can find that the IGD values of all algorithms will be larger and more similar to that in many papers. 
I'm sorry, my English is not very good, I hope you can understand me.

**Comment by Juanjdurillo** [comment]
Dear White-Chen, 

we consider the IGD as the GD (generational distance) but changing the direction on which we measure  distances (from optimal front to approximation computed by an algorithm, and vice-versa). If you go then to the GD description in the book "Multi-Objective Optimization using Evolutionary Algorithms" by Prof. K. Deb, it is defined as you see in our code. 
The same definition for IGD as we have can be seen also in this paper https://www.researchgate.net/publication/220739956_Some_comments_on_GD_and_IGD_and_relations_to_the_Hausdorff_distance

Nevertheless, it may be interesting to have a look your proposal if you feel most papers are using that instead of the one commented in Prof. Deb's book or the commented paper.

**Comment by White-Chen** [comment]
Thank you for your reply.
I find the definition by Prof K.deb in `NSGA-III` algorithm is:
![image](https://cloud.githubusercontent.com/assets/5842970/10776924/f9893bc8-7d50-11e5-8688-661e68ee6636.png)
, and the reference of IGD metric is `MOEA/D algorithm`.

Of course, I also read paper you mentioned, in which K.deb discuss the value of p and use `p = 2`. So the definition of IGD maybe self contradictory for same author in different papers.

In fact, if you go then to the IGD description in paper which is a guide for CEC2009
```
Multiobjective optimization Test Instances for the CEC 2009 Special Session and Competition
```
you will find the definition is 
![image](https://cloud.githubusercontent.com/assets/5842970/10777090/b1122722-7d52-11e5-8504-4e651deb8bfc.png).
So I'm a little confused now, but fortunately the experiment is built on the same standard.

**Comment by Juanjdurillo** [comment]
The second reference is somewhat expected, since the authors are the same as the MOEA/D algorithm. I think the key is the p value as you mention here. We should provide in jMetal the oportuntity of setting this value so we cover the current measurment and your proposal

**Comment by White-Chen** [comment]
That’s great O(∩_∩)O

**Comment by ajnebro** [comment]
We have just included a new constructor in the classes implementing the [GD](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/GenerationalDistance.java) and [IGD](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/InvertedGenerationalDistance.java) to allow to indicate the value of p.
