### ISSUE TITLE
Why the performance of NSGAII (new version) is always better then NSGAII45?

### ISSUE THREAD

**Issue by shaikatcse** [jMetal/jMetal#120]
Hi all,

Fist of all, there is a bug in NSGAII45. The offspring population is not evaluated. But my main question is why the performance of NSGAII (new version) is always better then NSGAII45? I wrote my own NSGAII version, still NSGAII (new version) perform always much better than NSGAII45. 
![ext_zdt6](https://cloud.githubusercontent.com/assets/5484585/10945383/7bed78be-831d-11e5-9f98-0b3853c93d03.jpeg)

Evaluations: 9000, populationSize: 30, crossover: SBX, mutation: polynomial same distribution index. Please ignore vertical lines in the figure. I did the test several times. So, it is not a coincidence.

**Comment by matthieu-vergne** [comment]
I would have gladly said that this is of course due to the improvement of the architecture, but that would be an ungrounded self-praise (i.e. mental masturbation).

Given the apparently regular error, isn't it a matter of numerical precision? Or maybe a value which was changed (fixed?) in the new version?

**Comment by shaikatcse** [comment]
I do not think any new values are fixed. NSGAII45 is recently implemented by Antonio in jMetal 5 framework.

**Comment by ajnebro** [comment]
After fixing the bug reported by shaikatcse I don't see any difference between `NSGAII` and `NSGAII45`. I'm trying with problems ZDT1, ZDT4, and ZDT6 and the fronts are very similar.

After all, both algorithms are the same: the only difference is that `NSGAII` is based on the `AbstractEvolutionaryAlgorithm` template and `NSGAII45` implements directly the `Algorithm` interface.

I implemented `NSGAII45` only as an example of algorithm following the same structure of the former jMetal 4.5 version, thinking on those users that can feel uncomfortable with using the provided templates.

**Comment by matthieu-vergne** [comment]
@shaikatcse, could you provide the datasets, settings, and custom code that you use? You may provide a zip file and tell how to use it.

**Comment by ajnebro** [comment]
> Evaluations: 9000, populationSize: 30, crossover: SBX, mutation: polynomial same distribution index

@shaikatcse, I have just noticed your parameter settings. I always run NSGA-II with "standard" settings: Evaluations: 25000, population size: 30.

**Comment by shaikatcse** [comment]
Hi all,

Here is the code I used:

    selectionOperator = new BinaryTournamentSelection<DoubleSolution>();
    
    double crossoverProbability = 0.9 ;
    double crossoverDistributionIndex = 10.0 ;
    crossover = new SBXCrossover(crossoverProbability, crossoverDistributionIndex) ;

    double mutationProbability = 1.0 / problem.getNumberOfVariables() ;
    double mutationDistributionIndex = 10.0 ;
    mutation = new PolynomialMutation(mutationProbability, mutationDistributionIndex) ;

    algorithm = new NSGAII<DoubleSolution>(problem, 9000, 30, crossover, 	mutation, selectionOperator, evaluator );
		   
    // algorithm = new NSGAII45<DoubleSolution>(problem, 9000, 30, crossover,mutation, selectionOperator, evaluator );
    
    AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm).execute() ;

>After all, both algorithms are the same:

Yes, both algorithms are identical in algorithmic point of view. But, there are significant differences in terms of results with number of evaluations are low. 

Regards,
Shahriar

**Comment by ajnebro** [comment]
Shahriar, 
  ok, let us check that.


Antonio

**Comment by shaikatcse** [comment]
The following figure shows the result of NSGAII (new) with only 300 and 600 evaluations with 30 individuals. It seems that with only 600 evaluations, it converges nicely. Very surprising for me!!!!!. 
![ext_zdt6](https://cloud.githubusercontent.com/assets/5484585/10966603/ebab7402-83b4-11e5-8198-985ff6c6f20d.jpeg)

Regards,
Shahriar

**Comment by ajnebro** [comment]
Shahriar, have you used these configurations in the former versions of jMetal?

I made a few tests comparing NSGA-II in jMetal 4.5 and jMetal 5.0. They shown that the latter is a bit slower, but I didn't paid attention to the quality of the fronts.

**Comment by shaikatcse** [comment]
Results of NSGAII (jMetal 4.5 version, not NSGAII45) and NSGAII (5.0 version). There is no comparison. 
![ext_zdt6](https://cloud.githubusercontent.com/assets/5484585/10967089/6520dba8-83b8-11e5-86b5-941efecebbd8.jpeg)

**Comment by ajnebro** [comment]
Hmmm, interesting ...

There are at least two differences in the two implementations:
- The default random generator in jMetal 5.0 uses Java's Random class; in jMetal 4.5 the generator was the same included in the original implementation of NSGA-II.
- The binary tournament in jMetal 4.5, called BinaryTournament2, created a permutation of all the solutions in the population and the parents to be crossed were taking sequentially from the permutation. In jMetal 5.0 we use for now a pure binary tournament.

 As I said before, I didn't notice any significant performance difference in the algorithms I tested, but I always used the same settings. 

 There is a number of random number generators in jMetal 5.0: Mersenne Twister and Well44497b. Perhaps it could be interesting to see if they affect the algorithm performance when using a low number of evaluations.

**Comment by shaikatcse** [comment]
BUt my question is that why NSGAII45 has so different performance compared to NSGAII. Does not NSGAII45 uses same random generators?

**Comment by matthieu-vergne** [comment]
@ajnebro, can't we force the random generator in order to ensure we use the same? If we do that and force it to start from the same seed, what happens? I don't see any seed setting in the custom code, but if you use different seeds when there is a random generator, there is no surprise in having different results. I know I am saying evidences, but the point is to reduce ass much as possible the uncertainties. I don't try it because I am quite busy now, so I can only give ideas.

**Comment by shaikatcse** [comment]
@matthieu-vergne, the question is that why not a single time NSGAII45 performs better than NSGAII or at least have same performance (if you consider uncertainty).

**Comment by ajnebro** [comment]
The random generator can be initialized with a same seed. No problem in this sense.

My workload currently is also very high. When I have time I will check the implementations of NSGAII and NSGAII45 to try to find out whey they produce differents results.

**Comment by shaikatcse** [comment]
@ajnebro, I have some time to explore, if you give me some direction to start. They seems very identical to me.

**Comment by shaikatcse** [comment]
@ajnebro, @matthieu-vergne, it seems I have got it. In NSGAII, iteration works as generations. so,

    algorithm = new NSGAII<DoubleSolution>(problem, 9000, 30, crossover,    mutation, selectionOperator, evaluator );
means 9000 generations with 30 individuals. whereas, 
    algorithm = new NSGAII45<DoubleSolution>(problem, 9000, 30, crossover,mutation, selectionOperator, evaluator );
means 9000 evaluations with 30 individuals (i.e., 300 generations).

**Comment by ajnebro** [comment]
I changed both algorithms to use evaluations instead of iterations, but I'm affraid that I updated the repository with the changes yesterday.

The problem with using iterations is that, if we use for example a local search, the number of iterations will not be affected, and that could lead to unfair comparisons.

**Comment by matthieu-vergne** [comment]
OK. Then @shaikatcse can try with the new version and, if it does not solve the problem, I may try to check the code too. I am not familiar with it, so maybe I will better identify the subtle differences.

**Comment by shaikatcse** [comment]
@matthieu-vergne, thanks. For now, the issue is resolved. I'll inform you if I face some problem in future.

**Comment by matthieu-vergne** [comment]
ok
