### ISSUE TITLE
Does experiment work as it was on jMetal 4.5?

### ISSUE THREAD

**Issue by shaikatcse** [jMetal/jMetal#122]
Hi there,

I am not able to run experiments as it was run on jMetal 4.5. If it is okay in 5.0 version, can you please inform me how to perform.

Thanks.
Best regards,
Shahriar

**Comment by matthieu-vergne** [comment]
Well, in 5.0 you don't {'^_^}. It has not been ported yet. Maybe there is some remnant of the 4.5, but as far as I remember (I worked on that but did not touch it since a while) there is some pieces of an experiment framework in the commits, none of them being part of 5.0.

**Comment by shaikatcse** [comment]
Well :( then I need to convert back my code from version 5.0 to 4.5.

**Comment by ajnebro** [comment]
Hi Shahriar.
  As Matthie said, there is not yet support for experiments in jMetal 5.0. In the meantime, what I do is to use a Python script to run the algorithms. Once all of them are finished, I configure an experiment with jMetal4.5 to make all the statistical processing.

**Comment by shaikatcse** [comment]
Hi @ajnebro,
Therefore, the idea is to run the algorithms multiple times (let say not by python script, may be from inside the framework). Then use jMetal4.5 experiment class for statistical analysis. Right?

Regards,
Shahriar

**Comment by ajnebro** [comment]
Hi Shahriar.
  We have just included a first version of experimental support in jMetal 5.

  If you want to try, there are some examples in: https://github.com/jMetal/jMetal/tree/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment

  If you have any question or suggestion, please feel free to comment it here.
 

Antonio
