### ISSUE TITLE
WFG problems' true Pareto Front

### ISSUE THREAD

**Issue by mina111** [jMetal/jMetal#127]
Hi,

It seems there are no implementation of WFG problems' true Pareto Fronts in jMetal. The original code  of generating true PFs on the link http://www.wfg.csse.uwa.edu.au/toolkit/ has errors for WFG1 and WFG2... 

So do you know where can I find the true Pareto Front code of all the nine WFG problems?

Thanks,
Wenwen

**Comment by ajnebro** [comment]
Hi Wenwen.  
  I've taken a look to the fronts provided by other framework and ... they are the ones we obtained with the toolkit some years ago.
  
  We didn't were aware that the toolkit produced wrong fronts. Having into account that the WFG problems are widely used, particularly in many-objective optimization studies, this issue can lead to wrong conclusions in the papers.
 
  I'm going to contact other researchers about this. 


Antonio

**Comment by mina111** [comment]
Hi Antonio,

Thank you very much for the reply and looking into the issue carefully.
Really appreciate that! :)

Maybe it is also a good idea to contact the original authors of WFG toolkit
to address the issues so that they can update their website as well. In
addition, I think it can be very helpful if the generating code of true
fronts of WFG problems can be implemented in jMetal. So it would be easier
for researchers to scale up the WFG problems (such as more than 3
objectives) and obtain the associated true Pareto fronts, cuz so far,
jMetal's website only provides up to 3 objectives true front data without
implementation code for generating these data for WFG problems.   :)

So what are your thoughts about the above two suggestions.

Cheers,
Wenwen

**Comment by ajnebro** [comment]
HI Wenwen.
 The matter is that if you take a look to the authors of the first WFG papers, Simon Huband, he doesn't belong to the WFG group since 2007 (at least this is the year of his last paper according to DBLP); the only remaining author of the original paper is Lindon While.

  The problem is this sentence in the project page: "Last updated 28 March 2006. Note that we are unable to provide support for the use of this toolkit."
 

Antonio

**Comment by mina111** [comment]
Hmm, not support for the use of this toolkit but maybe they can still
answer some research questions about their paper..

No worries, Antonio. Thank you for providing the information. I will try to
contact Lindon While for some research questions about generating the true
fronts...

Many thanks,
Wenwen

On Tue, Dec 22, 2015 at 11:12 AM, Antonio J. Nebro <notifications@github.com
