### ISSUE TITLE
`minimumDistance` in MOCHC is always zero

### ISSUE THREAD

**Issue by darkuranium** [jMetal/jMetal#128]
In [line 166 of MOCHC.java](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/mochc/MOCHC.java#L166), you have the following statement:

``` java
minimumDistance = (int) (1.0 / size * (1 - 1.0 / size) * size);
```

It can be simplified to the following (floating-point precision issues notwithstanding):

``` java
minimumDistance = (int) (1 - 1.0 / size);
```

Since `size` is positive (it is the number of bits in the problem), and since `double` to `int` cast works via truncation, the result is always `0`.

For example, if `size` is `1` (min. possible value), then the result is `0`. If `size` is very large, then the result approaches `1`, but never reaches (or exceeds) that value &mdash; so it is still truncated to `0`.

**Comment by ajnebro** [comment]
Thanks for reporting it.

We designed MOCHC many years ago and I don't remember right now why we changed the expression for updating the minimum distance. Taking a look to older versions of jMetal, we had the following expression commented:

``` java
      minimumDistance = (int) (0.35 * (1 - 0.35) * size);
```

I'm taking a look to it.

**Comment by darkuranium** [comment]
Yes, the version I had still had both lines &mdash; the one you've pasted is commented out.

Looks like the constant `0.35` (which, granted, is somewhat of a bad practice &mdash; being a magic number and all) was replaced with `1.0 / size`.

**Comment by ajnebro** [comment]
Curiously, 0.35 is the probability of the cataclismic mutation in the original CHC algorithm.
