### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by Ravby** [jMetal/jMetal#131]
For normalization of approximations I use the reference Pareto front contained in the files. So the maximum and minimum values for each objective are obtained from the reference. But what if the approximation set has bigger max values than the reference set? I noticed this when solving the unconstrained problem 1 from the CEC2009 competition. The normalized reference is not in the range [0,1] because it has bigger max values than the reference set.

**Comment by matthieu-vergne** [comment]
I am not familiar with the normalization requirements you are speaking about, but:
- if it must be in [0;1], then normalize based on the *reachable* values, not just the values of a given front ;
- if the normalization just allows to scale the values for reasonable comparison, then the fact that it remains in [0;1] is not a requirement (only the scaling is a requirement) and so what you mention is not a problem.

But surely someone else would have a better answer if what you want to know is what are the usual practices.

**Comment by Ravby** [comment]
Yes I would like to know the usual practices. The code in jMetal uses the max and min values form the reference Pareto front, which may not contain the possible max and min values of all objectives. As you said, I was thinking that for the normalization I should take the max and min reachable values. But the question is what are these values? The max values are usually in the reference point for hypervolume.

**Comment by ajnebro** [comment]
The normalization issue was discussed here: https://github.com/jMetal/jMetal/pull/62

We hope you can find there the anwer to your question.

**Comment by Ravby** [comment]
Yes I found the answer. Thank you!
