### ISSUE TITLE
Weighting strategies

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#133]
Here I open an issue for designing classes dedicated to weighting strategies, in particular for normalization purpose but not only. The point here is to factor common concepts that we retrieve in many algorithms into dedicated classes which can be reused in these algorithms, rather than each having to implement its own.

This issue continues the discussion started in the pull request #132.

**Comment by ajnebro** [comment]
Let's include here the (updated) list of algorithms in jMetal 5.1 sharing weighting strategies and scalarizing strategies:
* MOEA/D (and variants): 
 * Three aggregation schemes (TCHE, PBI, AGG) implemented in the `fitnessFunction()` method in class `AbstractMOEAD`
 * A method `initializeUniformWeight()` to compute/read the weights
 * A method `fitnessFunction()` to escaralize the multi-objective problems.
* MOMBI/MOMBI2:
 * An abstract class `AbstractUtilityFunctionsSet` with methods `evaluate()` and `loadWeightsFromFile()`
 * Two subclasses of AbstractUtilityFunctionsSet: `ASFUtilityFunctionSet` and `TchebycheffUtilityFunctionsSet`
* WASFGA/GWASFGA:
 * A `WeightVector` class with methods such as `initUniformWeights2D()` and `getWeightsFromFile()`.
 * Shares with MOMBI/MOMBI2 the code for managing weight vectors
* DMOPSO
 * Share (copy) the methods of MOEA/D for initializing weights and its `fitnessFunction()`

**Comment by ajnebro** [comment]
Another issue to take into account: some of the aforementioned algorithms use a reference point. I created a [referencePoint](https://github.com/jMetal/jMetal/tree/master/jmetal-core/src/main/java/org/uma/jmetal/util/referencePoint) package with two initial implementations (`IdealPoint` and `NadirPoint`).

**Comment by matthieu-vergne** [comment]
Currently closing my PhD thesis, so really busy. I see the jMetal notificaiton e-mail stacking up... but I cannot deal with them for the moment. Hopefully soon after March 14th. {'^_^}

**Comment by matthieu-vergne** [comment]
Looking at the MOEA/D, you have these TCHE, PBI, AGG. If I look at `fitnessFunction()`, it seems that they need to consider:
- idealPoint (excepted AGG)
- lambda
- individual
- problem.getNumberOfObjectives()

Am I right by saying that the last one can be always retrieved from the size of lambda? It seems so from the constructor, but maybe I miss something.

**Comment by matthieu-vergne** [comment]
And as an additional question, do you test the values of your `fitnessFunction()` somewhere to ensure it is correct?
