### ISSUE TITLE
MOEAD Algoritm

### ISSUE THREAD

**Issue by HanrichPotgieter** [jMetal/jMetal#142]
When attempting to run the MOEAD Builder I get a thread interrupted exception. 
![image](https://cloud.githubusercontent.com/assets/8564706/14984923/7fdd6450-1145-11e6-8e43-f29dd8784d3a.png)

This is wsetting up an standard experiment as per the included examples.

![image](https://cloud.githubusercontent.com/assets/8564706/14984891/549d78de-1145-11e6-977b-8a75d4f8efd9.png)

I am not sure why this is happening. Perhaps it is due to the default parameters not being correct.

**Comment by HanrichPotgieter** [comment]
The first exception that is being raised is that of 
![image](https://cloud.githubusercontent.com/assets/8564706/14985046/fb697032-1145-11e6-96a8-ee5b5d9fef1c.png)

**Comment by HanrichPotgieter** [comment]
The issue seems to arise when using more than 2 objectives for a multi optimization problem. The issue does not happen when using only 2 objectives.

**Comment by ajnebro** [comment]
Hi Hanrich.
  MOEA/D requires a file containing the weights that are required. We provide a number of files, just take a look to directory `jmetal-core/src/main/resources/MOEAD_Weights/`.

  The file names follow this scheme: `WaD_b.dat`, where `a` is the number of functions of the problem and `b` is the population size.  You are solving a 4-objective problem with a population of 300, and the W4D_300.dat file is not included. 

  You should create (of find) the file of weights you need.



Antonio

**Comment by matthieu-vergne** [comment]
Should we close this issue?
