### ISSUE TITLE
HUXCrossover defect in jMetal 5.0

### ISSUE THREAD

**Issue by guv** [jMetal/jMetal#148]
After a (too) large amount of debugging I realized that the HUXCrossover in jMetal 5.0 is broken.
It doesn't use the variables of the second parent and modifies the solutions in place (in contrast to SinglePointCrossover).

On the current master branch this is already fixed.
Could you please communicate known severe errors such as this one somewhere prominently?
That would save your users considerable amounts of time.

Is it possible to get a bug fix release?

Thank you for your work.

**Comment by matthieu-vergne** [comment]
There is a 5.1 version in preparation:
https://github.com/jMetal/jMetal/tree/Version5.1

I don't remember for when it is planned to be released, though.

**Comment by ajnebro** [comment]
> Could you please communicate known severe errors such as this one somewhere prominently?
That would save your users considerable amounts of time.

> Is it possible to get a bug fix release?

I'm sorry you have wasted time in a solved bug. I will pay attention to that from now on and all the fixed bugs will be clearly indicated.

**Comment by ajnebro** [comment]
> I don't remember for when it is planned to be released, though.

There is not a planned date for the new version. It could be released righ now, but I should devote time to write at least a minimum documentation before that.

**Comment by guv** [comment]
Thanks, documenting the fixed bugs, especially the critical ones will be really helpful.
