### ISSUE TITLE
SMPSOMeasures never stops running

### ISSUE THREAD

**Issue by fernandocamargoti** [jMetal/jMetal#161]
It's a subclass of SMPSO, but it creates its own iterations counter, while not calling super.updateProgress() to update the super class' iterations counter. That would be ok if it overrided the isStoppingConditionReached() method, but it's no the case. So, it runs forever, never reaching its stopping condition.

**Comment by ajnebro** [comment]
Hi Fernando.
Thanks for reporting the bug. I've just fixed it.


Antonio

**Comment by matthieu-vergne** [comment]
So shouldn't it be closed?

**Comment by ajnebro** [comment]
Of course
