### ISSUE TITLE
Implementation of  Fast Hypervolume-Based Many-Objective Optimization

### ISSUE THREAD

**Issue by minawenli** [jMetal/jMetal#164]
Hi,

May I ask if Fast Hypervolume-Based Many-Objective Optimization (HypE) can be implemented in jMetal? This MOEA is proposed by Johannes Bader and Eckart Zitzler.

Paper source: http://www.tik.ee.ethz.ch/sop/publicationListFiles/bz2008a.pdf
Code source: http://www.tik.ee.ethz.ch/pisa/

Thanks,
Wenwen

**Comment by cbarba** [comment]
Hi Wenwen  I implemented an HypE for jMetal 4.5 two years ago, so it is possible to be implemented, when I find the time I want to update HypE for jMetal 5 however, if you want to do it, we will be grateful.

**Comment by mina111** [comment]
Hi,

Thank you very the reply. But it seems HypE is not in jMetal4.5.2, the latest version on http://jmetal.sourceforge.net/ Please find the screenshot. 
![jmetalscreenshopt](https://cloud.githubusercontent.com/assets/9783301/18645688/1f20488e-7ea6-11e6-8d50-66711dd69df1.JPG)

Would you please have a check on that?

Many thanks,


Wenwen

**Comment by matthieu-vergne** [comment]
It is also not in this repo, which also have the old version. Maybe you could share the code of your implementation?

**Comment by mina111** [comment]
Hi Matthieu-vergne,

I haven't implemented HypE in Java. I was looking for it on jMetal, but I cannot find it in jMetal 4.5.2 or the latest version on GitHub... Your colleague cbarba said it is already implemented in jMetal. Wondering which version of jMetal HypE was implemented in?

Thanks,
Wenwen

**Comment by matthieu-vergne** [comment]
Actually, my post was for cbarba. (S)He told that it has already been implemented for jMetal, but it is not part of it. Unless it is under a name which does not include HypE.

**Comment by ajnebro** [comment]
Cristóbal made the implementation of HypE on a old version of jMetal but we didn't put the algorithm in a release version.

**Comment by mina111** [comment]
Hi Antonio,

So do you plan to release the implementation of HypE in jMetal in the near future?

Thanks,
Wenwen

**Comment by GoodLittleStar** [comment]
Hi Wenwen, I found a cloased issue about how to obtain the true pareto front of WFG test suit that created by you I think. If you find the way now, would you please share the method to us, thanks much.

**Comment by mina111** [comment]
Hi,

Thanks for still interested in this issue. But no, I didn't write a tool to
generate the true Pareto front of WFG, but if I am not wrong I remember Dr.
Markus Wagner (markus.wagner@adelaide.edu.au) and his co-authors generated
their own WFG true fronts for their AGE paper
http://www.sciencedirect.com/science/article/pii/S0377221714009552 . Maybe
you can ask Markus about the tool that they used for generating the true
Pareto fronts?

Best wishes,
Wenwen
