### ISSUE TITLE
Generational Data

### ISSUE THREAD

**Issue by shelvin29** [jMetal/jMetal#168]
Hi,

I wanted to know if there are any existing methods or classes within jmetal to capture generational data and store it in files similar to how the experiment class allows for the final x and f values to be written to file. Ideally I would be interested in the ND set after each generation. This is to capture convergence of the population. 

Thanks!

**Comment by ajnebro** [comment]
Hi.
  You can use [measures](https://github.com/jMetal/jMetalDocumentation/blob/master/measures.md) for that purpose. To see how they works, we include a variant of NSGA-II using measures in the [NSGAIIMeasures class](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/nsgaii/NSGAIIMeasures.java) and its corresponding [NSGAIIMeasuresRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/NSGAIIMeasuresRunner.java) class. This latter class illustrates how measures can be captured and used.
