### ISSUE TITLE
Results of analyzing the project with SonarQube

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#169]
<img width="1108" alt="captura de pantalla 2016-10-26 a las 18 55 24" src="https://cloud.githubusercontent.com/assets/1889196/19735952/eed3f548-9bad-11e6-8056-85b3810440ec.png">

**Comment by matthieu-vergne** [comment]
Could you describe a bit or give a link to a page which tells how to interpret the results?

**Comment by ajnebro** [comment]
I would suggest you to follow the "Starting in Two Minutes" guide: http://docs.sonarqube.org/display/SONAR/Get+Started+in+Two+Minutes

Once you have the software installed, the sonar-project.properties is in the root directory of the project, so you only have to run the sonar-scanner tool and then you can browse the analysis report in http://localhost:9000
