### ISSUE TITLE
A little bug in class *org.uma.jmetal.util.archive.impl.AdaptiveGridArchive*

### ISSUE THREAD

**Issue by SunnyWind** [jMetal/jMetal#170]
In the method *prune* of class *org.uma.jmetal.util.archive.impl.AdaptiveGridArchive*, there is a bug.

```
 public void prune() {
    Iterator<S> iterator = getSolutionList().iterator();
    boolean removed = false;
    while (iterator.hasNext()) {
      if (!removed) {
        S element = iterator.next();
        int location = grid.location(element);
        if (location == grid.getMostPopulatedHypercube()) {
          iterator.remove();
          grid.removeSolution(location);
          removed = true ;
        }
      }
    }
  }
```
When one solution is removed, the flag `removed` will be true, and the if closure will never be executed. That is, the statement `iterator.next()` will not be executed thereafter, and the program will fall into death loop of `while(iterator.hasNext());`

The flag `removed` could be removed in this way:
```
  public void prune() {
    Iterator<S> iterator = getSolutionList().iterator();
    while (iterator.hasNext()) {
        S element = iterator.next();
        int location = grid.location(element);
        if (location == grid.getMostPopulatedHypercube()) {
          iterator.remove();
          grid.removeSolution(location);
          return;
        }
    }
  }
```

**Comment by matthieu-vergne** [comment]
Seems relevant. It's a pity that we need both `iterator.remove()` and `grid.removeSolution(...)`, otherwise we could have used Java 8 streams.

**Comment by ajnebro** [comment]
SunnWind, thanks for reporting the bug. I've just fixed it.
