### ISSUE TITLE
A few questions about 'Quality Indicators'

### ISSUE THREAD

**Issue by jose** [jMetal/jMetal#171]
Hi,

First of all let me say that you have done an amazing job. jMetal is likely the best framework out there for multi-objective optimization studies. :+1:

I have a few questions about quality indicators and how to use them. (please forgive my lack of knowledge about quality indicators)

- Are the quaility indicators implemented on jMetal the best known metrics and the most common ones?
- It seems that [CommandLineIndicatorRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/qualityIndicator/CommandLineIndicatorRunner.java) does not use R2 (it's actually commented out). Why is that? Is R2 buggy?
- Why is [PISAHypervolume](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/PISAHypervolume.java) the default Hypervolume metric? Does it work better than for example, [WFGHypervolume](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/WFGHypervolume.java)?
- Each quality indicator requires a _Front_ and a _Reference Pareto Front_. What is a reference pareto front? Is it the true pareto front? Assuming that I am not evaluating any of the typical problems (e.g., ZDT-1) and therefore I do not have the true pareto front, what would be my reference pareto front?
- The [Epsilon](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/Epsilon.java) class implements the _unary epsilon additive indicator_, does that mean I have to use Epsilon metric with an approximation set and a reference set? Or does not matter, and I can still use Epsilon class with two approximation sets, i.e., as a binary epsilon rather than unary?

--
Cheers,
Jose

**Comment by jose** [comment]
> Each quality indicator requires a Front and a Reference Pareto Front. What is a reference pareto front? Is it the true pareto front? Assuming that I am not evaluating any of the typical problems (e.g., ZDT-1) and therefore I do not have the true pareto front, what would be my reference pareto front?

Assuming that I use more than one moo-algorithm, could the reference pareto front be the set of non-dominated solutions found by the union of all moo-algorithms? If yes, is there any algorithm (either on jMetal or any research paper) that I should be aware of?

**Comment by ajnebro** [comment]
Hi Jose.
  It's nice to have new from you :)

> Are the quaility indicators implemented on jMetal the best known metrics and the most common ones?
Yes

> It seems that CommandLineIndicatorRunner does not use R2 (it's actually commented out). Why is that? Is R2 buggy?
The R2 is not completely implemented (only works for bi-objective problems), so I decided to not use it.

> Each quality indicator requires a Front and a Reference Pareto Front. What is a reference pareto front? Is it the true pareto front? Assuming that I am not evaluating any of the typical problems (e.g., ZDT-1) and therefore I do not have the true pareto front, what would be my reference pareto front?
Most of indicators require the Pareto front to be computed, but this front is rarely obtained with dealing with real-world problems. The most commoly used strategy is to build a reference Pareto front, which is composed of the result of merging all the solutions obtained by all the algorithms in all their runs. 
> Why is PISAHypervolume the default Hypervolume metric? Does it work better than for example, WFGHypervolume?
PISAHypervolume is based on the original implementation of Eckart Zitzler, and I would say that yes, it is the default HV indicator. WFGHypervolume is a different implementation which is faster when solving bi-objective problems (in part because it doesn't normalize the objetives values, as PISAHypervolume does).

>The Epsilon class implements the unary epsilon additive indicator, does that mean I have to use Epsilon metric with an approximation set and a reference set? 
Yes.

> Or does not matter, and I can still use Epsilon class with two approximation sets, i.e., as a binary epsilon rather than unary?
Hmmm, I'm not sure. I shold take a look to the implementation.

**Comment by ajnebro** [comment]
> Assuming that I use more than one moo-algorithm, could the reference pareto front be the set of non-dominated solutions found by the union of all moo-algorithms? If yes, is there any algorithm (either on jMetal or any research paper) that I should be aware of?

Yes (I have answered this question before). No, you only need an archive to store non-dominated solutions and add to it all the solutions found by all the algorithms (as the [NonDominatedSolutionListArchive](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/archive/impl/NonDominatedSolutionListArchive.java)).

**Comment by jose** [comment]
Hi @ajnebro,

Many thanks for your quick reply. Your answers were very helpful. :-)

Once again, well done jMetal's contributors. :+1: 



Cheers,
Jose
