### ISSUE TITLE
How to generate reference Pareto fronts ?

### ISSUE THREAD

**Issue by tarunchhabra26** [jMetal/jMetal#179]
Hi I am currently working on an experiment to compare different optimizers on a given problem. My problem doesn't have a reference pareto front yet. Is there a way one can generate the reference pareto front using jMetal ? If yes could you please provide some snippet which might be of help ? 
If not what is the best method to do so ?
Many thanks !

**Comment by jacksonpradolima** [comment]
@tarunchhabra26, see the Issue [171](https://github.com/jMetal/jMetal/issues/171).

#171

**Comment by tarunchhabra26** [comment]
Hi @jacksonpradolima 
Thanks for pointing me to the right resource.

**Comment by jacksonpradolima** [comment]
@tarunchhabra26 there is a application that can help you, the [analysis](https://github.com/jacksonpradolima/analysis/releases/tag/1.1).
It's simple, but can help you.

**Comment by tarunchhabra26** [comment]
hi @jacksonpradolima,

I tried using the jar file but I am unable to open the *.tsv files using it. Kindly advice. I am using macOS Sierra.

**Comment by jacksonpradolima** [comment]
Hi @tarunchhabra26,
We are using the jMetal4.5 yet. In the future, we will implement it using the jMetal in the last version.
So, I suggest that you remove the ".tsv" from each file. You can do it with a simple Java code.

Anything I'm at disposal

**Comment by tarunchhabra26** [comment]
@jacksonpradolima Thanks ! Fortunately I was able to generate a reference pareto using this example code base in jMetal : https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment/BinaryProblemsStudy.java
