### ISSUE TITLE
Attributes of entities

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#181]
There is an issue related to the algorithms and problems in the experimentation classes of jMetal that I'm not sure about how to deal with.

An experiment consists in defining a list of algorithms that will solve a list of problems. Once the experiment is configured, it can be executed, resulting in a lot of information (the FUN and VAR files of all the experiments, Latex tables and R scripts). To organize the result files, they are stored in a tree with this structure: experiment -> algorithmName -> problemName.To get the algorithm name I use the `getName()` method due that the `Algorithm` interface extends `DescribedEntity`; in the  case of the problems, the `Problem` interface has a `getName()` method (perhaps it should extende also `DescribedEntity`).

The issue is that we can be interested in a experiment based on several variants of a same algorithm, so they I found the problem of how to name the algorithm variants, because all of them have the same name. The adopted solution was to define a `TaggedAlgorithm` class that applies the decorator pattern to allow to add a tag to the algorithms (plus a iteration number and the problem to be solved). An example can be found  in the [NSGAIIStudy](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment/NSGAIIStudy.java). I'm nor particularly happy with this solution, but it works.

My problem now is with the problems. A colleague asked me if I could define an experiment using several variants of same problem (e.g. problems such as ZDT and DTLZ are scalable, so many variants of them can be defined according to the number of variables and objectives). I thought at a first glance to use again the decorator pattern, but it is not so simple. 

So I'm wondering if it could make sense to have something like an `AttributedEntity` interface that could be extended not only by the problems and algorithms, but also to replace the attributes in the solutions.

**Comment by matthieu-vergne** [comment]
Duplicate of issue #129? You may propose something new with your attribute-based solution, but the problem seems the same, so I would recommend you say it in the old issue.

**Comment by ajnebro** [comment]
You are right, I already opened an issue about that before.
