### ISSUE TITLE
Find the Max Solution

### ISSUE THREAD

**Issue by uMklami** [jMetal/jMetal#183]
Dear concern,
while using nsga2 from jMetal, i have created a problem with upper and lower bounds for finding the max solution for it. but i didn't find it in jMetal. it always gives me the combinations with minimal values. Kindly help me in finding the combination with the max value.

thanks

**Comment by matthieu-vergne** [comment]
The implementation of NSGA2 aims for minimising, not maximising. If you want to maximise, you have to reverse your values in order to minimise them. Please consider issue #143 which might be smilar.

**Comment by uMklami** [comment]
Yes issue#143 is somehow same like mine, and hopefully it will solve my problem. thanks for your cooperation.

**Comment by matthieu-vergne** [comment]
If it does, please close this issue to confirm.
