### ISSUE TITLE
Change some private atributes to protected

### ISSUE THREAD

**Issue by vinixnan** [jMetal/jMetal#185]
I would like to set crossovers, mutations and algorithms atributes as protected. So, I could use inheritance properly.

Is there any chance of this kind of pull request be accepted?

**Comment by matthieu-vergne** [comment]
Any pull request could be accepted as long as it is clearly better. We cannot tell in advance before to see the real thing and evaluate it. Just make a pull request, even if it is not accepted as is it may lead to refinements anyway. But don't forget to motivate the pull request (explain problem and justify the change if it is not trivial).

**Comment by ajnebro** [comment]
The crossover, mutation and selection operators are protected in the `AbstractGeneticAlgorithm` class, so in principle you could apply inheritance normally.

**Comment by vinixnan** [comment]
For example, 

In my research, I need to change all crossover/mutation parameters in execution time. For example in BLXAlphaCrossover, would be nice to be able to change alpha and probabilities values in execution time. It can be assured by set methods os protected attributes.

I need to swap between algorithms and execute just one generation. Thus, If I have protected attributes in this kind of class, I could extend It and overhide the methods. Sometimes users may extend class such NSGA-II, SPEA2 and IBEA and just override methods to create new algorithms. I think It can make our projects cleaner.

Currently, I just copy and paste these classes in my project and adapt them. However, I don't think that is the best possibility.

**Comment by ajnebro** [comment]
Ok. Let me thing about it. In general, I have no problem in declaring attributes as protected.

**Comment by ajnebro** [comment]
In the meantime, I have added setters to all the operator parameters.

**Comment by vinixnan** [comment]
Sorry, but I can not see any set method inside the operators. Could you add?

**Comment by ajnebro** [comment]
It seems that I didn't merge the changes to the master branch. Now you should find the updated operators with the setters methods.
