### ISSUE TITLE
Useless constructor

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#199]
I noticed that `DMOPSOMeasures` has 2 constructors, with one adding a `name` parameter. The issue is that this parameter is not used. So whether the constructor is useless, whether the parameter should be used.

**Comment by ajnebro** [comment]
We are using that class to test the [chartcontainer](https://github.com/jMetal/jMetal/tree/master/jmetal-core/src/main/java/org/uma/jmetal/util/chartcontainer) package which is being developed by a colleague. You can use the [DMOPSOMeasuresRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/DMOPSOMeasuresRunner.java) to see how it works.

It is a work in progress so surely we will need to review that class.
