### ISSUE TITLE
Useless protected

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#211]
I see that `AbstractGenericSolution` and `ArrayDoubleSolution` have a protected field `randomGenerator` which contains the `JMetalRandom` singleton. Because the singleton is how it is (i.e. unique and public), their is no need to make it shared through a protected variable. Implementations needing it should just call `JMetalRandom.getInstance()` by themselves. If it was an instance which may not be unique, it would have make sense, but because there can have only one `JMetalRandom`, and anyone can get it, the fields provide no added value.

Making these fields private might break existing code, but I think that they should at least be deprecated to ask implementations to call the singleton directly (or use something else). Ensuring that this field is not used is a requirement for a proper generalisation of random generators, so considering that it add no value because it uses a public singleton, I think it should be planned for future removal.

**Comment by matthieu-vergne** [comment]
[Here](https://github.com/matthieu-vergne/jMetal/blob/commitRandom/jmetal-core/src/main/java/org/uma/jmetal/solution/impl/AbstractGenericSolution.java#L35) is what I mean.

**Comment by ajnebro** [comment]
I agree.

**Comment by matthieu-vergne** [comment]
OK, so I can integrate that in my generalisation of random generators.
