### ISSUE TITLE
Useless recomputation?

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#212]
The class `AdaptiveRandomNeighborhood` has a method `recompute()`. This method is used [only once](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/test/java/org/uma/jmetal/util/neighborhood/impl/AdaptiveRandomNeighborhoodTest.java#L196) in the core project, in the tests of the class. If I understand well this code, the neighborhood is recomputed because it is first computed at the instantiation time, before you can setup the sequence of random numbers to use. Consequently, once you have setup the sequence, you recompute it before to test. Am I correct?

If yes, then I assume that, if we can ensure that the good sequence is given at instantiation time, there is no need to recompute. My refinements allow to provide a custom random generators to the constructor, so it can be set up before the instantiation. If I run the test with that, the test passes if we remove recomputation (and fails otherwise, because we use it twice).

Is it OK if I remove it because of my refinement? (you can see what I mean [there](https://github.com/matthieu-vergne/jMetal/blob/commitRandom/jmetal-core/src/test/java/org/uma/jmetal/util/neighborhood/impl/AdaptiveRandomNeighborhoodTest.java#L194))

**Comment by ajnebro** [comment]
This method is also used in two algorithms, `StandardPSO2007` and `StandardPSO2011`. 

Let me check it.

**Comment by matthieu-vergne** [comment]
Well, whether or not it is used elsewhere is not really important, the point is about this test. Is it OK to remove the recomputation in this specific test? If yes, maybe another test should be added specifically for the recomputation (if there is no such test yet, I did not check).
