### ISSUE TITLE
Operators and functional interfaces

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#214]
The `Operator` interface as only an `execute()` method. 

I'm wondering weather it would make sense to consider it as a functional interface.

**Comment by matthieu-vergne** [comment]
I don't think so. A Functional interface *aims* at requesting a single method (thus the name). If having a single method is not a fundamental requirement of an operator (and I think it is not) then it makes no sense to make it a functional interface. If it does have a single method, it can still be used in lambda expressions, but if it seems reasonable to have several method if deemed useful, then it must remain a normal interface.
