### ISSUE TITLE
How to determine/change PopulationSize for NSGAIII

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [jMetal/jMetal#219]
How to determine pop.size for NSGAIII in Jmetal 5. We could determine it in old versions of Jmetal. What is the number 12 determined for?
```
    numberOfDivisions.add(12) ; // Default value for 3D problems ???
    (new ReferencePoint<S>()).generateReferencePoints(referencePoints,getProblem().getNumberOfObjectives() , numberOfDivisions);
    int populationSize = referencePoints.size();

```

**Comment by ajnebro** [comment]
Hi.
  NSGA-III is only available on jMetal 5. Compared with other algorithms, including NSGA-II, you cannot set an arbitrary population size in NSGA-III, which depends on the number of objectives. Our implementation is based on this code: http://web.ntnu.edu.tw/~tcchiang/publications/nsga3cpp/nsga3cpp.htm

  To know about the population sizes in NSGA-III I would suggest you to read Deb's paper (http://ieeexplore.ieee.org/document/6600851/)
