### ISSUE TITLE
God object anti-pattern in experiments

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#221]
I am currently working on an experiment framework, so I am looking at the current code to see how I can help to improve it. And here is an anti-pattern that I could spot.

A [God object](https://en.wikipedia.org/wiki/God_object) is an object that knows or do many stuff, and thus on which many other objects will rely for their own reasons. Usually, a good factoring consists in finding common stuff and factor it into a dedicated class. The God object occurs when *different* features are centralized into a single class, thus making the responsibility unclear and tentacular.

This is what I can observe with `org.uma.jmetal.util.experiment.Experiment`. First, despite its name, it is not an experiment (i.e. something which produces an evaluation of some algorithm performances) but a configuration container. It stores many things, like the name of the experiment, the list of algorithms to run, the directory in which the results will be stored, the number of runs to perform on each algorithm, the number of cores to use, etc. Consequently, it is related to many responsibilities, like display, storage, execution, etc. It is still a *soft* God object, because it does nothing (the only behavioral method is the one which removes duplicate algorithms), but it is one.

Some clear disadvantages are:
- one must guess what to put in `Experiment`, because the code does not show which parameters are required for each step, as they all request only the God object.
- because of that, whether or not the right parameters are provided is checked at runtime, while with explicit parameters such a control would be made at compilation time.

A better way to go for now is to extract all the data from this God object and make relevant parameters for each class currently using it (`ExecuteAlgorithms`, `ComputeQualityIndicators`, etc.). This way, when you use them, you see clearly what is needed in the code.

If default parameters need to be used, one can simply make some static values somewhere, like an `ExperimentDefault` structure. It would be a temporary solution, because I think there is a lot of improvements which can be done regarding the responsibilities of each step, in order to remove some redundancies.

So what I suggest is to plan its removal (i.e. deprecate `Experiment` and related stuff, and remove its use in jMetal). I am currently working on that in a dedicated branch, so I can make a pull request for it. But first I would like to know your opinion about it.

**Comment by matthieu-vergne** [comment]
For example, here is what you have:
```java
String experimentBaseDirectory = args[0];

List<ExperimentProblem<BinarySolution>> problemList = new ArrayList<>();
problemList.add(new ExperimentProblem<>(new ZDT5()));
problemList.add(new ExperimentProblem<>(new OneZeroMax(512)));

List<ExperimentAlgorithm<BinarySolution, List<BinarySolution>>> algorithmList =
        configureAlgorithmList(problemList);

Experiment<BinarySolution, List<BinarySolution>> experiment;
experiment = new ExperimentBuilder<BinarySolution, List<BinarySolution>>("BinaryProblemsStudy")
        .setAlgorithmList(algorithmList)
        .setProblemList(problemList)
        .setExperimentBaseDirectory(experimentBaseDirectory)
        .setOutputParetoFrontFileName("FUN")
        .setOutputParetoSetFileName("VAR")
        .setReferenceFrontDirectory(experimentBaseDirectory+"/referenceFronts")
        .setIndicatorList(Arrays.asList(
                new Epsilon<BinarySolution>(), new Spread<BinarySolution>(), new GenerationalDistance<BinarySolution>(),
                new PISAHypervolume<BinarySolution>(),
                new InvertedGenerationalDistance<BinarySolution>(),
                new InvertedGenerationalDistancePlus<BinarySolution>())
        )
        .setIndependentRuns(INDEPENDENT_RUNS)
        .setNumberOfCores(8)
        .build();

new ExecuteAlgorithms<>(experiment).run();
new GenerateReferenceParetoFront(experiment).run();
new ComputeQualityIndicators<>(experiment).run();
new GenerateLatexTablesWithStatistics(experiment).run();
new GenerateWilcoxonTestTablesWithR<>(experiment).run();
new GenerateFriedmanTestTables<>(experiment).run();
new GenerateBoxplotsWithR<>(experiment).setRows(1).setColumns(2).setDisplayNotch().run();
```
In this code, you fill your `Experiment` with several things, but then we never see where it is used. All the steps after just take the whole configuration instead of the relevant pieces they need. This means that one need to go in the code of each piece to know what to fill in the `Experiment`. Meanwhile, if you remove `setIndependentRuns(INDEPENDENT_RUNS)` it will still run fine, because this one has a default value of 1, but if you remove `setOutputParetoSetFileName("VAR")`, you will know that there is something wrong only when running it, because `ComputeQualityIndicators` needs it... but you cannot guess it from this code.

Here is what I get by removing `Experiment`:
```java
String experimentBaseDirectory = args[0];

List<ExperimentProblem<BinarySolution>> problemList = new ArrayList<>();
problemList.add(new ExperimentProblem<>(new ZDT5()));
problemList.add(new ExperimentProblem<>(new OneZeroMax(512)));

List<ExperimentAlgorithm<BinarySolution, List<BinarySolution>>> algorithmList =
        configureAlgorithmList(problemList);

int numberOfCores = 8;
List<GenericIndicator<BinarySolution>> indicatorList = Arrays.asList(
        new Epsilon<BinarySolution>(), new Spread<BinarySolution>(), new GenerationalDistance<BinarySolution>(),
        new PISAHypervolume<BinarySolution>(),
        new InvertedGenerationalDistance<BinarySolution>(),
        new InvertedGenerationalDistancePlus<BinarySolution>()) ;
String referenceFrontDirectory = experimentBaseDirectory+"/referenceFronts" ;
String outputParetoFrontFileName = "FUN" ;
String outputParetoSetFileName = "VAR" ;
String experimentName = "BinaryProblemsStudy" ;

new ExecuteAlgorithms<>(algorithmList, INDEPENDENT_RUNS, numberOfCores, experimentBaseDirectory).run();
List<String> referenceFrontFileNames = new LinkedList<>();
new GenerateReferenceParetoFront(algorithmList, problemList, experimentBaseDirectory, referenceFrontDirectory, outputParetoFrontFileName, INDEPENDENT_RUNS, referenceFrontFileNames).run();
new ComputeQualityIndicators<>(algorithmList, problemList, indicatorList, experimentBaseDirectory, referenceFrontDirectory, referenceFrontFileNames, outputParetoFrontFileName, outputParetoSetFileName, INDEPENDENT_RUNS).run();
new GenerateLatexTablesWithStatistics(algorithmList, problemList, indicatorList, experimentBaseDirectory, experimentName).run();
new GenerateWilcoxonTestTablesWithR<>(algorithmList, problemList, indicatorList, experimentBaseDirectory).run();
new GenerateFriedmanTestTables<>(algorithmList, problemList, indicatorList, experimentBaseDirectory).run();
new GenerateBoxplotsWithR<>(algorithmList, problemList, indicatorList, experimentBaseDirectory).setRows(1).setColumns(2).setDisplayNotch().run();
```
Here, each step is clearly related to specific pieces of data, and if you remove `String outputParetoSetFileName = "VAR"` it just cannot compile, because it is explicitly requested by `ComputeQualityIndicators`. So you don't have to wait at runtime (and hope to have some clear exceptions coded manually) to fix it.

**Comment by ajnebro** [comment]
> But first I would like to know your opinion about it.

I commented some time ago that I didn't like the adopted approach for the experiments from a programming perspective. It's just a solution that works but has some flaws, as you have pointed out, so any improvement is welcome.

A point that must be taken into account is that the order of the steps is important: to generate the tables and boxplots it is mandatory to compute first the quality indicators, and to get the quality indicators the algorithms must have been executed previously.

**Comment by matthieu-vergne** [comment]
And you cannot guarantee that with your current architecture, because you completely hide these dependencies from the experimenter, leading you also to redo several stuff from scratch, like rebuild the full path of the files from the strings you give as parameters. Rather, you should think about each step as an input consumer and an output provider, not just a block to `run()` mindlessly. Then, the first one to build the whole paths will be the only one, and it will return a list of paths (or I don't know what) to give to the next steps. In my example above, I have adapted the code to remain compatible with old code, but if you want to ensure some order, at least you need to produce outputs explicitly for each intermediary step, like the quality indicators, and use them as inputs of the steps which should go after them, so you ensure that you cannot do them before you have the relevant inputs.

Typically, you need something like a [pipeline](https://en.wikipedia.org/wiki/Pipeline_(software)) here, like the collection streams introduced in Java 8, excepted that it is not a linear one (the results need to be send to various consumers). You can also make a [template method](https://en.wikipedia.org/wiki/Template_method_pattern), which gives a predefined processing but would be enough for your few implementations, because the process is always the same: configure, execute, consume. In my framework, I use the latter to rewrite your experiments, although I plan more advanced stuff.

So are you OK to go from scratch for an experiment framework, or do you want progressive changes? Soon we will have to break it anyway.

**Comment by ajnebro** [comment]
> So are you OK to go from scratch for an experiment framework

I agree. If we keep the current implementation (deprecating `Experiment` as you suggested) I don't see any advantage in a progressive changes approach.

**Comment by matthieu-vergne** [comment]
OK, so let's go back to issue #135 to have a discussion on the new framework.
