### ISSUE TITLE
NSGAIII EnviromentalSelection is removing multiple solutions per iteration when finding a niche reference point

### ISSUE THREAD

**Issue by Barbiero** [jMetal/jMetal#223]
Hiya

I'm currently using Jmetal on a project due to its NSGAIII algorithm, but I was surprised when it crashed on me with out-of-bounds exceptions when I ran my Problem, even though it worked perfectly fine on NSGAII.

After some investigation, I found that, when finding niche reference points at `EnvironmentalSelection#execute`, the iteration expects to remove one member per cycle:
```java
        while (source.size() < this.solutionsToSelect) {
            int min_rp = FindNicheReferencePoint();

            S chosen = SelectClusterMember(this.referencePoints.get(min_rp));
            if (chosen == null) // no potential member in Fl, disregard this reference point
            {
                this.referencePoints.remove(min_rp);
            } else {
                this.referencePoints.get(min_rp).AddMember();
                this.referencePoints.get(min_rp).RemovePotentialMember(chosen);
                source.add(chosen);
            }
        }
```

However, when looking at `ReferencePoint#RemovePotentialMember`, we see that the method is designed to remove multiple, equivalent, members when called:
```java
    public void RemovePotentialMember(S solution) {
      Iterator<Pair<S, Double>> it = this.potentialMembers.iterator();
      while (it.hasNext()) {
        if (it.next().getLeft() == solution) {
          it.remove();
        }
      }
    }
```

this means that, in the event that a `solution` might exist in duplicates(ie. two equivalent solutions might be generated if operators are too conservative), the method will end up removing multiple potential members out of the reference points, but will add only one member - eventually clearing out all reference points while not filling `source` with `solutionsToSelect` solutions, leading to `FindNicheReferencePoint` breaking trying to index an empty array.

I fixed this by simpling `break`ing the method, and now the algorithm is working properly for me; However, I'm not creating a pull request because I'm inexperienced and my approach might be wrong. Should it even be possible for duplicate `solution`s to exist within a `potentialMembers` list in the first place? Or maybe we could simply add a copy of the `chosen` object to `source` for each removed member?

The original paper's algorithm(section IV-E, Algorithm 4) is written in a way that it only removes a single point per iteration, so I feel like my approach is the correct - but I'd prefer to discuss this with more experienced people in the area before considering a PR for this particular issue.

Thank you for your time!

**Comment by matthieu-vergne** [comment]
Given that it is about the algorithm itself, not the code, I will let @ajnebro and @Juanjdurillo reply. Just wait for them to find some time to do so.

**Comment by ajnebro** [comment]
Hi @Barbiero 

We implemented NSGA-III from a C++ code and certainly I don't know that algorithm in detail. I have used it only once, and with the default settings. 

From your post, it seems clear that you have found a bug, so if you make a pull request I will accept it.

**Comment by matthieu-vergne** [comment]
If possible, with tests to avoid regressions. {^_°}

**Comment by Barbiero** [comment]
Seeing as this was merged already, I'll close the issue
