### ISSUE TITLE
Some Issues and sugestions

### ISSUE THREAD

**Issue by LucasLP** [jMetal/jMetal#224]
Some issues I found, sorry if some these already been solved...

1. Wilcoxon RScript at the /src/org/uma/jmetal/util/experiment/component/GenerateWilcoxonTestTablesWithR.java
	in generate R code, the path inside of scripts are relative of jar, but it needs to be relative of Rscripts.

2. Differencial Evolution need the variants "rand/2/bin" "current-to-rand/2/bin"
	in AbstractMOEAD modify the method "parentSelection" to select more solutions
	example:

	@Override
      protected List<DoubleSolution> parentSelection(int subProblemId, NeighborType neighborType, String variant) {
        List<DoubleSolution> parents = null;
        if (variant.equals("rand/1/bin") || variant.equals("rand/1/exp") 
                || variant.equals("current-to-rand/1/bin")){//|| variant.equals("best/1/bin") || variant.equals("best/1/exp")) {
            List<Integer> matingPool = matingSelection(subProblemId, 3, neighborType);
            parents = new ArrayList<>(3);
            parents.add(population.get(matingPool.get(0)));
            parents.add(population.get(matingPool.get(1)));
            parents.add(population.get(matingPool.get(2)));
        }else if (variant.equals("rand/2/bin") ){
            List<Integer> matingPool = matingSelection(subProblemId, 4, neighborType);
            parents = new ArrayList<>(4);
            parents.add(population.get(matingPool.get(0)));
            parents.add(population.get(matingPool.get(1)));
            parents.add(population.get(matingPool.get(2)));
            parents.add(population.get(matingPool.get(3)));
        } else if(variant.equals("current-to-rand/2/bin")) {
            List<Integer> matingPool = matingSelection(subProblemId, 5, neighborType);
            parents = new ArrayList<>(5);
            parents.add(population.get(matingPool.get(0)));
            parents.add(population.get(matingPool.get(1)));
            parents.add(population.get(matingPool.get(2)));
            parents.add(population.get(matingPool.get(3)));
            parents.add(population.get(matingPool.get(4)));
        } 
        return parents;
    }

	
3. ExperimentAlgorithm can show the execution time at the output

4. (suggestion) at GenerateLatexTablesWithStatistics.java
	Change the string format:
		"%10.2e"
		"%8.1e"
	to:
		"%10.5e"
      "%8.3e"
	It will show more numbers;

5. In MOEADDRA create the attribute "protected int draTime" for set step size of apply utilityFunction, and create its public setting;
	Its default value is 30;

6. (suggestion) After compile the project,
		I develop some bash script for automatize view of the results of statistical test
		https://github.com/LucasLP/ExecuteJMetal

**Comment by matthieu-vergne** [comment]
Please close this issue and make a different one for each. If you are able to provide code to fix, a pull request would be better.
