### ISSUE TITLE
How to use Algorithm MOEADD?

### ISSUE THREAD

**Issue by dylanzx** [jMetal/jMetal#229]
I have saw and learned how to use MOEAD, ConstraintMOEAD, MOEADDRA, MOEADSTM. But in the fold runner\multiobjective, I cant not see a runner.java according to MOEADD algorithm, can you give me any advice about it?

**Comment by matthieu-vergne** [comment]
@ajnebro ?

**Comment by ajnebro** [comment]
Hi @dylanzx.  The MOEADD implementation was a contribution of @vinixnan. 

I have never used it in my research work, so I didn't notice that the runner was missing. Taking a look to the class constructor it seems that a runner similar to the one of MOEA/D would work. 

Let me check that.

**Comment by dylanzx** [comment]
@vinixnan How to configure the parameters according to algorithm MOEADD? Hope you to give me some advise.

**Comment by fritsche** [comment]
For the other MOEAD variants, the MOEADBuilder is used.
The current version of MOEADBuilder does not support MOEADD.

To add this support one should include MOEADD in the enum:
```java
    public enum Variant {
        MOEAD, ConstraintMOEAD, MOEADDRA, MOEADSTM, MOEADD
    };
```

and include the MOEADD option in the `build` method:
```java
} else if (moeadVariant.equals(Variant.MOEADD)) {
            algorithm = new MOEADD(problem, populationSize, resultPopulationSize, maxEvaluations, crossover, mutation,
                    functionType, dataDirectory, neighborhoodSelectionProbability,
                    maximumNumberOfReplacedSolutions, neighborSize);
        }
```

**Comment by fritsche** [comment]
I have created a pull request #232 that includes MOEADD on the MOEADBuilder.

Meantime you can create your own MOEADDBuilder:

```java
public class MOEADDBuilder extends MOEADBuilder {

    public MOEADDBuilder(Problem<DoubleSolution> problem) {
        super(problem, null);
    }

    @Override
    public AbstractMOEAD<DoubleSolution> build() {
        AbstractMOEAD moeadd = new MOEADD(problem, populationSize, resultPopulationSize, maxEvaluations, crossover, mutation,
                functionType, dataDirectory, neighborhoodSelectionProbability,
                maximumNumberOfReplacedSolutions, neighborSize);
        return moeadd;
    }
}
```

**Comment by matthieu-vergne** [comment]
Thank you for your effort. {^_^}
Just wait for @ajnebro to look at it before integration (if he considers it to be OK).

**Comment by ajnebro** [comment]
I have made the changes but when running the algorithm I get a `java.lang.NullPointerException` when calling the `DifferentialEvolutionCrossover.execute()` method. 

Do you have a runner to configure the algorithm?

**Comment by ajnebro** [comment]
I have updated manually the involved classes and the runner seems to work ok. 

Thanks @fritsche for your contribution.

**Comment by dylanzx** [comment]
Thanks all of you.
