### ISSUE TITLE
How to set the target function

### ISSUE THREAD

**Issue by fsctz** [jMetal/jMetal#238]
I created a new  class named OFF to extends class(AbstractDoubleProblem). However, my design objective function is this：int-type decision variables and double-type function values. So I do not know how to set.Please give me some advice.{^_^}

**Comment by fsctz** [comment]
I use class(AbstractIntegerDoubleProblem) but it has not evaluate method...

**Comment by matthieu-vergne** [comment]
An `AbstractDoubleProblem` is supposed to take `DoubleSolution` as solutions. A `DoubleSolution` is a `Solution` which takes `Double` as *variables*. Objective functions are always considered as `double` values. So if your variables are integers, you should rather take an `IntegerSolution`, and thus extend an `IntegerProblem`.
