### ISSUE TITLE
How to set constraints

### ISSUE THREAD

**Issue by fsctz** [jMetal/jMetal#241]
I implements the ConstrainedProblem<IntegerSolution>, rewritten the evaluateConstraints(IntegerSolution solution).
However after running, the result is still not satisfied with the constraints.

code here:
                     // Times constraints
		    constraint[0] = 80/1000 - app1_ddl(con_app1_t12);	//Time
		    constraint[1] = 50/1000 - app2_ddl(con_app2_t12);
		    constraint[2] = 80/1000 - app3_ddl(con_app3_t12);
		    //System.out.println(" ...."+app1_ddl(con_app1_t12));
		    //System.out.println(" ...."+app2_ddl(con_app2_t12));
		    //System.out.println(" ...."+app3_ddl(con_app3_t12));
		    
		    double overallConstraintViolation = 0.0;
		    int violatedConstraints = 0;
		    for (int i = 0; i < getNumberOfConstraints(); i++) {
		      if (constraint[i]<0.0){
		        overallConstraintViolation+=constraint[i];
		        violatedConstraints++;
		      }
		    }
		    overallConstraintViolationDegree.setAttribute(solution, overallConstraintViolation);
		    numberOfViolatedConstraints.setAttribute(solution, violatedConstraints);

the results which subject to constrains are here:
Time：
0.0745
0.23950000000000002
0.10450000000000001
~~~~~~~~~~~
Energy：
1.44E-4
0.14410699999999999
0.032128000000000004


 However ,times here are not subject to constraints. ^-^

**Comment by ajnebro** [comment]
When you are dealing with a constrained problem there is no guarantee that an evolutionary algorithm returns feasible solutions. 

The benchmark problems included in jMetal are easy to solve, but in my experience with a heavily constrained problem and NSGA-II, the algorithm needed thousands of evaluations until finding a feasible solution.

**Comment by fsctz** [comment]
Thanks ! ^_^
What you mean is: a small amount of running results do not always get the solution I want（that subject to the constraint）, I need to run the program several times until I find the right solution?

**Comment by ajnebro** [comment]
The matter dependes on the problem, the algorithm and how this is configured. Think that when a metaheuristic compares two solutions to determine which is better, the overall constraint violation degree of them is compared first and the one having the lowest value is selected, and the dominance relationship is not taken into account.

Have you formulated the constraints in as unequalities of type  0 <  V?

**Comment by fsctz** [comment]
I do not understand:  "0 < V"  ? 
my code:  
                    constraint[0] = 80/1000 - app1_ddl(con_app1_t12);	//Time
		    constraint[1] = 50/1000 - app2_ddl(con_app2_t12);
		    constraint[2] = 80/1000 - app3_ddl(con_app3_t12);
		
		    double overallConstraintViolation = 0.0;
		    int violatedConstraints = 0;
		    for (int i = 0; i < getNumberOfConstraints(); i++) {
		      if (constraint[i]<0.0){
		        overallConstraintViolation+=constraint[i];
		        violatedConstraints++;
		      }
		    }
I set three constraints here, that means: they must less than the given value(0.08,0.05,0.08)
Other parts I follow Water.class

Water.class code:
  public void evaluateConstraints(DoubleSolution solution)  {
    double[] constraint = new double[getNumberOfConstraints()];
    double[] x = new double[solution.getNumberOfVariables()];
    for (int i = 0; i < solution.getNumberOfVariables(); i++) {
      x[i] = solution.getVariableValue(i) ;
    }

    constraint[0] = 1 - (0.00139/(x[0]*x[1])+4.94*x[2]-0.08)             ;
    constraint[1] = 1 - (0.000306/(x[0]*x[1])+1.082*x[2]-0.0986)         ;
    constraint[2] = 50000 - (12.307/(x[0]*x[1]) + 49408.24*x[2]+4051.02) ;
    constraint[3] = 16000 - (2.098/(x[0]*x[1])+8046.33*x[2]-696.71)      ;
    constraint[4] = 10000 - (2.138/(x[0]*x[1])+7883.39*x[2]-705.04)      ;
    constraint[5] = 2000 - (0.417*x[0]*x[1] + 1721.26*x[2]-136.54)       ;
    constraint[6] = 550 - (0.164/(x[0]*x[1])+631.13*x[2]-54.48) ;

    double overallConstraintViolation = 0.0;
    int violatedConstraints = 0;
    for (int i = 0; i < getNumberOfConstraints(); i++) {
      if (constraint[i]<0.0){
        overallConstraintViolation+=constraint[i];
        violatedConstraints++;
      }
    }

    overallConstraintViolationDegree.setAttribute(solution, overallConstraintViolation);
    numberOfViolatedConstraints.setAttribute(solution, violatedConstraints);
  }

**Comment by ajnebro** [comment]
If you take into account how the overall constraint violation is computed:

```java
for (int i = 0; i < getNumberOfConstraints(); i++) {
  if (constraint[i]<0.0){
    overallConstraintViolation+=constraint[i];
    violatedConstraints++;
  }
}
```

every constraint must be expressed as an unequality of type "expression >=0.0". This way, when "expression < 0.0" then it is considered as a constraint violation.

**Comment by fsctz** [comment]
Thank you !
I found this point("expression >=0.0") yesterday and have solved this problem.
