### ISSUE TITLE
Accessing each generation (population).

### ISSUE THREAD

**Issue by vsantjr** [jMetal/jMetal#245]
Hello,

I am investigating jMetal with the classical NSGAII algorithm and the classical ZDT1 problem (30 decision variables,  2 objectives). The Builder is with the standard parameters: MaxEvaluations = 25000, PopulationSize = 100. 

My question is how to access each generation by running NSGAII. In other words, I need to access not only the "final" Pareto Optimal Set (VAR file), but all intermediate Pareto Sets after each generation. 

I am not sure about this, but I assume that if the final non-dominated (final) solution set is equal, in size, to the initial population, thus 25000/100 = 250 generations (updates of population) will be created by running this algorithm with this configuration. Is this right?

Thank you.

**Comment by vinixnan** [comment]
I think this is a good idea, make possible to acess the main population after each generation.That means, all run() method should be:

`run(){
   while(stopping criteria is not reach){
       executeGeneration();
}`

I use this kind of stuff in my research, so if necessary, I can implement it.

**Comment by ajnebro** [comment]
You can get the population at the end of each iteration by using the implementation of NSGA-II included in the [NSGAIIMeasures](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/nsgaii/NSGAIIMeasures.java) class. 

An example of using that class is contained in the [NSGAIIRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/NSGAIIMeasuresRunner.java) class. You only need to modify the `Listener` class to do whatever you need with the population (see lines 129 - 138). This example assumes that the Hypervolume is also calculated every iteration; if that not your case, just modify the code to remove the sentences related to manipulate it.

**Comment by vinixnan** [comment]
This happens in all jMetal algorithms?

**Comment by ajnebro** [comment]
Only some of them (SMPSO, DMOPSO), but the approach taken in class `NSGAIIMeasures` can be adopted in the algorithms you need.

**Comment by vsantjr** [comment]
Thanks ajnebro. I ran the NSGAIIMeasuresRunner (within Eclipse) but an exception is raised as shown below:

PUSH MEASURE. Iteration: 100
PUSH MEASURE. Iteration: 200
PUSH MEASURE. Counter = 0 First solution: Variables: 0.6141385701006934 0.7313458763008676 0.9105640192762099 0.06152614240949428 0.9524481028282303 0.551784360097826 0.025302150591088646 0.4916920216420959 0.24961783259632597 0.21875197761872955 0.3031353349354986 0.9450731881786062 0.6634656863892543 0.5474439344968571 0.27591335074562684 0.23399695221708128 0.8083515114637783 0.9259120827884464 0.4489375263777333 0.02636019352001695 0.17101066276062016 0.4491681499644734 0.12351198183667778 0.8826090814999007 0.09865042817568559 0.13355282609078778 0.1283820195985449 0.4763323481001269 0.11776256257031203 0.4895998777951033 Objectives: 0.6141385701006934 3.133496730212861 	AlgorithmAttributes: {class org.uma.jmetal.util.solutionattribute.impl.DominanceRanking=0, class org.uma.jmetal.util.solutionattribute.impl.CrowdingDistance=0.8800705440462708}

Exception in thread "Thread-0" org.uma.jmetal.util.JMetalException: The index value (0) is greater than the number of points (0)
	at org.uma.jmetal.util.front.imp.ArrayFront.getPoint(ArrayFront.java:163)
	at org.uma.jmetal.qualityindicator.impl.hypervolume.PISAHypervolume.hypervolume(PISAHypervolume.java:214)
	at org.uma.jmetal.qualityindicator.impl.hypervolume.PISAHypervolume.evaluate(PISAHypervolume.java:72)
	at org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAIIMeasures.updateProgress(NSGAIIMeasures.java:63)
	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:63)
	at org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAIIMeasures.run(NSGAIIMeasures.java:76)
	at java.lang.Thread.run(Thread.java:745)


Evaluations (0)                     : 200
Computing time (0)                  : 5006
Number of Nondominated solutions (0): 11
Evaluations (1)                     : 200
Computing time (1)                  : 10011
Number of Nondominated solutions (1): 11
Evaluations (2)                     : 200
Computing time (2)                  : 15016
Number of Nondominated solutions (2): 11
Evaluations (3)                     : 200
Computing time (3)                  : 20021
Number of Nondominated solutions (3): 11
...

Here, the program continues presenting the Evaluations (..) results, even after removing the 5 second delay in the while loop (TimeUnit.SECONDS.sleep(5);). 

Any hints?

**Comment by vsantjr** [comment]
Only to remark that the NSGAIIMeasuresWithChartsRunner seems to work for me. But, I had to copy the reference pareto front (ZD1.pf) to a folder within my Eclipse project to work. With the default location (jmetal-problem/src/test/resources/pareto_fronts/ZDT1.pf) the file is not found (exception raised).
