### ISSUE TITLE
MOMBI2 variable maxs it is not initialized with values

### ISSUE THREAD

**Issue by fritsche** [jMetal/jMetal#247]
https://github.com/jMetal/jMetal/blob/6bedf58834cf563c6e1f197ab5622bfa713eaaf1/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/mombi/MOMBI2.java#L75

https://github.com/jMetal/jMetal/blob/6bedf58834cf563c6e1f197ab5622bfa713eaaf1/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/mombi/MOMBI2.java#L76

**Comment by Juanjdurillo** [comment]
Hi,

they seem to be initialized a bit later the instantiation of the list, at
the function updatemax

https://github.com/jMetal/jMetal/blob/6bedf58834cf563c6e1f197ab5622bfa713eaaf1/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/mombi/MOMBI2.java#L55












which is called in the initProgress of the algorithm. Is this correct or
are these max values used somewhere before?


2018-02-26 7:25 GMT+01:00 Gian Mauricio Fritsche <notifications@github.com>:

**Comment by fritsche** [comment]
It was my mistake, I did an inheritance from MOMBI2 that do not use the progress, so I removed the call for `initProgress()` and `updateProgress()`.
Probably this line (L70) should be moved to somewhere else as it does not relate to progress initialization.

Thank you!

**Comment by Juanjdurillo** [comment]
Yes, I agree that it should be moved somewhere else to avoid hiding the
problem in cases like the one you are mentioning

2018-02-26 13:57 GMT+01:00 Gian Mauricio Fritsche <notifications@github.com>
:
