### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by muwednesday** [jMetal/jMetal#251]
Hey, I have used MOEA/D to solve some real world problems which I do not know their PF. I need the max and min objective to normalize the real objective, do you have some idea?
For example, when I multiply by 100 to ZDT1's second objective, the result is bad.
ZDT1
![1](https://user-images.githubusercontent.com/34086410/37502647-ecd7877e-290e-11e8-8072-585b1936b0a8.jpg)
modified ZDT1
![2](https://user-images.githubusercontent.com/34086410/37502649-ed08898c-290e-11e8-9dd5-2dfbd04d7f9b.jpg)

**Comment by matthieu-vergne** [comment]
The reference pareto front is usually empirical. You can build it through several runs, until you get something prone to not improve more.

Regarding the min/max objectives, they should depend on your problem. So only you should know what they are.

@ajnebro may provide some more detailed explanations or hints, if he has.

**Comment by ajnebro** [comment]
As far as I know, MOEA/D only needs to update the ideal point in every iteration, which is estimated by taking the lowest values of all the objectives. 

I have used it to solve real-world problems and I haven't had the need of finding the maximum and minimum values of the objective functions.

**Comment by vsantjr** [comment]
Hello,
I take this issue to ask how jMetal precisely builds the reference Pareto Front (ref PF) when it is not known. In the experiment/ZDTStudy2, what I understood is that it concatenates (add to the end) all partial contributions. In other words, in this experiment we have (ZDT1 problem):

ZDT1.rf (the "final" ref PF) = ZDT1.NSGAIIa.rf + ZDT1.NSGAIIb.rf + ZDT1.NSGAIIc.rf + ZDT1.NSGAIId.rf

where "+" means concatenation, and a,b,c,d means different probabilities, distribution indexes, ... And this ref PF (ZDT1.rf) is then used for calculating the quality indicators (GD, Error Ratio, ...).

Is that right? 

Thanks again.

**Comment by vsantjr** [comment]
Sorry. The experiment is indeed experiment/NSGAIIStudy2.

Thanks.

**Comment by ajnebro** [comment]
To get a reference Pareto front in an experiment, the strategy is to combine all the solutions obtained by all the runs of all the algorithms for a given problem, keeping only the non-dominated solutions.

**Comment by vsantjr** [comment]
Ok. Thank you.
