### ISSUE TITLE
Crossover and Mutation parameters

### ISSUE THREAD

**Issue by pwangsom** [jMetal/jMetal#256]
In NSGAIIIRunner code which uses SBX crossover and Polynomial Mutation,

I see four parameters including
Crossover probability,
Crossover distribution index,
Mutation probability,
Mutation distribution index.

I am not sure about their possible values and their representations.

Where can I find more details about them?

Thank you

**Comment by Juanjdurillo** [comment]
The best source of information is this book:
https://dl.acm.org/citation.cfm?id=559152

2018-03-26 5:57 GMT+02:00 Peerasak Wangsom <notifications@github.com>:

**Comment by pwangsom** [comment]
@Juanjdurillo Thank you for your reply and I am sorry that I left my question too short.

The things that I would like to clarify are how does jMetal use these parameters.

For my understanding, crossover probability is the number of parent solutions will be selected for crossover operation. But I am not sure that it is the possible values of it in jMetal. I guess its value is range from 0.0 to 1.0. 

For example, in an algorithm with 100 solutions, if crossover probability was 0.9, it means 90 parents or 45 pairs of solutions will be selected for doing the crossover and as a result, we will get 90 offsprings.

Also, mutation probability is the number of parents will be chosen for mutation operation. Again, its value is range from 0.0 to 1.0.

If mutation probability was 0.9, it is 90 parents will be mutated and we will get 90 offsprings.

Please clarify my understanding and correct me if I am wrong.

**Comment by Juanjdurillo** [comment]
yes, probabilities  are between 0.0 and 1.0

crossover 0.9 means that out of all the parents selected to generate
offsprings crossover is applied to 90% of them generating solutions merging
features of the parents, and in 10% identical copies of the parents are
generated.
Going to your example 90 offsprings comes from the crossover operator, 10
offsprings are copies of the parents.
Nevertheless, the best way of understanding this is looking at the
available source code.

2018-03-26 8:32 GMT+02:00 Peerasak Wangsom <notifications@github.com>:

**Comment by matthieu-vergne** [comment]
IMHO, one should not need to look at the code to understand the meaning of
the parameters one must provide. These details should be in the
documentation of the method/constructor requiring the parameters.

I did not check whether such documentation exists, but a good answer to
this kind of question should always be "read the doc". If we cannot say so,
there is surely something to do on our side.
