### ISSUE TITLE
Quality Indicators: synonyms

### ISSUE THREAD

**Issue by vsantjr** [jMetal/jMetal#257]
Hello,

Just to be sure, are these quality indicators provided by jMetal synonyms of other terms found in the literature?

Spread/Gspread (jMetal) = Uniform distribution of a non-dominated population (UD). Ref: Srinivas & Deb, 1994

Error Ratio (jMetal) = Ratio of non-dominated individuals (RNI). Ref: Tan et al., 2002

Thanks.

**Comment by vinixnan** [comment]
@vsantjr 

These metrics are not synonyms

See
Consistencies and contradictions of performance metrics in multiobjective optimization, Jiang et al 2014, IEEE Trans. on Evolutionary

Performance Metrics Ensemble for Multiobjective Evolutionary Algorithms, Yen and He, 2013, IEEE Trans. on Evolutionary

**Comment by vsantjr** [comment]
Thanks vinixnan.
