### ISSUE TITLE
State is kept between independent runs when running experiments

### ISSUE THREAD

**Issue by duvholt** [jMetal/jMetal#259]
The easiest way I found to reproduce this issue is by running ZDTStudy using SMPSO with 10 iterations.
10 independent runs should produce more or less the same indicator values, but a clear progress can be seen after each run. 

This is the content of `SMPSO/ZDT1/IGD` after 10 runs with 10 iterations for each run. 
```
0.03514951801112995
0.02093955244035617
0.016669572631993073
0.012158586373266856
0.006522263502570968
0.004837404445364619
0.003136340249826026
0.001059361410142327
5.570689442089307E-4
2.825933656691139E-4
```

After digging a bit, I discovered that the archive is not cleared between runs. 
By adding the following code to SMPSO.java the algorithm behaves more as expected:
```java  
  @Override
  public void run () {
    leaders.getSolutionList().clear();
    super.run();
  }
```

After running with the modification:
```
0.03641453453957802
0.0394776584262001
0.04696311781426386
0.06131756914270818
0.03358119326557638
0.04632175749061348
0.03868865126639302
0.04430461917631434
0.04061804736865977
0.03885412081541176
```

This seems to affect several algorithms and from what I can gather the problem is that the algorithm instance is reused between runs and the `run` method does not reset the state properly for all algorithms. 

Manually clearing archives and other state seem to mitigate the problem but do not provide any guarantee that all the state in the algorithm is cleared.

Known algorithms that this affects: ABySS, SPEA2, SMPSO, PAES, MOCell.

**Comment by ajnebro** [comment]
Thanks for your comment. I'm already working on this issue because I noticed similar behaviors in some experiments. The reason is that the algorithm instance is the same in all the runs; I have to modify the experiments to create a new instance each time.

**Comment by duvholt** [comment]
@ajnebro I just noticed that you pushed a fix in https://github.com/jMetal/jMetal/commit/f4529c16fd8cd522bf55cace1e81c1a63f9246bc.
Does this fix my problem?

**Comment by ajnebro** [comment]
It should be.  Please, if you try it, tell me whether it is working properly or not.

**Comment by duvholt** [comment]
Thank you so much for the quick bug fix!

I'll run my experiment and report back!

**Comment by duvholt** [comment]
The problem described in this issue seems to be fixed now, but I'm experiencing another problem which did not appear with the old code. 
I'll open a new issue and close this.
