### ISSUE TITLE
Out of memory when running larger experiments

### ISSUE THREAD

**Issue by duvholt** [jMetal/jMetal#260]
This issue started after #259 was fixed. 

I'm not entirely sure why it happens, but I hypothesize that each Algorithm instance uses a certain amount of memory and when running for example 30 independent runs with several algorithms the memory usage is too much. 

It might just be one algorithm that is misbehaving, but my experience was that running eight algorithms on DTLZ with 30 independent ran out of memory several times. After increasing Java's max memory to 14GB, the experiment got slower by each completed run, and the memory usage steadily grew to the 14GB limit. 

My understanding of the study code is somewhat limited, but maybe removing completed algorithm instances from the algorithm list will mitigate this problem? Is it safe to do so before the experiment has fully completed?

**Comment by duvholt** [comment]
It seems SMPSO especially has problems with memory usage.

**Comment by ajnebro** [comment]
Could you try an experiment without SMPSO to see if the memory problem is due to that algorithm?

**Comment by duvholt** [comment]
I ran an experiment with AbYSS, MOCell, MOEA/DD, NSGAIII, NSGAII, PAES, and SPEA2 on DTLZ1-7 with 30 independent runs and it works fine. 
With SMPSO I was not able to complete the experiment.

**Comment by ajnebro** [comment]
So the problem is SMPSO instead of having a large list of algorithms. I will profile SMPSO to see what is happening.

Thanks

**Comment by matthieu-vergne** [comment]
It makes me think I should continue the new experiment framework.
Didn't have much free time since September. I hope you can find a fix for
this one.
