### ISSUE TITLE
How to configure GDE3 algorithm

### ISSUE THREAD

**Issue by fsctz** [jMetal/jMetal#273]
I want to use GDE3 algorithm to test my multi-objective function, but there are some parameters in the configuration I do not know how to set, please give me some suggestions on parameters.

This is my code snippet：

 problem = new OFF();          	        
	        selection = new DifferentialEvolutionSelection();  
	       
	        double cr = 0.5;  
	        double f = 0.4;  
	        crossover = new DifferentialEvolutionCrossover(cr, f,"how to set？？？");          

	        evaluator = new SequentialSolutionListEvaluator<DoubleSolution>(); 
	       
	        algorithm = new GDE3(problem, 100, 1000000, selection, crossover, evaluator);

**Comment by ajnebro** [comment]
Hi.
  There are many variants of GDE, and you can use the `DifferentialEvolutionCrossover` class to indicate which version do you intend to use. "rand/1/bin" is the most commoly used variant, but you can choose others (e.g, "best/1/bin", "rand/1/exp", etc.) You can see the included alternatives in the implementation ofthat class: https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/operator/impl/crossover/DifferentialEvolutionCrossover.java
