### ISSUE TITLE
NSGAIII Experiment with PermutationSolution<Integer>

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [jMetal/jMetal#276]
Hi, 
I try to solve a many objective o.  problem with NSGAIII. I want to make an experiment on Mutationrate but I get an error that I could not figure out. Could you help please.  Here is the Error : 

 

> /NSGAIIIWithPermSwapMutationProb04/DietProblem/FUN0.tsv [org.uma.jmetal.util.experiment.util.ExperimentAlgorithm runAlgorithm]
> Exception in thread "main" java.lang.NullPointerException
> 	at org.uma.jmetal.algorithm.multiobjective.nsgaiii.NSGAIII.selection(NSGAIII.java:88)
> 	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:59)
> 	at org.uma.jmetal.util.experiment.util.ExperimentAlgorithm.runAlgorithm(ExperimentAlgorithm.java:67)
> 	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.lambda$run$0(ExecuteAlgorithms.java:42)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
> 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
> 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:747)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
> 	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:395)
> 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:725)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
> 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:594)
> 	at org.uma.jmetal.util.experiment.component.ExecuteAlgorithms.run(ExecuteAlgorithms.java:42)
> 	at org.uma.jmetal.experiment.NSGAIIIExperimentMutationRate.main(NSGAIIIExperimentMutationRate.java:85)

and This is how i Create my experiment
````
Experiment<PermutationSolution<Integer>, List<PermutationSolution<Integer>>> experiment =
        new ExperimentBuilder<PermutationSolution<Integer>, List<PermutationSolution<Integer>>>("NSGAIIIExperimentMutationRate")
            .setAlgorithmList(algorithmList)
            .setProblemList(problemList)
            .setExperimentBaseDirectory(experimentBaseDirectory)
            .setOutputParetoFrontFileName("FUN")
            .setOutputParetoSetFileName("VAR")
            .setReferenceFrontDirectory(experimentBaseDirectory+"/referenceFronts")
            .setIndicatorList(Arrays.asList(
                new Epsilon<PermutationSolution<Integer>>(), new Spread<PermutationSolution<Integer>>(), new GenerationalDistance<PermutationSolution<Integer>>(),
                new PISAHypervolume<PermutationSolution<Integer>>(),
                new InvertedGenerationalDistance<PermutationSolution<Integer>>(), new InvertedGenerationalDistancePlus<PermutationSolution<Integer>>()))
            .setIndependentRuns(INDEPENDENT_RUNS)
            .setNumberOfCores(8)
            .build();

    new ExecuteAlgorithms<>(experiment).run();
    new GenerateReferenceParetoFront(experiment).run();
    new ComputeQualityIndicators<>(experiment).run() ;
    new GenerateLatexTablesWithStatistics(experiment).run() ;
    new GenerateWilcoxonTestTablesWithR<>(experiment).run() ;
    new GenerateFriedmanTestTables<>(experiment).run();
    new GenerateBoxplotsWithR<>(experiment).setRows(3).setColumns(3).run() ;
  }

  static List<ExperimentAlgorithm<PermutationSolution<Integer>, List<PermutationSolution<Integer>>>> configureAlgorithmList(
          List<ExperimentProblem<PermutationSolution<Integer>>> problemList) {
    List<ExperimentAlgorithm<PermutationSolution<Integer>, List<PermutationSolution<Integer>>>> algorithms = new ArrayList<>();
    Algorithm<List<PermutationSolution<Integer>>> algorithm = new NSGAIIIBuilder<PermutationSolution<Integer>>(
            problemList.get(0).getProblem())
            .setCrossoverOperator(new PMXCrossover(0.9))
            .setMutationOperator(new PermutationSwapMutation(0.4))
            .setMaxIterations(2500)
            .setPopulationSize(100)
            .build();
    algorithms.add(new ExperimentAlgorithm<>(algorithm,
            "NSGAIIIWithSwapMutationProbability04",
            problemList.get(0).getTag()));
```

**Comment by ajnebro** [comment]
Hi. Have you tried first to use the `NSGAIIIRunner` class, previously adapted to your problem, to see whether it works?

**Comment by CumaliTurkmenoglu** [comment]
Hi, NSGAIIIRunner works fine but when I try to use NSGAIII for experiments it stucks as in error log.

**Comment by CumaliTurkmenoglu** [comment]
I found out the missing part. A Selection operator.

  SelectionOperator<List<PermutationSolution<Integer>>, PermutationSolution<Integer>> selection;
      selection = new BinaryTournamentSelection<PermutationSolution<Integer>>();


    Algorithm<List<PermutationSolution<Integer>>> algorithm = new NSGAIIIBuilder<PermutationSolution<Integer>>(
            problemList.get(0).getProblem())
            .setCrossoverOperator(new PMXCrossover(0.9))
            .setMutationOperator(new PermutationSwapMutation(0.4))
            .setMaxIterations(25)
            .setPopulationSize(100)
            .setSelectionOperator(selection)
            .build();

Thanks

**Comment by ajnebro** [comment]
:)

**Comment by matthieu-vergne** [comment]
Please close the issue if your problem is solved.
