### ISSUE TITLE
Problem building the project (IntelliJ IDEA)

### ISSUE THREAD

**Issue by deepak311086** [jMetal/jMetal#278]
I have downloaded .ZIP from the jMetal 5 website. I am trying to build the project in IntelliJ IDEA. Following are the errors. Please guide me through it. 

Information:java: Errors occurred while compiling module 'jmetal-core'
Information:javac 1.8.0_171 was used to compile java sources
Information:8/7/18 12:54 PM - Compilation completed with 85 errors and 0 warnings in 5 s 402 ms
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/operator/impl/crossover/NPointCrossover.java
Error:(3, 32) java: package org.apache.commons.lang3 does not exist
Error:(74, 11) java: cannot find symbol
  symbol:   variable ArrayUtils
  location: class org.uma.jmetal.operator.impl.crossover.NPointCrossover<T>
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/component/GenerateWilcoxonTestTablesWithR.java
Error:(3, 32) java: package org.apache.commons.lang3 does not exist
Error:(265, 32) java: cannot find symbol
  symbol:   variable StringUtils
  location: class org.uma.jmetal.util.experiment.component.GenerateWilcoxonTestTablesWithR<Result>
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/chartcontainer/ChartContainer.java
Error:(13, 24) java: package org.knowm.xchart does not exist
Error:(14, 38) java: package org.knowm.xchart.BitmapEncoder does not exist
Error:(15, 24) java: package org.knowm.xchart does not exist
Error:(16, 24) java: package org.knowm.xchart does not exist
Error:(17, 24) java: package org.knowm.xchart does not exist
Error:(18, 24) java: package org.knowm.xchart does not exist
Error:(19, 33) java: package org.knowm.xchart.XYSeries does not exist
Error:(31, 25) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(32, 13) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(33, 13) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(34, 13) java: cannot find symbol
  symbol:   class SwingWrapper
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(34, 26) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(225, 44) java: cannot find symbol
  symbol:   class BitmapFormat
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(249, 12) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(253, 12) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(257, 12) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(51, 49) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(63, 31) java: cannot find symbol
  symbol:   class XYChartBuilder
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(65, 65) java: cannot find symbol
  symbol:   variable XYSeriesRenderStyle
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(73, 9) java: cannot find symbol
  symbol:   class XYSeries
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(82, 9) java: cannot find symbol
  symbol:   class XYSeries
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(91, 29) java: cannot find symbol
  symbol:   class XYChartBuilder
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(93, 63) java: cannot find symbol
  symbol:   variable XYSeriesRenderStyle
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(98, 9) java: cannot find symbol
  symbol:   class XYSeries
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(105, 23) java: cannot find symbol
  symbol:   class SwingWrapper
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(105, 36) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(105, 59) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(142, 9) java: cannot find symbol
  symbol:   class XYChart
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(142, 38) java: cannot find symbol
  symbol:   class XYChartBuilder
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(143, 64) java: cannot find symbol
  symbol:   variable XYSeriesRenderStyle
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(150, 9) java: cannot find symbol
  symbol:   class XYSeries
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(189, 9) java: cannot find symbol
  symbol:   class XYSeries
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
Error:(227, 13) java: cannot find symbol
  symbol:   variable BitmapEncoder
  location: class org.uma.jmetal.util.chartcontainer.ChartContainer
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/component/ComputeQualityIndicators.java
Error:(3, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(4, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(150, 16) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.ComputeQualityIndicators<S,Result>
Error:(154, 13) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.ComputeQualityIndicators<S,Result>
Error:(154, 46) java: cannot find symbol
  symbol:   class ImmutablePair
  location: class org.uma.jmetal.util.experiment.component.ComputeQualityIndicators<S,Result>
Error:(158, 49) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.ComputeQualityIndicators<S,Result>
Error:(160, 32) java: cannot find symbol
  symbol: class Pair
Error:(160, 61) java: cannot find symbol
  symbol: class Pair
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/SetCoverage.java
Error:(3, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(4, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(22, 33) java: cannot find symbol
  symbol: class Pair
Error:(22, 97) java: cannot find symbol
  symbol: class Pair
Error:(33, 7) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.qualityindicator.impl.SetCoverage
Error:(32, 10) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.qualityindicator.impl.SetCoverage
Error:(43, 16) java: cannot find symbol
  symbol:   class ImmutablePair
  location: class org.uma.jmetal.qualityindicator.impl.SetCoverage
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/component/GenerateFriedmanTestTables.java
Error:(3, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(4, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(5, 38) java: package org.apache.commons.lang3.tuple does not exist
Error:(131, 15) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(131, 66) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(134, 31) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(136, 30) java: cannot find symbol
  symbol:   class ImmutablePair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(138, 53) java: cannot find symbol
  symbol:   class Pair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(140, 28) java: cannot find symbol
  symbol: class Pair
Error:(140, 57) java: cannot find symbol
  symbol: class Pair
Error:(154, 15) java: cannot find symbol
  symbol:   class MutablePair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(154, 71) java: cannot find symbol
  symbol:   class MutablePair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(158, 30) java: cannot find symbol
  symbol:   class MutablePair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
Error:(168, 29) java: cannot find symbol
  symbol:   class MutablePair
  location: class org.uma.jmetal.util.experiment.component.GenerateFriedmanTestTables<Result>
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/pseudorandom/impl/MersenneTwisterGenerator.java
Error:(3, 39) java: package org.apache.commons.math3.random does not exist
Error:(11, 11) java: cannot find symbol
  symbol:   class MersenneTwister
  location: class org.uma.jmetal.util.pseudorandom.impl.MersenneTwisterGenerator
Error:(23, 15) java: cannot find symbol
  symbol:   class MersenneTwister
  location: class org.uma.jmetal.util.pseudorandom.impl.MersenneTwisterGenerator
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/pseudorandom/impl/Well44497bGenerator.java
Error:(3, 39) java: package org.apache.commons.math3.random does not exist
Error:(11, 11) java: cannot find symbol
  symbol:   class Well44497b
  location: class org.uma.jmetal.util.pseudorandom.impl.Well44497bGenerator
Error:(23, 15) java: cannot find symbol
  symbol:   class Well44497b
  location: class org.uma.jmetal.util.pseudorandom.impl.Well44497bGenerator
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/component/GenerateLatexTablesWithStatistics.java
Error:(3, 32) java: package org.apache.commons.lang3 does not exist
Error:(4, 49) java: package org.apache.commons.math3.stat.descriptive does not exist
Error:(159, 5) java: cannot find symbol
  symbol:   class DescriptiveStatistics
  location: class org.uma.jmetal.util.experiment.component.GenerateLatexTablesWithStatistics
Error:(159, 39) java: cannot find symbol
  symbol:   class DescriptiveStatistics
  location: class org.uma.jmetal.util.experiment.component.GenerateLatexTablesWithStatistics
Error:(209, 14) java: cannot find symbol
  symbol:   variable StringUtils
  location: class org.uma.jmetal.util.experiment.component.GenerateLatexTablesWithStatistics
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/JMetalLogger.java
Error:(3, 29) java: package org.apache.commons.io does not exist
Error:(4, 29) java: package org.apache.commons.io does not exist
Error:(77, 41) java: cannot find symbol
  symbol:   variable FileUtils
  location: class org.uma.jmetal.util.JMetalLogger
Error:(79, 41) java: cannot find symbol
  symbol:   variable FileUtils
  location: class org.uma.jmetal.util.JMetalLogger
Error:(87, 43) java: cannot find symbol
  symbol:   variable IOUtils
  location: class org.uma.jmetal.util.JMetalLogger
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/neighborhood/impl/WeightVectorNeighborhood.java
Error:(3, 44) java: package org.apache.commons.math3.ml.distance does not exist
Error:(88, 17) java: cannot find symbol
  symbol:   class EuclideanDistance
  location: class org.uma.jmetal.util.neighborhood.impl.WeightVectorNeighborhood<S>
Error:(88, 59) java: cannot find symbol
  symbol:   class EuclideanDistance
  location: class org.uma.jmetal.util.neighborhood.impl.WeightVectorNeighborhood<S>
/home/deepak/Downloads/jMetal-master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/util/ExperimentAlgorithm.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

**Comment by matthieu-vergne** [comment]
You are apparently trying to build it "standalone". It won't work because it builds on external libs that are not packaged with the zip (because they are not in our repo). Just search for the "package" keyword in this list, you will find plenty of those libs that you need, like:
- org.apache.commons.lang3
- org.apache.commons.math3
- org.knowm.xchart
- etc.

I am not familiar with IntelliJ, but probably you are trying to build it in an incomplete way. Either you should use Maven (maybe there is something in IntelliJ for that) to get everything automatically and compile, or you should go the long way and get the dependencies manually, setup your project correctly, and compile with the right commands.
