### ISSUE TITLE
Weight Vector Generation: set the number of vectors

### ISSUE THREAD

**Issue by fritsche** [jMetal/jMetal#279]
There is a way of generating a predefined number of weight vectors uniformly distributed?

For example, I would like to generate 128 vectors to a 5 objective problem.

Using Das and Dennis’s Method I cannot decide the number of points.

**Comment by matthieu-vergne** [comment]
I am not sure to understand the question. Maybe @ajnebro ?

**Comment by ajnebro** [comment]
We use the weight vector generation provided here: http://computacion.cs.cinvestav.mx/~rhernandez/mombi/index.html

**Comment by vsantjr** [comment]
Hello, 
1.) Regarding this point, what is the meaning of the notation of the weight vectors files? For instance:
weight_02D_152 -> That is: 2 objectives and we have 152 vectors. And that is ok in the jMetal distribution I am using.

But weight_03D_14 -> That is: 3 objectives and I expect 14 vectors but we have 120 in jMetal (the distribution I am using).

2.) If I have a 2D problem (ZDT1, DTLZ1.2D), does the number of vectors play a significant role? I mean do we expect a great difference in MOMBI (for instance) performance if I use as input weight_02D_152  (152 vectors) or weight_02D_200 (200 vectors)?


Thanks

**Comment by ajnebro** [comment]
I have never used MOMBI in my research, so I'm affraid that I cannot help you to answer both questions. About the first one, I see that the 2D weight vector files follow the rule of #objectives_#vectors, but I don't know the reason why the 3D ones do not.
