### ISSUE TITLE
do I need to specifically formulate the use of pareto sorting when I use DE Algorithm

### ISSUE THREAD

**Issue by suixinzhenguai** [jMetal/jMetal#281]
When I set the parameters of the Differential Evolution Algorithm, do I need to specifically formulate the use of pareto sorting?

code here:
       
	       ```
DifferentialEvolutionSelection selection = new DifferentialEvolutionSelection(); 
	        
	         double cr = 0.2;  
	        double f = 0.5; 
	        DifferentialEvolutionCrossover crossover = new DifferentialEvolutionCrossover(cr, f,"rand/1/bin");
           
	       SolutionListEvaluator<DoubleSolution> evaluator = new SequentialSolutionListEvaluator<DoubleSolution>();
	        
	        Algorithm<List<DoubleSolution>> algorithm = new GDE3(problem, 250, 2500000, selection, crossover, evaluator); 

        	AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm).execute();
```

**Comment by matthieu-vergne** [comment]
I don't understand the question.

**Comment by suixinzhenguai** [comment]
How can I specify that use " pareto sorting" in the parameter configuration of the GDE3 algorithm?

**Comment by matthieu-vergne** [comment]
@ajnebro will correct me, but if I understand well:
- pareto comparisons are implemented in jMetal through the [DominanceComparator](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/comparator/DominanceComparator.java), with an additional priority to the ones which violate the least constraints.
- GDE3 [uses it](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/gde3/GDE3.java#L47)

So although you cannot ask it explicitly to do so, it already does.

Or did I misunderstood something?

Meanwhile, if you want to change that, you can:
- create your own class which extends GDE3
- in your constructor, set your own `dominanceComparator` (protected parameter)

So you cannot set it as a parameter of the original GDE3, but you can change it easily by extending the class.

**Comment by suixinzhenguai** [comment]
But in my experiments, some individuals in the previous generation that were significantly better and did not violate the constraints were not appear in the next generation of populations. It is even true that all individuals in the next generation of populations violated the constraint, while some of the previous generation of populations did not violate the constraints.
If GDE3 uses "pareto", then individuals in the previous generation that are significantly better and do not violate the constraint should appear in the next generation of population.
So I doubt that my parameter settings are missing something.

My code is here:

```
double cr = 0.2;  
double f = 0.5; 
DifferentialEvolutionCrossover crossover = new DifferentialEvolutionCrossover(cr, f,"rand/1/bin");
DifferentialEvolutionSelection selection = new DifferentialEvolutionSelection();  
SolutionListEvaluator<DoubleSolution> evaluator = new SequentialSolutionListEvaluator<DoubleSolution>();      
Algorithm<List<DoubleSolution>> algorithm = new GDE3(problem, 250, 2500000, selection, crossover, evaluator); 
AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm).execute();
```

**Comment by ajnebro** [comment]
GDE3 applies a replacement step by applying ranking and crowding, what implies that feasible solutions in a generation can be discarded if they are in the most crowded regions of the current front.

**Comment by matthieu-vergne** [comment]
@ajnebro, in the case of having only few non violating solutions, is it also possible to loose all of them with this algorithm? Or is there some guarantee that at least some of them are preserved in the next generation?

**Comment by suixinzhenguai** [comment]
@ajnebro ，I agree with @matthieu-vergne  ’s point of view. Isn’t it a priority to preserve few  non violating solutions? And when I use NSGA2, this problem can be solved very well.

**Comment by matthieu-vergne** [comment]
It is not my point of view. I only ask about the expected result and state of the code. @ajnebro confirmed that feasible solutions can be discarded, but it seems you observed a case where it discards all of them. My only question is whether or not such a behaviour is to be expected with this algorithm.

If it is, then that's it, it might happen. If it is annoying, just use another algorithm.

If it should not happen, then maybe there is some bug fixing to do, and more analysis should be done.

**Comment by ajnebro** [comment]
I'm using GDE3 to solve some of the included benchmark problems and the produced fronts seem to be ok. If feasible solutions are found, they are only discarded in the replacement step if they are dominated by solutions of the offspring population or after applying the ranking and crowding methods.

**Comment by matthieu-vergne** [comment]
I have no doubt it works well, but I don't speak about personal experience
but about design. Is it possible, in theory, to loose all the feasible
solutions of the previous generation with this algorithm?

Regarding domination, I understand that one may be lost only if another
feasible solution is found, so you cannot reach 0 feasible solutions in
this way, although it may decrease to 1 feasible solution.

Regarding ranking and crowding, is it possible to reach 0 feasible
solutions?

>

**Comment by ajnebro** [comment]
The answer is yes. It can be possible that, when solving a constrained problem, all the solutions in the population be unfeasible. In that case, the ranking will consider the constraint violation degree. If you try the `SMPSORPChangingTheReferencePointsAndChartsRunner`, the problem dealed with is highly constrained and only after about 60-80 iterations a feasible solution is found and then a front appears.

**Comment by Juanjdurillo** [comment]
In GDE3 each solution in a population P(t) is compared using the
DominanceComparator to compare it with the child generated from it. If it
is dominated by its child, then it will not be taken to be part of the
population of the next generation P(t+1). This deviates slightly from the
way it is done in NSGA-II and it is how GDE3 is described in GDE3 original
paper. I would assume that this may be the reason why some feasible
solutions are not preserved from generation to generation in your case
despite  "having room for it".

As @ajnebro said, having all non-feasible solutions in a population is a
normal issue though.

One last thing, for the sake of a sanity check, how are you setting the
constraints values in jMetal? By default,  the constraint violation value
of a solution is a negative a number. If you are using constraint violation
values bigger than 0, the comparator will ignore the constraint violations.
Yes, this is crying for improvements ...
