### ISSUE TITLE
Maven Repo don't have jMetal jar file

### ISSUE THREAD

**Issue by zhouxiumin** [jMetal/jMetal#282]
I wanted to implement my algorithms using jMetal 5. After I  introduced jmetal dependency, the jmetal jar file was missing. I found that the cnetral repository did not have jar files.
[Repo link](http://central.maven.org/maven2/org/uma/jmetal/jmetal/5.5.3/)

**Comment by ajnebro** [comment]
The jMetal project is structured in four Maven subprojects: jmetal-core, jmetal-algorithm, jmetal-problem, and jmetal-exec. Dependending on the requirements of your project, you may need to import the needed dependences for those subprojects (e.g., the one of jmetal-core is here: https://search.maven.org/artifact/org.uma.jmetal/jmetal-core/5.5.3/jar).

**Comment by matthieu-vergne** [comment]
I updated the readme in #283 to provide a short description of how to use them.
