### ISSUE TITLE
SBX generates different solutions from version 4.5 and 5.5 of jMetal

### ISSUE THREAD

**Issue by fritsche** [jMetal/jMetal#284]
In the last `else` from `doCrossover` the implementations are a bit different
* jMetal4.5:
```java
else {
          offs1.setValue(i, valueX2) ;
          offs2.setValue(i, valueX1) ;
        } // if
```

* jMetal 5.5
```java
else {
          offspring.get(0).setVariableValue(i, valueX1);
          offspring.get(1).setVariableValue(i, valueX2);
        }
```
one sets valueX1 to offspring 0 and the other implementation does the opposite.

I have tested using the same seed (changing the implementation of PseudoRandom from jMetal4.5 to be compatible to the random of jMetal5.5) and passing the same parents; the generated offspring are different from 4.5 to 5.5.

May this difference affect the quality of the output of an algorithm?

**Comment by fritsche** [comment]
It was changed 4 years ago on the commit [Added SBXCrossoverTest ](https://github.com/jMetal/jMetal/commit/854d6eebff62f83898df9be617b603ce80a9c594).
Was it a bugfix compared to jMetal4.5? 
Should I do the same on a project that uses jMetal4.5?

**Comment by fritsche** [comment]
[](url)

**Comment by fritsche** [comment]
[](url)

**Comment by Juanjdurillo** [comment]
The original implementation and description of Prof. Deb is as in jMetal
4.5. I cannot say if there is any quality loss or not (I expect only small
differences, hard to quantify in stochastic algorithms). I am unsure why
the implementation was changed.

**Comment by ajnebro** [comment]
>  I am unsure why the implementation was changed.

The reason is surely that I made a mistake when reimplementing the operator. I have made the change and it doesn't seem to affect the performance of NSGA-II after solving some problems with it.

**Comment by ajnebro** [comment]
Fixed.
