### ISSUE TITLE
How to add own Problems

### ISSUE THREAD

**Issue by akkbng** [jMetal/jMetal#285]
Hi,
I want to implement my own Multi-Objective Problem using jMetal but i couldn't find a simple set of instructions how to do that. Is there a document/source that you can recommend? I've done Google searches with keywords "jMetal tutorial", "jMetal problem define" etc. but couldn't find anything useful.
Thanks in advance

**Comment by fritsche** [comment]
Hi,

You can find more information in jMetalDocumentation repository.
Here is the page about problems:
- https://github.com/jMetal/jMetalDocumentation/blob/master/problem.md
