### ISSUE TITLE
Support for the Many-objective Optimization

### ISSUE THREAD

**Issue by ashleyhuo** [jMetal/jMetal#291]
Hi, can the jMetal support the calculation of the Many-objective Optimization?
I can change the objective  number of the DTLZ problems. 
But when compute the quality indicators, the pareto_fronts of more than three objective do not include in "...jmetal-problem\src\test\resources\pareto_fronts".
What can I do if I want to compute the quality indicators for the many-objective Optimization.

**Comment by fritsche** [comment]
Hi,

You need to generate the reference fronts.
The paper http://www.cs.bham.ac.uk/~likw/publications/MOEADD.pdf describes how to generate for DLTZ1-4.

The Walking Fish Group offers a toolkit to generate random reference fronts for WFG problems (http://www.wfg.csse.uwa.edu.au/toolkit/), then you must to remove dominated solutions for disconnected problems (e.g. WFG2). 

https://github.com/fritsche/reference-fronts repository offers some reference fronts for many-objective problems.
