### ISSUE TITLE
Problem of  SPEA2  algorithm

### ISSUE THREAD

**Issue by Ziwardlxh** [jMetal/jMetal#294]
How  to  configurate  SPEA2    algorithm  in  the  JMetal ?

**Comment by matthieu-vergne** [comment]
I let @ajnebro reply to this one.

**Comment by ajnebro** [comment]
You have a [runner class](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/SPEA2Runner.java) for that.
