### ISSUE TITLE
shouldTheHypervolumeHaveAMininumValue Test Error

### ISSUE THREAD

**Issue by anuraganands** [jMetal/jMetal#296]
getting the build error for shouldTheHypervolumeHaveAMininumValue:

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.074 sec <<< FAILURE! - in org.uma.jmetal.algorithm.multiobjective.abyss.ABYSSIT
shouldTheHypervolumeHaveAMininumValue(org.uma.jmetal.algorithm.multiobjective.abyss.ABYSSIT)  Time elapsed: 0.367 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.uma.jmetal.algorithm.multiobjective.abyss.ABYSSIT.shouldTheHypervolumeHaveAMininumValue(ABYSSIT.java:85)

**Comment by matthieu-vergne** [comment]
I think there is some tests that lack in determinism and fail sometimes. Isn't it one of them?

Does it fail systematically with you?

**Comment by anuraganands** [comment]
It has happened with the first build of JMetal source code in Netbeans. I tried couple of times but every time I get the same error. mombi2 and abyss both gives error on shouldTheHypervolumeHaveAMininumValue with the given test files. For ABYSSIT it has happened with: 
double hv = (Double)hypervolume.evaluate(population) ;
assertTrue(hv > 0.64) ;

and similarly, on MOMBI2IT:
double hv = (Double)hypervolume.evaluate(population) ;
assertTrue(hv > 0.968) ;

**Comment by ajnebro** [comment]
These are integration tests that check the observed behavior in many cases, but it's true that the algorithms are non-deterministic, so it would possible that they could not achieve results with the enough quality to pass the tests in a particular run.

I have never experienced fails with those tests, but if they fail sometimes I will have to deal with that. Besides the choice of removing them, perhaps the tests could be executed a number of times in case of failure during a maximum number of iterations.

**Comment by anuraganands** [comment]
Thanks @ajnebro and @matthieu-vergne for your input. 

I think it is a systematic error. It works fine when I disable the integration testing for shouldTheHypervolumeHaveAMininumValue.

**Comment by matthieu-vergne** [comment]
At first run of the whole test suite, the ABYSSIT runs fine on my machine (in 0.350s). The one from MOMBI2IT failed. Running everything a second time lead to the same result. Running specifically the MOMBI2IT one leads only to failures with several attempts. I completed the test to display the faulty value, and here it is, always the same:
```
java.lang.AssertionError: HV = 0.9665663427440061 ≤ 0.968
	at org.uma.jmetal.algorithm.multiobjective.mombi2.MOMBI2IT.shouldTheHypervolumeHaveAMininumValue(MOMBI2IT.java:101)
```

So it appears to be systematic, at least in the sense that it returns the same value. Now it may be that it depends on the machine. @ajnebro, could you share the value you obtain and whether it is always the same on your machine? @anuraganands could you do the same?

Just replace the line 101:
```java
assertTrue(hv > 0.968) ;
```
by this:
```java
assertTrue("HV = "+hv+" ≤ 0.968", hv > 0.968) ;
```

**Comment by ajnebro** [comment]
I get the same value. The random seed is fixed, so the algorithm always returns the same front. 

That test never failed before, so perhaps an update of the JVM could affect the random number generator. Anyway, the idea of these integration tests is to ensure that the algorithms produce a front with a minimum degree of quality. The value 0.968 is a bit arbitrary (set after running MOMBI2 a number of times). We can relax the condition to, let's say, `hv > 0.96` and the meaning of the test would be the same.

**Comment by matthieu-vergne** [comment]
You are the expert. {^_^}

@anuraganands, can you confirm you also obtain the same value? And if you replace the constraint by 0.96 does it work for you?

**Comment by anuraganands** [comment]
The MOMBI2 error has passed with `hv > 0.96`.

_Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.77 sec - in org.uma.jmetal.algorithm.multiobjective.mombi2.MOMBI2IT_

However, ABYSSIT had failed in the first run but worked later :)

Thanks

**Comment by matthieu-vergne** [comment]
ABYSSIT seems to be the one which occurs sporadically. Since running it again is enough to make it pass, I suggest to close this issue with the fix of the test of MOMBI2, which is the blocking one. If someone wants to investigate the ABYSSIT case, another issue can be open specifically.
