### ISSUE TITLE
Eclipse IDE: class org.uma.jmetal.runner.multiobjective.RNSGAIIRunner

### ISSUE THREAD

**Issue by shdotcom** [jMetal/jMetal#297]
I have got this error "class org.uma.jmetal.runner.multiobjective.RNSGAIIRunner" when I tried to run RNSGAII algorithm. I am using eclipse IDE

**Comment by matthieu-vergne** [comment]
Please tell us how you run it and provide the full stack trace. We cannot
do much without that.

**Comment by shdotcom** [comment]
Sorry, it was my mistake, I have imported the projects as a java project. while it should be imported as a Maven project. 
When I imported it as a Maven project, I followed these steps:
https://www.lagomframework.com/documentation/1.4.x/java/EclipseMavenInt.html

In "Goals" field I entered , "install" instead of "lagom:runAll" . Then I got this:

...
...
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty/6.1.25/jetty-6.1.25.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty/6.1.25/jetty-6.1.25.pom (6.3 kB at 4.9 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/project/6.1.25/project-6.1.25.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/project/6.1.25/project-6.1.25.pom (9.2 kB at 5.1 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-parent/10/jetty-parent-10.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-parent/10/jetty-parent-10.pom (3.3 kB at 4.1 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/14/jetty-parent-14.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/14/jetty-parent-14.pom (16 kB at 13 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-util/6.1.25/jetty-util-6.1.25.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-util/6.1.25/jetty-util-6.1.25.pom (3.9 kB at 7.3 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.pom (2.7 kB at 5.0 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-parent/7/jetty-parent-7.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/mortbay/jetty/jetty-parent/7/jetty-parent-7.pom (13 kB at 16 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom (22 kB at 21 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/37/commons-parent-37.pom
...
...

Please confirm if the steps are correct or not. Thank you

**Comment by matthieu-vergne** [comment]
If you never learned how to use Maven, then please look around on the net. There is plenty to know about it. Once opened in your favourite IDE, just run the tests to check all is green. Then use it how you intend to.

Anyway, this issue is now obsolete. Please close it and open another when required.
