### ISSUE TITLE
How to run an experiment in JMetal 5.6?

### ISSUE THREAD

**Issue by shdotcom** [jMetal/jMetal#298]
Would you please describe the steps of running one of the experiments provided in
[this link](https://github.com/jMetal/jMetal/tree/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment)
Thank you

**Comment by matthieu-vergne** [comment]
As indicated in the readme of this project, you can find the full documentation here:
https://github.com/jMetal/jMetalDocumentation
