### ISSUE TITLE
Syntax error in R code 

### ISSUE THREAD

**Issue by shdotcom** [jMetal/jMetal#299]
Hi,
I have found this syntax error in the generated R code by running **ZDTStudy.java**
Please check the attached photo.
Thank you

![err1](https://user-images.githubusercontent.com/22214093/47861866-c339b100-de2e-11e8-937e-e5fd6124681f.JPG)

**Comment by matthieu-vergne** [comment]
Seems like mine is going wild:
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```
So I cannot try it for now. But looking at the code I did not see any way to obtain a script like that.

Could you give me the commit you are at?

**Comment by shdotcom** [comment]
I have downloaded JMetal from[ this link](https://jmetal.github.io/jMetal/) (Source code: jMetal-5.6.zip), which seems is not updated.

Please check the differences between the **GenerateWilcoxonTestTablesWithR.java**  in your [previous link](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/experiment/component/GenerateWilcoxonTestTablesWithR.java#L281) and [this](https://jmetal.github.io/jMetal/):


`private static final String END_STATEMENT = "\"){\n)";`

```
"for (i in algorithmList) {" + "\n" +
        "  if (i != \"" +  experiment.getAlgorithmList().get(experiment.getAlgorithmList().size() - 1).getAlgorithmTag()+ END_STATEMENT +
        "    write(i , \"" + latexFileName + APPEND_STRING +
```

This `END_STATEMENT = "\"){\n)";` is the reason of the extra brackets.

**Comment by matthieu-vergne** [comment]
At least, we don't have it anymore. {^_^}
