### ISSUE TITLE
Save IGD values at each generation

### ISSUE THREAD

**Issue by shdotcom** [jMetal/jMetal#300]
The NSGAIIStudy.java example calculate and save the IGD values at each **run**. How can I do this at each generation? 

> number of generations = evaluations / max population

because, what I need to do then is to plot the IGD values at each generation.

**Comment by ajnebro** [comment]
I have just added a class for that: [NSGAIIMeasuresWithQualityIndicatorRunner](https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/NSGAIIMeasuresWithQualityIndicatorRunner.java).

Please, take a look to it to see whether it is what you need.

**Comment by shdotcom** [comment]
Yes, this exactly what I need. I just need to do some modification to save the values of the performance indicators of each iteration in an external file.
But, In the printed result, the last iteration is 248, while I think, it should be 249, because, Max_iteration= 250, is in't it?
Please check the attached photo.
Thank you
![j2](https://user-images.githubusercontent.com/22214093/47918273-153e0d80-dee7-11e8-9649-85a3dff6b931.JPG)

**Comment by ajnebro** [comment]
The reason is that the iteration counter is initialized in the runner program to zero instead of 1.

**Comment by shdotcom** [comment]
@ajnebro would you please check the code when maxEvaluations=100;
In this case, one result should be printed by ```
System.out.println("Iteration: " + counter +
              ". Epsilon: " + epsilon.evaluate(solutionList) + ". Hypervolume: " + hv.evaluate(solutionList)) ;
``` but, this is not the case in the current code. If the initial value of `counter=0` and the `` number_of_generations = maxEvaluations/ populationSize``. Then the last value of the counter should be **number_of_ generations-1** So, in the code,  last value of the counter = 250-1=249 not 248
