### ISSUE TITLE
Plotting performance indicators values at each iteration for R-NSGA-II algorithm

### ISSUE THREAD

**Issue by shdotcom** [jMetal/jMetal#304]
I have modified `RNSGAII.java`, `ChartContainerWithReferencePoints.java` and `RNSGAIIWithChartsRunner.java` classes to plot performance indicators values at each iteration, but when I run the project, they are not plotted in the chart.

The modified classes are here:

[RNSGAII.java](https://github.com/shdotcom/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/rnsgaii/RNSGAII.java)

[RNSGAIIWithChartsRunner.java](https://github.com/shdotcom/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/RNSGAIIWithChartsRunner.java)

[ChartContainerWithReferencePoints.java](https://github.com/shdotcom/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/chartcontainer/ChartContainerWithReferencePoints.java)

![chart](https://user-images.githubusercontent.com/22214093/48139314-2a4cdf00-e2e1-11e8-86d7-2bbd9e8c5f8f.JPG)

**Comment by matthieu-vergne** [comment]
Please don't copy paste full source code, it is too time consuming and really inefficient to investigate that way.

If you want us to evaluate your changes, please fork the project, change your fork, and give us a link to the branch where you made your fixes. This way we can make a diff to see exactly what you have changed, clone your fork to try it, and investigate better what you did wrong.

**Comment by shdotcom** [comment]
@matthieu-vergne  I have edited the issue. please check the modified classes.
