### ISSUE TITLE
There is no  'updateNeighborhood' operation in the run() function of MOEA/D-STM algorithm.

### ISSUE THREAD

**Issue by dongzhiming** [jMetal/jMetal#306]
There is no  updateNeighborhood operation in the run() function of MOEA/D-STM algorithm.
The next generation of population comes from the stmSelection() operation.

` for (int i = 0; i < populationSize; i++) {
        ... ...
        updateNeighborhood(child, subProblemId, neighborType);
        ... ...

}`

**Comment by matthieu-vergne** [comment]
I am not personally familiar with this algorithm. Could you tell what is the problem, what do you expect instead, and why?
