### ISSUE TITLE
Write/read a list of solutions to/from file

### ISSUE THREAD

**Issue by pwangsom** [jMetal/jMetal#308]
I have a plan to run a large experiment comparing many algorithms with several different parameters.
I also would like to keep solutions of each generation.
I am thinking to write those solutions to a file.
Once all algorithms are done, I would like to read all solutions from files and sort those solutions by nondominated sorting and measure them.

So, I would like to know that it is possible to write a list of solutions and read them later for sorting and measuring them.
If yes, please give me some examples.
Thank you in advance.

**Comment by ajnebro** [comment]
If you store all the generated solutions into files and put them in a directory, you can use the utility [`GenerateReferenceFrontFromFile`] (https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/utility/GenerateReferenceFrontFromFile.java) to get the nondominated solutions. Is this what you are looking for?

**Comment by pwangsom** [comment]
Dear ajnebro

Thank you for your suggestion. I think it is I am looking for.
