### ISSUE TITLE
Compute Hypervolume

### ISSUE THREAD

**Issue by leodsti** [jMetal/jMetal#311]
Hi,

I struggle trying to compute the hypervole of a pareto front in a file.
My situation is that I have a file in 2 dimention containg a Pareto Front and I would like to compute the Hypervolume.

I don't understand how to load the pareto front in a List Solution Object.

Could you please help me out.

Thank you in advance,
Regards,

**Comment by matthieu-vergne** [comment]
There is an example in the documentation with the hypervolume:
https://github.com/jMetal/jMetalDocumentation/blob/master/qualityIndicators.md

Would it be enough?

**Comment by matthieu-vergne** [comment]
You're welcome.

When one of your issues is solved, feel free to close it by yourself.
