### ISSUE TITLE
Duplicate += oprator.

### ISSUE THREAD

**Issue by AlexZabashta** [jMetal/jMetal#312]
https://github.com/jMetal/jMetal/blob/b3c63dd36ee97a181594a7a08dfefdf612504a1e/jmetal-core/src/main/java/org/uma/jmetal/util/pseudorandom/impl/ExtendedPseudoRandomGenerator.java#L93

Looks like it should be:  `length += x[i] * x[i];` or `length = length + x[i] * x[i];` but not both.

**Comment by matthieu-vergne** [comment]
Given:
- it computes the length of a vector ;
- such length is computed as <img src="https://latex.codecogs.com/gif.latex?\inline&space;\sqrt{\sum&space;x_i^2}" title="\sqrt{\sum x_i^2}" /> ;
- `sqrt` is applied after the loop ;

then, indeed, it should be `length += x[i] * x[i]`.

@ajnebro may fix it. I think a test on the distribution of this function would be a great addition.

**Comment by AlexZabashta** [comment]
Also you should check that `length > 0`
I know the probability of `length == 0` too small but it still can happen.

**Comment by AlexZabashta** [comment]
https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/pseudorandom/impl/ExtendedPseudoRandomGenerator.java#L130

The second case has not been fixed.

**Comment by ajnebro** [comment]
Fixed.
