### ISSUE TITLE
Experiment Design with NSGAIII and cMOEA/D on a PermutationSolutions<Integer> Problem.

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [jMetal/jMetal#313]
Hi,
I have a problem that has many-objectives, multi constraints and represented as PermutationSolutions<Integer>. 

How can I use PermutationSolutions<Integer> with cMOEA/D  Algorithm and design an experiment to compare two algorithms (NSGAIII , cMOEA/D) on the problem? 

Thank you

**Comment by ajnebro** [comment]
The implementation of MOEA/D and cMOEA/D in jMetal assumes that the problem is continuous and uses differential evolution. If you want to use permutations, you should adapt the code to use crossover and mutation that can be applied to that encoding.
