### ISSUE TITLE
[Urgent] - Metrics Formulas for paper publication

### ISSUE THREAD

**Issue by leomitd** [jMetal/jMetal#315]
Hi All,

First of all, let me tell you what an amazing job this Framework is!

I am writing a paper using jMetal to write a scientific paper.
However, I am wondering what are the scientific formulas for the different metrics.

I can easily find the Hypervolume, GD and IGD but what about the others?
It is not documented what jMetal actually implements. The only chance is to go and decrypt the code.

I am thinking about first what Normalisation is being used and how the Epsilon and Spread are being implemented.

Thank you very much in advance,

Regards,

**Comment by matthieu-vergne** [comment]
I remember some of them mention the source paper they implement in their Javadoc or comments, directly in the code. I don't know how much of them do this effort, though. Probably @ajnebro knows better. Surely, I would agree to systematically have them there.

**Comment by ajnebro** [comment]
Take a look to this paper: https://sop.tik.ee.ethz.ch/publicationListFiles/ztlf2002a.pdf
