### ISSUE TITLE
Help on building jmetal

### ISSUE THREAD

**Issue by hyapici** [jMetal/jMetal#319]
I'm having a problem when I try to create a project with jMetal on Eclipse IDE. The error message reads:
The project was not built due to "A resource exists with a different case: '/jMetal-master/bin/org/uma/jmetal/qualityindicator'.". Fix the problem, then try refreshing this project and building it since it may be inconsistent	jMetal-master		

how can I fix this problem? Any help will be much appreciated.

**Comment by matthieu-vergne** [comment]
Please look at the documentation:
https://github.com/jMetal/jMetalDocumentation

Especially the installation part:
https://github.com/jMetal/jMetalDocumentation/blob/master/installation.md

If it is incomplete or you fail to do what it says, please open an issue [there](https://github.com/jMetal/jMetalDocumentation/issues) telling exactly what you did, what you expected, and what you get.
