### ISSUE TITLE
Quality Indicators in JMetal Experiments

### ISSUE THREAD

**Issue by gadhaunaslam** [jMetal/jMetal#324]
I am using experiment class for three algorithms for many-objective benchmark problems. 

After the algorithms are executed, this is called: 	
new ComputeQualityIndicators<>(experiment).run();
	
This eventually creates separate folders for all three algorithms and has all quality indicators. Now if i want to calculate the overall hypervolume, is there a method that can do it? OR will i have to take a mean of the ones found above for individual algorithms?

Early response will be appreciated!!!

**Comment by csgeek95** [comment]
@ajnebro @matthieu-vergne

**Comment by ajnebro** [comment]
What do you mean for the overall hypervolume? 

After running the `ComputeQualityIndicators<>(experiment).run()` method what you get, in the case of the Hypervolume, a file called `HV` with the hypervolume value of all the independent runs.

**Comment by csgeek95** [comment]
Yes, that is right. So, in my case, i am applying three algorithms to a problem in configureAlgorithmList function, and after the execution of this function, i was assuming one file HV for this experiment. But instead i get three files because of the three algorithms i am using. 

So, i was wondering is there any way i could get like one HV file for the entire experiment?

**Comment by ajnebro** [comment]
Just take a look to the ZDTExperiment2: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/experiment/ZDTStudy2.java. You can indicate a directory to store the global Pareto front (line 75) and obtain it by calling the `new GenerateReferenceParetoSetAndFrontFromDoubleSolutions(experiment).run();` method. 

Then, you can calculate its HV with the `CommandLineIndicatorRunner` utility: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/qualityIndicator/CommandLineIndicatorRunner.java (line 88)

**Comment by csgeek95** [comment]
Hello! Thanks for your reply. 

If i use the new GenerateReferenceParetoSetAndFrontFromDoubleSolutions(experiment).run(); method, can i not use the new ComputeQualityIndicators<>(experiment).run(); method instead of the CommandLineIndicatorRunner utility?
