### ISSUE TITLE
Chromosome including two parts

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [jMetal/jMetal#327]
Hi, 
I want to use a chromosome with two parts, in each mutation and crossover operators have to be applied separately. Is it possible to implement it by Jmetal5 ? Or do I have to modify variable in  AbstractGenericSolution.

Thank you

**Comment by matthieu-vergne** [comment]
You can implement your own operators (mutation & crossover) for that. More precisely:
- choose (or implement) a mutation operator for the first part
- choose (or implement) a mutation operator for the second part
- implement a mutation operator which builds on the 2 others
- do the same for crossover
- run the algorithm with your new operators

This is the route I would take to do what you want. If you have trouble to do it, you will need to share more details about what you want to do.

**Comment by CumaliTurkmenoglu** [comment]
Thanks for the route you advised. Unfortunately, I didn't understand how to have the first part and the second part of the chromosome.  
Details:
I try to optimize a diet problem which has many objectives, many constraints (daily required nutrient intakes). For now, I am recommending a menu to the user but I want to divide the menu as breakfast and lunch+dinner. To do this I need to optimize first part of the chromosome with breakfast foods the other with Lunch-Dinner type foods (I don't want them to be mixed with crossover and mutation). By that way, I'll have a more realistic menu recommendation.

**Comment by matthieu-vergne** [comment]
If they are completely independent, what you can do is:
- run an algorithm for identifying the best breakfast
- run an algorithm for identifying the best lunch+dinner
- return a menu which combines both results.

How does it sound?

**Comment by CumaliTurkmenoglu** [comment]
Unfortunately, they are not. For Example a 25 years old man daily Energy need is 2400-3000 Kcal. 1/3 of this range is gonna to be for breakfast and the rest for dinner+lunch. If breakfast part satisfied from the lower bound of its own range the lunch+dinner will have a larger room to fill. If I find them separately, Energy taken from both could exceed the  2400-3000 range, so they have to be optimized together. 

For now, I am going to have a PermutationSolution<Integer>solution and create my own crossover, mutation operators and DefaultIntegerPermutationSolution() for my problem. Then I will handle the solution as  two parts in initialization, crossover and mutation phases. I hope I could do it. 

Thanks

**Comment by pwangsom** [comment]
Dear CumaliTurkmenoglu,

I am going to implement a specific chromosome as you proposed as well.
However, instead of using a chromosome having multiple parts, I would like to implement a solution having multiple chromosomes (e.g. two chromosomes including X chromosome and Y chromosome). When crossover and mutation operations are performed, they should be applied to X and Y chromosome separately. 

Could you please share your implementation and suggestion to implement a group of chromosomes.

Thank you

**Comment by CumaliTurkmenoglu** [comment]
Hi,
I have solved this problem for my problem: Many-Objective Diet optimization
with two(n) parts.
I used permutation representation, I determined splitting points for n
parts of the chromosome. I initialized both parts with randomly related
numbers(food ID's, Breakfast foods for first part others for the second
part).  I reimplemented mutation and crossover operators accordingly. I
split some of the constraints into two parts according to percentages for
breakfast/lunch/Dinner, used different additional constraints for each
part, evaluate constraints for each part of the chromosome separately.
Therefore constraint evaluation is separately but the objective calculation
is applied for all parts together.

Shortly, split the chromosome (initialize randomly and separately) with
some splitting points, in optimization phase:  for each chromose in a loop
of parts evaluate constraints separately, optimize objectives together.

Best,

**Comment by matthieu-vergne** [comment]
That is good to know.
Do you think you could contribute something to jMetal?
Maybe we could create a template that allows to do that.

**Comment by CumaliTurkmenoglu** [comment]
Hi,

It will be a pleasure for me to contribute to JMetal. Unfortunately, I am
so busy with my thesis. Later I will have enough time to contribute with a
consistent and generic many-part chromosome implementation.

Thanks for your proposal,
Best

------------------------------------------------------------------------------------------------------------------------------------------
Cumali TÜRKMENOĞLU

Computer Scientist
Ph.D. Candidate at Istanbul Technical University
Research Assistant at the Faculty of Computer Science & Informatics
Maslak Campus, 34469 Istanbul

Phone   :  +90 541 462 14 22
E-Mail   :  turkmenogluc@itu.edu.tr


Matthieu Vergne <notifications@github.com>, 18 Haz 2019 Sal, 19:23
tarihinde şunu yazdı:

**Comment by matthieu-vergne** [comment]
Thank you.

If your problem is solved, I suggest you to close this issue.
When you find time to contribute, feel free to open a merge request or a new issue on that matter.

**Comment by pwangsom** [comment]
Hi CumaliTurkmenoglu,
Thank you for sharing
