### ISSUE TITLE
Test testing nothing in NaryTournamentSelection

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#328]
In the tests of `NaryTournamentSelection`, there is this test:
```java
  @Test
  public void shouldExecuteReturnTwoSolutionsIfTheListContainsTwoSolutions() {
    NaryTournamentSelection<IntegerSolution> selection =
        new NaryTournamentSelection<>(2, mock(Comparator.class)) ;

    IntegerSolution solution1 = mock(IntegerSolution.class) ;
    IntegerSolution solution2 = mock(IntegerSolution.class) ;

    List<IntegerSolution> population = Arrays.asList(solution1, solution2) ;
    assertEquals(2, population.size());
  }
```
It does not use the instantiated `selection`. Actually, as it is, the assertion is testing `Arrays.asList()`, nothing related to jMetal. I assume the list should be consumed by `selection.execute()`, but then it returns only a single solution (not a list), so it seems odd to have a test checking it returns 2 of them.

Since I cannot figure out what is the right way to revise it, could you please do it @ajnebro ?

**Comment by ajnebro** [comment]
That test does not make sense. I have just removed it.

**Comment by matthieu-vergne** [comment]
Thanks
