### ISSUE TITLE
Possible bug in comparator.DominanceComparator#dominanceTest method

### ISSUE THREAD

**Issue by iorixxx** [jMetal/jMetal#346]
```java
 private int dominanceTest(S solution1, S solution2) {
    int bestIsOne = 0 ;
    int bestIsTwo = 0 ;
    int result ;
    for (int i = 0; i < solution1.getNumberOfObjectives(); i++) {
      double value1 = solution1.getObjective(i);
      double value2 = solution2.getObjective(i);
      if (value1 != value2) {
        if (value1 < value2) {
          bestIsOne = 1;
        }
        if (value2 < value1) {
          bestIsTwo = 1;
        }
      }
    }
    if (bestIsOne > bestIsTwo) {
      result = -1;
    } else if (bestIsTwo > bestIsOne) {
      result = 1;
    } else {
      result = 0;
    }
    return result ;
  }
```

In the loop of the method, a particular objective is compared and primitive data structures updated accordingly at a time. As the loop continues primitive variables are overridden. At the end, the final decision is made using the last objective. The dominance method is effectively same as :

```java
return Double.compare(
    solution1.getObjective(solution1.getNumberOfObjectives() - 1),
    solution2.getObjective(solution1.getNumberOfObjectives() - 1));
```

**Comment by matthieu-vergne** [comment]
If I am correct, the purpose is to figure out whether one of the solutions dominates the other. To do so, we aim for finding at least 1 objective where solution 1 dominates 2, and at least one where 2 dominates 1. These 2 conditions are represented, respectively, by the two variables `bestIsOne` and `bestIsTwo`. You can consider them as boolean initialized at false, and then set at true when finding a dominated objective. At the end, we check whether we found one dominance only (-1), the other dominance only (1), or no dominance or both (0). They are integers to order them, so comparisons at the end are easier.

As a general comment for pull requests, please refrain from opening an issue on the mere *possibility* of a bug. It is always possible unless we do formal validation, which we don't, so one may open an infinite amount of issues on the sole reason of possible bugs. Please first confirm the bug by yourself, and only then open an issue which provides the proof of the bug and, preferably, a fix to make it pass.

To do so, you can create a test on a specific case and confirm that it does not return the right result. We already have a test class for this one (`DominanceComparatorTest`) and they are all green. So feel free to investigate our tests, figure out a case that we may have forgotten and which might highlight a mistake on our side.

**Comment by iorixxx** [comment]
Ups sorry for the noise and thank you for the explanation.
