### ISSUE TITLE
How can I use the reference front to set the hypervolume reference point?

### ISSUE THREAD

**Issue by fritsche** [jMetal/jMetal#352]
I have tried to set offset to zero, but with both WFGHypervolume and PISAHypervolume the result does not match as I expected.
I have tested with two fronts, A and B (B dominates A).
WFGHypervolume gives: hv(A)=0.03 and hv(B)=0.01
PISAHypervolume gives: hv(A)=0.30 and hv(B)=0.46
I expected: hv(A)=0.10 and hv(B)=0.22

```java
        Problem p = new ZDT1(); // any problem
        List<DoubleSolution> reference = new ArrayList<>();
        DoubleSolution s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.0);
        s.setObjective(1, 0.8);
        reference.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.2);
        s.setObjective(1, 0.2);
        reference.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.8);
        s.setObjective(1, 0.0);
        reference.add(s);

        List<DoubleSolution> A = new ArrayList<>();
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.4);
        s.setObjective(1, 0.7);
        A.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.5);
        s.setObjective(1, 0.6);
        A.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.6);
        s.setObjective(1, 0.5);
        A.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.7);
        s.setObjective(1, 0.4);
        A.add(s);

        List<DoubleSolution> B = new ArrayList<>();
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.3);
        s.setObjective(1, 0.5);
        B.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.4);
        s.setObjective(1, 0.4);
        B.add(s);
        s = (DoubleSolution) p.createSolution();
        s.setObjective(0, 0.5);
        s.setObjective(1, 0.3);
        B.add(s);

        Hypervolume hv = new WFGHypervolume(new ArrayFront(reference));
        hv.setOffset(0.0);
        Double res = (Double) hv.evaluate(A);
        System.out.println(res);
        res = (Double) hv.evaluate(B);
        System.out.println(res);

        hv = new PISAHypervolume(new ArrayFront(reference));
        hv.setOffset(0.0);
        res = (Double) hv.evaluate(A);
        System.out.println(res);
        res = (Double) hv.evaluate(B);
        System.out.println(res);
```

**Comment by matthieu-vergne** [comment]
I'll let @ajnebro reply to this one, since it is out of my field of competence.

**Comment by fritsche** [comment]
I have checked PISAHypervolume, looks like referenceParetoFront and offset are not used at hypervolume computation. Only the method computeHypervolumeContribution uses the referenceFront and the offset.

For WFGHypervolume, the referenceParetoFront is used to generate the reference point, however the point is overrided when evaluate is called. https://github.com/jMetal/jMetal/blob/7dfbd0c44f95701dc5d6c1184b7ddb51c919865c/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/WFGHypervolume.java#L68

**Comment by ajnebro** [comment]
As you mention, the PISAHypervolume does not allow to indicate a reference point. What is does is to normalize the front, invert it and uses the point (0.0, 0.0, ...) as reference point. 

The WFGHypervolume only works with two objectives, and it does not apply normalization. I have used it very scarcely (only with the SMPSOHv algorithm). The reference pont should not be overriden; I'll check that.

**Comment by ajnebro** [comment]
There are other proposals for computing the hypervolume, as the [one proposed](http://lopez-ibanez.eu/hypervolume) by Carlos M. Fonseca et al. [This site](https://ls11-www.cs.tu-dortmund.de/rudolph/hypervolume/start) contains other implementations, including one in Python. Unfortunately, as far as I know there are not implementations available in Java.

**Comment by fritsche** [comment]
> As you mention, the PISAHypervolume does not allow to indicate a reference point. What is does is to normalize the front, invert it and uses the point (0.0, 0.0, ...) as reference point.

The method `computeHypervolumeContribution` makes use of the reference front and the offset value. I wonder if the `evaluate` method could make use of it as well.

https://github.com/jMetal/jMetal/blob/7dfbd0c44f95701dc5d6c1184b7ddb51c919865c/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/PISAHypervolume.java#L231
