### ISSUE TITLE
Could you provide some examples of configuring the CMA_ES algorithm in JMetal for 3D modeling?

### ISSUE THREAD

**Issue by chatyan** [jMetal/jMetal#355]
Hi, 
I am trying to use CMA_ES algorithm to solve an optimization problem. I focus on 3D modeling and try to encode each 3D vertex for representing a model. I expect that I can find an optimized model though evolving the vertices with respect to a fitness function. 

So far, I found JMetal, Class of CovarianceMatrixAdaptationEvolutionStrategy, and a detailed description of the class. But still, I cannot configure a CMA_ES by using JMetal because of my lack of java programming skill. 

So, I want to ask if my direction is right? And Could you provide me some examples of configuring the CMA_ES algorithm in JMetal for real problem and give me some hint of encoding a 3D vertex, configuration a CMA_ES?

Sincerely.

**Comment by matthieu-vergne** [comment]
I'm not competent enough on this algorithm, so I'll let @ajnebro reply to this one.
Didn't you find what you need in [the documentation](https://github.com/jMetal/jMetalDocumentation)?

**Comment by chatyan** [comment]
No, I did not find any :)
