### ISSUE TITLE
MOEA\D issue

### ISSUE THREAD

**Issue by 1017073490** [jMetal/jMetal#356]
Hi,
I want to use MOEA\D  in Java,but i don't know how to configure my code to use it. Could you give me an example?

Thank you!

**Comment by ajnebro** [comment]
Hi.
  You can use this program to configure and run MOEA/D: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/MOEADRunner.java

Antonio

**Comment by 1017073490** [comment]
First, thank you for your patient apply. But i meet some questions. I hope to ask for your help.
One question is  when i try to new my own problem function for the variable loadProblem, it failed. 
I want to know how to define the problem?  

Looking forward to your reply.
Best wish to you! Thank you!

**Comment by ajnebro** [comment]
You can take a look to any of the available problems (https://github.com/jMetal/jMetal/tree/master/jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective) and to the documentation about how adding them (https://github.com/jMetal/jMetalDocumentation/blob/master/problem.md).
