### ISSUE TITLE
Using Bits Solution (4.5)

### ISSUE THREAD

**Issue by fpgdesa** [jMetal/jMetal#359]
Dears, 
i'm using the NSGA2 algorithm in Feature Selection problem.  The binary solutions generatedes represents, each bit, a feature adopted or not. However, the solution has precision with N bits (double value representation) for each variable. Is correct adopt precision with 1 bit representation?

**Comment by matthieu-vergne** [comment]
If you use the `BinarySolution`, then you must define the number of bits, which could be the number of features to be selected. This way you have 1 bit per feature and can use them as activation genes. If you have 10 features, then I assume you should have solutions of 10 bits.

**Comment by matthieu-vergne** [comment]
Are you speaking about jMetal 4.5?
If yes, then be aware that we are now at jMetal 5.
Any support should be on this new version, not the old one.

**Comment by fpgdesa** [comment]
Thanks!

**Comment by matthieu-vergne** [comment]
If it solves your problem, please close the issue.
