### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by abolfazl-sh** [jMetal/jMetal#361]
Hi.
I think it's so good that add a comprehensive example with details and comments to source code.
thanks in advance.

**Comment by matthieu-vergne** [comment]
Could you please be more specific?
An example for what? Where?

**Comment by abolfazl-sh** [comment]
for example define operators with custom parameters, problems and run them with some different algorithm. I really trying to study and understand the document, but I didn't take it and I didn't found some example code that run an example with different parts.
I hope it was clear.

**Comment by matthieu-vergne** [comment]
Did you check the documentation?
https://github.com/jMetal/jMetalDocumentation

The section about `Running algorithms` is quite verbose on that matter and references implemented runners for examples.

**Comment by abolfazl-sh** [comment]
I am really so sorry, mistakenly I studied another Documentation(not your Documentation).
really sorry.
thanks for response.
