### ISSUE TITLE
make an arrangement of unique number az answer

### ISSUE THREAD

**Issue by abolfazl-sh** [jMetal/jMetal#362]
Hello.
I am working on a problem that every solution is an arrangement of numbers.for example the solution should be an arrangement of 1 to 6 (for example 2,4,5,6,1,3 could be one, without any duplication). does making this kind of solution have implemented in jMetal?
thanks in advance.

**Comment by matthieu-vergne** [comment]
I guess the [PermutationSolution](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/solution/PermutationSolution.java) would be the one to target. Especially the [integer-based implementation](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/solution/impl/DefaultIntegerPermutationSolution.java).

**Comment by abolfazl-sh** [comment]
do you think just using "java.util.Collections.shuffle(List<Integer> list)" to shuffle my solution list is ok?
(I think nothing special happen in the background)

**Comment by abolfazl-sh** [comment]
thanks.
