### ISSUE TITLE
cast defualtIntegerSolution to BinarySolution

### ISSUE THREAD

**Issue by abolfazl-sh** [jMetal/jMetal#363]
Hello.
I am trying to run a NSGA-II algorithm on the problem that I have defined.when I run the algorithm it throw the below:
```
Exception in thread "Thread-1" java.lang.ClassCastException:
org.uma.jmetal.solution.impl.DefaultIntegerSolution cannot be cast to 
org.uma.jmetal.solution.BinarySolution
```
   
it returns some solution and at the end print this Exception.(my code to run the algorithm, if other details needs let me know. thanks in advance).
```
        Problem<IntegerSolution> problem = new StaticPrioritizer();
        Algorithm<List<IntegerSolution>> algorithm;
        CrossoverOperator crossover;
        MutationOperator<IntegerSolution> mutation;
        SelectionOperator<List<IntegerSolution>,IntegerSolution> selection;
        String referenceParetoFront = "";
        double crossoverProbability = 0.9;

        crossover = new SinglePointCrossover(crossoverProbability);
        double mutationProbability = 1.0 / problem.getNumberOfVariables();

        mutation = new PermutationSwapMutation(mutationProbability);

        selection = new BinaryTournamentSelection<IntegerSolution>(new RankingAndCrowdingDistanceComparator<IntegerSolution>());
        
         algorithm = new NSGAIIBuilder<IntegerSolution>(new StaticPrioritizer(), crossover, mutation,100)
        .setSelectionOperator(selection)
        .setMaxEvaluations(50000)
        .build() ;   
               AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm)
        .execute() ;
```

**Comment by matthieu-vergne** [comment]
Could you please share the full stack trace? We miss the source of the exception.

**Comment by abolfazl-sh** [comment]
```
> Exception in thread "Thread-1" java.lang.ClassCastException: org.uma.jmetal.solution.impl.DefaultIntegerSolution cannot be cast to org.uma.jmetal.solution.BinarySolution
> 	at org.uma.jmetal.operator.impl.crossover.SinglePointCrossover.execute(SinglePointCrossover.java:63)
> 	at org.uma.jmetal.operator.impl.crossover.SinglePointCrossover.execute(SinglePointCrossover.java:19)
> 	at org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAII.reproduction(NSGAII.java:125)
> 	at org.uma.jmetal.algorithm.impl.AbstractEvolutionaryAlgorithm.run(AbstractEvolutionaryAlgorithm.java:61)
> 	at java.lang.Thread.run(Thread.java:745)
```
and at the end :
```
Aug 07, 2019 8:13:42 PM org.uma.jmetal.util.JMetalLogger configureLoggers
INFO: Loggers configured with null
Aug 07, 2019 8:13:42 PM REMAP main
INFO: Total execution time: 298ms
Aug 07, 2019 8:13:42 PM org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet
INFO: Random seed: 1565192619285
Aug 07, 2019 8:13:42 PM org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet
INFO: Objectives values have been written to file FUN.tsv
Aug 07, 2019 8:13:42 PM org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet
INFO: Variables values have been written to file VAR.tsv
```

**Comment by matthieu-vergne** [comment]
You used a `SinglePointCrossover` which is made for `BinarySolution`, not for `IntegerSolution`. I am not convinced that such a specialization is wanted, but currently the `SinglePointCrossover` builds on `BinarySolution` features, which do not map completely on the generic `Solution` features. For example, a single variable can store several bits, so a `BinarySolution` should rely more on its `getTotalNumberOfBits()` because the generic `getNumberOfVariables()` does not provide the correct level of detail. `SinglePointCrossover` depends on these details so you cannot use it without using `BinarySolution`.

The easiest fix is to choose another crossover operator which accepts at least `IntegerSolution`.

**Comment by abolfazl-sh** [comment]
I have changed the Crossover and same thing happen for mutation(at least I think the same thing, if the exception needed let me know) by the way, do you have any idea if I want use `SinglePointCrossover` and `PermutationSwapMutation` with `IntegerSolution`?

**Comment by matthieu-vergne** [comment]
> I have changed the Crossover and same thing happen for mutation(at least I think the same thing, if the exception needed let me know)

Well, if it is blocking you then please share the info. If you can fix it yourself, then that is fine.

> by the way, do you have any idea if I want use SinglePointCrossover and PermutationSwapMutation with IntegerSolution?

You can look at the code :
```java
public class SinglePointCrossover implements CrossoverOperator<BinarySolution>
```
So it works with `BinarySolution`, and `IntegerSolution` is not a `BinarySolution`.
```java
public class PermutationSwapMutation<T> implements MutationOperator<PermutationSolution<T>>
```
So it works with `PermutationSolution`, and `IntegerSolution` is not a `PermutationSolution` either.

Maybe their code can be generalized to be applied to `IntegerSolution`, but currently they are not applicable. Generalizing would need to investigate the code. I can't say in advance whether or not we can do it.

**Comment by abolfazl-sh** [comment]
I will take a look at code(if I found something usable I will notify).
thanks a lot for response.
