### ISSUE TITLE
make fixed numbers of solution

### ISSUE THREAD

**Issue by abolfazl-sh** [jMetal/jMetal#365]
Hello,
does it possible to make a fixed numbers of solution in jmetal?
I know about set the population size, but for example if I set it to 1000 maybe it make less than 1000 because the algorithm doesn't found more. in other word I want make exactly 1000 and if the algorithm doesn't found this many bring the bad answers too.
does it possible?
(if any details needed let me know)

**Comment by ajnebro** [comment]
What algorithm are you using?. Most of evolutionary algorithms usually return a population full of individuals, but if the problem to be solved is highly constrained or some of its functions take a set of discrete values in a narrow range (e.g., an objective is the number of antennaes to be deployed and that number is in the range [1, 5]), you can get as a result a set containing unfeasible solutions or one with duplicated solutions, respectively.

**Comment by abolfazl-sh** [comment]
I am using NSGA-II.
thanks for the hint.
