### ISSUE TITLE
Problem with constraints for mono objective problems

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#370]
### INTRO

Hello my query is difficult to explain, but I will try to be as brief as possible :).
I am solving several problems in JMetal with Mono and Multiobjective algorithm.
The problem I have is with **the constraints for mono objective problems**. I will give as an example the KP problem, although this happens to me with the other problems and with different algorithms.

### THE ISSUE I HAVE
With the **MULTI-Objective executions** (NSGA for example)  the solutions that I obtain respects the restrictions  **_¡IS OK!_** (the solutions  don't exceed the maximum limit of the backpack), BUT with the **MONO-Objective executions** (with GA for example) the solutions don't respect the constraint (the solution exceeds the maximum limit of the backpack).

### TRYING TO SOLVE THE ISSUE

1. I use the same class of problem definition (I don't think the problem is in the problem definition), the methods evaluate evaluateConstraints are attached (they are the same for mono or multi-objective, the difference is that for mono objective I only evaluate one objective).

![image](https://user-images.githubusercontent.com/2429022/65682606-c6dbb500-e04a-11e9-8547-dd97f57d695a.png)

![image](https://user-images.githubusercontent.com/2429022/65682629-d1964a00-e04a-11e9-881f-14b067c1842d.png)

2. I thought that the difference may be that in JMetal the Multi-objective algorithms (NSGA) uses Hard and Constraints and Mono-objective (GA) uses Soft Constraints (solutions that violate the restriction are not ruled out. But in my case the restriction is very important to obtain feasible solutions.  So I did the following (not sure if it's correct)..

3. I have modified the following code (native of JMEtal), and with this I have solved the problem (
or so I think :) ), but I don't know if it is correct (I don't know if my modification respects the definition of a genetic algorithm)

![image](https://user-images.githubusercontent.com/2429022/65683157-18387400-e04c-11e9-9817-a416c10d0734.png)

In order to make the modification, I took inspiration from the method used in NSGA by JMetal

![image](https://user-images.githubusercontent.com/2429022/65682541-ac094080-e04a-11e9-8ea0-02cae2185fc3.png)

Please, if it has not been clear any concept of my query, ask me to clarify more.
Finally sorry to make such a long and messy query.

**Comment by ajnebro** [comment]
Hi.
  Have you tried to solved the constrained single-objective with NSGA-II?. The default approach for dealing with constraint is to penalize the infeasible solutions (we do not consider hard constraints).
  

Antonio

**Comment by TarasGit** [comment]
Hi, I used NSGA-II to solve the Next Release Problem for multivalue optimization (max profit, min costs). GA generated a bunch of infeasible solutions in each iteration.  My solutions was to go in each iteration through the generated reference front (current solutions set) and to remove all solutions which violate my min and max constraints.

**Comment by momah** [comment]
Thank you very very much @ajnebro and @TarasGit for your good and quick responses.

I just tested and effectively the NSGA produces solutions (feasible) that do not violate the restriction, but I need to solve it with a mono-objective algorithm for reasons related with my study.

**But, i still have the doubt that, why NSGA produces feasible solutions and GA produces infeasible solution (@ajnebro 's explanation was very clear, but why NSGA does and GA doesn't).**

Anyway, in my case then, I have two options:
1. Previous elimination: In the same method of evaluate(), check if the solution is not feasible and discard it.
2. Subsequent elimination: Do as proposed by @TarasGit

**Anyone have any suggestions/differences about these two options** and their possible effect on the performance of the algorithm.

Finally, someone has some explanation of **why GA has generated viable solutions with the modification that I have mentioned before** (using ranking and crowding distance).

![image](https://user-images.githubusercontent.com/2429022/65700466-48ddd500-e06f-11e9-82da-d5416ab95a0e.png)

Thank you very much everyone in advance.

**Comment by TarasGit** [comment]
Hi, concerning performance measured in time (algorithms executed with same amount of time): NSGA-II showed the second best quality of the reference front after Tabu Search > Ant  Colony > Simulated Annealing > Random Search (see attachment)
![MO](https://user-images.githubusercontent.com/5406878/65704753-628b1680-e087-11e9-9da6-a40a35ce7899.png)

**Comment by ajnebro** [comment]
> But, i still have the doubt that, why NSGA produces feasible solutions and GA produces infeasible solution (@ajnebro 's explanation was very clear, but why NSGA does and GA doesn't).

Thinking about this, the dominance test in NSGA-II checks the overall constraint violation degree, but the GenerationalGeneticAlgorithm uses as comparator the `ObjectiveComparator()`, which does not do that test. Just try to change that comparator by the `DominanceComparator()`.

**Comment by momah** [comment]
@ajnebro, thank you very much, this will solve my problem.
Thanks also to the contributions of @TarasGit
