### ISSUE TITLE
Could someone provide a simple genetic algorithm implementation using jMetal.

### ISSUE THREAD

**Issue by niksithari** [jMetal/jMetal#371]
For example
1. How to create the list of chromosomes?
2. When chromosomes are ready how to use operators like crossover and mutation?
3. How to set fitness function?
3. How to use then, the algorithms of jMetal like NSGA on the user problem?
All i need is a simple example (in java if possible)

**Comment by ajnebro** [comment]
Hi.
   You can find many examples in the jmetal-exec subproject. For example, in the case of NSGA-II: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/multiobjective/NSGAIIRunner.java

  Some of the issues you comment are described in the documentation site: https://github.com/jMetal/jMetalDocumentation. The documentation is not complete and some parts are outdated, so feel free to ask any question you have.


Antonio
