### ISSUE TITLE
BinaryTournamentSelection operator difference( with and without RankingAndCrowdingDistanceComparator)

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#372]
I have observed that some algorithms in JMetal use the **_BinaryTournamentSelection_** **with** **_RankingAndCrowdingDistanceComparator_** and others **without** this argument.

The two options are below..
What is the difference between using one or the other? Is it dependent on the algorithm's own definition?

```

1. selection = new BinaryTournamentSelection<BinarySolution>(new RankingAndCrowdingDistanceComparator<BinarySolution>());
2. selection = new BinaryTournamentSelection<BinarySolution>();

```

In my case, I am comparing algorithms and I need to know if this can affect the accuracy of the comparison.

Thanks in advance,

**Comment by matthieu-vergne** [comment]
@ajnebro please correct me if I am wrong in my reading of the operators.

Looking at the code, if you don't provide an argument, it uses by default a `DominanceComparator` which :
- compares solutions based on the their constraints violations
- if they are equivalent, compares their objectives (Pareto dominance)

`RankingAndCrowdingDistanceComparator` goes this way:
- compares their ranks, which seems to be about comparing their constraints, and if equivalent using the dominance comparator (which again compares their constraints and then compare their objectives)
- if equivalent, we use the `CrowdingDistanceComparator`, which considers solutions having more differences (in their objectives, not their genes) as better, to improve diversity in the population

In summary, and if I understand well, it seems that:
- the `BinaryTournamentSelection` without argument uses constraints then objectives to compare the solutions
- the `BinaryTournamentSelection` with `RankingAndCrowdingDistanceComparator` uses constraints then objectives *then diversity* to compare the solutions

We may think that comparing diversity of objectives after confirming that they are equivalent is useless, but it is not. Objectives are compared through Pareto comparisons: if both solutions have some objectives where they are better than the other, we cannot tell which solution is better, so we consider them as equivalent. Yet, their objectives are different, so we can compute their diversity.

So they appear to do the same thing, except that the second case go deeper in the comparison to further differentiate the solutions through their variety in objectives. Equivalent solutions in the first case may be ordered in the second. So you should consider that they may lead to different results when applied on the same algorithm.

**Comment by momah** [comment]
Thank you for this clear response.
