### ISSUE TITLE
IBEA, MOEAD and MOEADD on a PermutationSolution<Integer> problem

### ISSUE THREAD

**Issue by rodiecko** [jMetal/jMetal#374]
Hi,
I am using this framework in my research. One of my tasks is to experiment with NSGAII, IBEA, MOEAD and MOEADD. I create my problem like MultiobjectiveTSP and NSGAIITSPRunner, but I don't know how to adapt to others (IBEA, MOEAD and MOEADD) with PermutationSolution <Integer>. They are implemented for DoubleSolution. I would be grateful for any suggestions on how to adapt them to use PermutationSolution.

Sincerely.

**Comment by ajnebro** [comment]
Hi.
  The version of MOEA/D implemented in jMetal is MOEA/D-DE, which replaces the crossover operator of the original MOEA/D algorithm by differential evolution (DE). If you intend to solve a TSP-like problem you should replace then the DE component by a crossover. Concretely, the code to modify is between lines 59-66 of the https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/moead/MOEAD.java program:

``` java
59        List<DoubleSolution> parents = parentSelection(subProblemId, neighborType) ;
60
61        differentialEvolutionCrossover.setCurrentSolution(population.get(subProblemId));
62        List<DoubleSolution> children = differentialEvolutionCrossover.execute(parents);
63
64        DoubleSolution child = children.get(0) ;
65        mutationOperator.execute(child);
66        problem.evaluate(child);
```

The parent selection in line 59 returns three parents, being the last one the current individual (subProblemId). You could take from them the two parents needed by the crossover, which should be carried out next ( by replacing lines 61-62 by a call to the proper crossover object).

**Comment by ajnebro** [comment]
I have just refactored class IBEABuilder to allow configuring and creating an IBEA instance using any encoding.

**Comment by rodiecko** [comment]
Thanks to the whole team for their fast support and great tool.
