### ISSUE TITLE
Running programs from the command line with Maven

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#375]
Hello everyone,

Until now I was running my executions with eclipse ,but now I need to run my experiments from the command line.

_I know it's a very basic question, but I'm not very familiar with Maven._

**I just need to some basic test (some example of Jmetal) with maven from the command line to understand the basic operation of Running JMetal programs from the command line.**

The steps I follow are:

1. Install maven and configure the $PATH environment correctly.

![image](https://user-images.githubusercontent.com/2429022/68692062-bb960780-056c-11ea-8473-645f5e8ae5e6.png)

2. git clone https://github.com/jMetal/jMetal.git
3. cd jMetal

4. follow the steps of the jMetalDocumentation/compiling.md
* `mvn clean`: cleaning the project
* `mvn compile`: compiling
* `mvn test`: testing
* `mvn package`: compiling, testing, generating documentation, and packaging in jar files
* `mvn site`: generates a site for the project

> mvn clear (with error!)

![image](https://user-images.githubusercontent.com/2429022/68691736-22ff8780-056c-11ea-914a-d7528582a0af.png)

> mvn compile (with error!)

![image](https://user-images.githubusercontent.com/2429022/68691871-64903280-056c-11ea-85f2-f40c2175c150.png)

5. Visit the issue "Running programs from the command line" #98
Perform some test as :
```
export CLASSPATH=jmetal-core/target/classes/:jmetal-exec/target/classes/:jmetal-problem/target/classes/:jmetal-algorithm/target/classes/s/
```
```
java org.uma.jmetal.runner.multiobjective.SMPSORunner org.uma.jmetal.problem.multiobjective.Golinski
```
OR
```
`mvn -pl jmetal-exec exec:java -Dexec.mainClass="org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner" -Dexec.args="ALL jmetal-problem/src/test/resources/pareto_fronts/Kursawe.pf FUN.tsv"
```

 _Before creating the issue, I consulted the JMetal documentation and tried to look in other forums of the Maven issues, But without success_

**Can you tell me where I am failing or give me some clue or the basic steps to run a test from the console, please?**

**Comment by matthieu-vergne** [comment]
`mvn clean` -> you made a typo, you wrote `clear` instead of `clean`.

Your error at compile time is genuine. It seems someone was not rigorous enough and comitted something which does not compile.

You can go to the last release `jmetal-5.8`, which compiles:
```
git checkout jmetal-5.8
mvn clean compile
```
It is not the last one (it was released in July) but it should work.

**Comment by momah** [comment]
Thanks for the typo correction, now with jmetal-5.8 it seems that the compilation is going well, but when I run some runner, an error occurs that I attach below..

![image](https://user-images.githubusercontent.com/2429022/68722623-f66c5f80-05ad-11ea-9365-24dd7edaf018.png)

![image](https://user-images.githubusercontent.com/2429022/68722673-1c91ff80-05ae-11ea-8d04-3e198322237e.png)

![image](https://user-images.githubusercontent.com/2429022/68722716-3d5a5500-05ae-11ea-820a-8e03672f0d18.png)

![image](https://user-images.githubusercontent.com/2429022/68723371-4d733400-05b0-11ea-95cf-6aebca6a2ec5.png)

![image](https://user-images.githubusercontent.com/2429022/68723234-eb1a3380-05af-11ea-9adf-9a9bc8db8251.png)

![image](https://user-images.githubusercontent.com/2429022/68723262-fd946d00-05af-11ea-8252-efd5d81015ff.png)

![image](https://user-images.githubusercontent.com/2429022/68722951-059fdd00-05af-11ea-8877-aaf56e4bea4a.png)

![image](https://user-images.githubusercontent.com/2429022/68722837-a9d55400-05ae-11ea-9f92-2901fe7d1944.png)


**Is my execution of a main program correct? or I skipped some step?**
Execution example :
`mvn -pl jmetal-exec exec:java -Dexec.mainClass="org.uma.jmetal.runner.multiobjective.NSGAIIRunner"`

Thanks in advance,

**Comment by ajnebro** [comment]
Hi.
  Thanks for reporting that the project does not compile. I didn't realize that I made a wrong push on the master branch. I have just restored it.

  About running a jMetal program from the command line, after running 
```
mvn clean package

```

you can execute the following command in case you intend to run NSGA-II with the settings defined in the NSGAIIRunner.java program (replace "6.0" by "5.8" if you are using this last version):

```
java -cp .\jmetal-exec\target\jmetal-exec-6.0-SNAPSHOT-jar-with-dependencies.jar org.uma.jmetal.runner.multiobjective.NSGAIIRunner
```
and you should get the following output: 

```
2019-11-13 10:47:06.969 INFORMACIËN: Loggers configured with null [org.uma.jmetal.util.JMetalLogger configureLoggers]                              GAIIRunner
2019-11-13 10:47:07.005 INFORMACIËN: Total execution time: 467ms [org.uma.jmetal.runner.multiobjective.NSGAIIRunner main]
2019-11-13 10:47:07.038 INFORMACIËN: Random seed: 1573638426495 [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-11-13 10:47:07.039 INFORMACIËN: Objectives values have been written to file FUN.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-11-13 10:47:07.041 INFORMACIËN: Variables values have been written to file VAR.tsv [org.uma.jmetal.util.AbstractAlgorithmRunner printFinalSolutionSet]
2019-11-13 10:47:07.132 INFORMACIËN:
Hypervolume (N) : 0.659553874880981
Hypervolume     : 0.659553874880981
Epsilon (N)     : 0.01068073320706521
Epsilon         : 0.01068073320706521
GD (N)          : 2.507445351789875E-4
GD              : 2.507445351789875E-4
IGD (N)         : 1.7756205474971068E-4
IGD             : 1.7756205474971068E-4
IGD+ (N)        : 0.003743363906528522
IGD+            : 0.003743363906528522
Spread (N)      : 0.3460880649662701
Spread          : 0.3460880649662701
```

**Comment by momah** [comment]
thank you, it works perfectly.
I have also updated to Jmetal6.0
