### ISSUE TITLE
Can't run the jMatal experiment

### ISSUE THREAD

**Issue by guanzhu218** [jMetal/jMetal#381]
Hi, there

I am currently trying to learn the jMetal, however, the case study "BinaryProblemsStudy" can't run with the following error: "Exception in thread "main" org.uma.jmetal.util.JMetalException: Needed arguments111: experimentBaseDirectory
	at org.uma.jmetal.experiment.BinaryProblemsStudy.main(BinaryProblemsStudy.java:85)".
I am in the very beginning to learn this, please give me some help.

Thank you very much.

**Comment by ajnebro** [comment]
Hi.
  You need to add a parameter indicating a directory (called "experiment base directory" in the code) where the results generated will be stored.


Antonio

**Comment by guanzhu218** [comment]
Hi,

Thank you very much, what a stupid problem.

Yue
