### ISSUE TITLE
Error message when solving knapsack problem

### ISSUE THREAD

**Issue by guanzhu218** [jMetal/jMetal#385]
Hi all,

Thank you very much, I check the org code, it can't run, so I download the package again. Now it works. 

The other problem is I am following the code in problem "OneZeroMax" to creat my knapsack problem. And the problem, I have two objectives, I need to maximize one and minimize the other. 

Should I make them both minimize to apply in the "BinaryProblemStudy"? I found it minimize both objectives in OneZeroMax but not sure.

By the way, how can I check the compute time of each algorithm each run?

Best wishes,
Yue

**Comment by matthieu-vergne** [comment]
Did you try to run first the original `BinaryProblemsStudy`, without any modifications?

**Comment by matthieu-vergne** [comment]
If the original one works, then please share your code, so we can see what you changed and investigate.

If the original one does not work, then please share the exception you get with it.

**Comment by ajnebro** [comment]
Taking a look to the error messages, we can see this one: 

"Caused by: java.lang.AbstractMethodError: Receiver class org.uma.jmetal.problem.multiobjective.CCKP does not define or inherit an implementation of the resolved method abstract evaluate(Lorg/uma/jmetal/solution/Solution;)V of interface org.uma.jmetal.problem.Problem."

**Comment by guanzhu218** [comment]
Hi all,

**Comment by KenMak8** [comment]
Hi @guanzhu218 

I was wondering if you would be able to help with the implementation of the CCKP using NSGA-II using jMetal. 
If you're from the Univerisity of Adelaide, we may have had the same supervisor.

Would really appreciate it!

Thanks
