### ISSUE TITLE
MOEAD

### ISSUE THREAD

**Issue by 1017073490** [jMetal/jMetal#387]
Now, I have a problem needs to solved by MOEAD, which has been configured successfully by NSGA-II. But when I run this problem by MOEAD, it shows that "(org.uma.jmetal.problem.Problem<org.uma.jmetal.solution.IntegerSolution>) in MOEADBuilder can not be applied to (org.uma.jmetal.problem.Problem<org.uma.jmetal.solution.DoubleSolution>)"
How can i do?

**Comment by ajnebro** [comment]
Hi.
 The version of MOEA/D included in jMetal is MOEA/D-DE (DE: Differential Evolution), which is intented to be applied to continuous problems. There is no a version to deal with integer encoding.

  A solution could be to develop a Integer version of the DE operators, but I don't know if that makes sense.
