### ISSUE TITLE
Difference between MaxIterations and MaxEvaluations respect to algorithm comparisons

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#388]
Hi all,

My question is about the algorithm comparison conditions in JMetal, regarding the evaluations and  iterations.

More specifically, if I need to compare for example NSGA (which uses setMaxEvaluations) and SPEA2 (which uses setMaxIterations), how could I ensure that the comparison conditions are fair?

Here I show an example of JMetal.
![image](https://user-images.githubusercontent.com/2429022/71170233-a474c480-2252-11ea-905b-94b6de325456.png)

In order to fix the number of evaluations for all algorithms, Is there any way to know when SPEA2 performs a number of itations, how many evaluations are performed?

If the following relationship is correct..

>`Number of function evaluations = Number of iterations * Population Size`

> Every iteration of SPEA2, the evaluation function is called x number of times (once for each individual/solution).

So, for a fair comparison, could I do something similar?

![image](https://user-images.githubusercontent.com/2429022/71176234-51563e00-2261-11ea-8e8d-d73aebd126fa.png)

My question may include the answer, but it is to confirm that I did not make an incorrect comparison, thank you in advance.

**Comment by ajnebro** [comment]
The number of function evaluations in SPEA2 is numberOfIterations*populationSize, so if the population size is 100, 25000 evaluations in NSGA-II are equivalent to 250 iterations * 100 in SPEA2.

**Comment by momah** [comment]
Thank you very much,
momah
