### ISSUE TITLE
interface Replacement

### ISSUE THREAD

**Issue by dongzhiming** [jMetal/jMetal#391]
Hi, I think it is necessary to add an input parameter, _sizeOfTheResultingSolutionList_ , to the `replace` function below, so that the algorithm designer can operate more flexibly.

```
package org.uma.jmetal.component.replacement;

import org.uma.jmetal.solution.Solution;

import java.util.List;

@FunctionalInterface
public interface Replacement<S extends Solution<?>> {
  enum RemovalPolicy {sequential, oneShot}
  List<S> replace(List<S> currentList, List<S> offspringList) ;
}
```

**Comment by ajnebro** [comment]
Hi @dongzhiming.
  Thanks for your comment. That parameter is not included in the `replace()` method because it is not always needed (see for example the `RankingAndDensityEstimatorReplacement()` class) and anyway it can be a parameter of the constructor of the replacement class (as done in class `MOEADReplacement()`). 

  If you find a situation where this last approach does not work, please let me know.


Antonio

**Comment by dongzhiming** [comment]
Hi @ajnebro 
Thank you very much for your reply. When I implemented an algorithm, I used the `RankingAndDensityEstimatorReplacement()` class, and the `sizeOfTheResultingSolutionList` and `currentList.size()` are not the same, so I think it is more convenient to add an input parameter to the `replace()` method. Of course, I can also write a `RankingAndDensityEstimatorReplacementPlus()` class and add a parameter of the constructor. Thanks again.

**Comment by ajnebro** [comment]
I see the issue. The point is that I'm assuming the default case in which the size of the population in the next generation is the same as the size of the population passed as the first parameter to the `replace()` method. 

Adding the parameter you need to the `RankingAndDensityEstimatorReplacement() is easy; just let me think about it. On the one hand, I dislike needing to add classes such as the one you mention but, on the other hand, I don't want to make the existing class more complex than necessary.

**Comment by matthieu-vergne** [comment]
Actually, you don"t even need a class. `Replacement` is a functional interface, so just use a lambda. I am not sure about how you use case looks like, but if it is about taking the n first solutions, then you can create a `Replacement` on the fly like that:
```java
static <S extends Solution<?>> Replacement<S> bound(Replacement<S> replacement, int n) {
  return (current, offspring) -> replacement.replace(current, offspring).subList(0, n);
}
```

**Comment by dongzhiming** [comment]
@matthieu-vergne 
The solution you proposed can indeed solve my current problem, but there is a risk that not all fronts pass through `densityEstimator.sort()` method regardless of the `oneShotTruncation()` method or the `sequentialTruncation()` method, which may cause some deviations. For example, let `subFront(0) = 4`, `subFront(1) = 6`, and when the needed solution set size` n = 3`, the elements of `subList(0,n)` are all derived from `subFront(0)` and are not sorted. In this case, the role of the `densityEstimator` is lost.
The reason I encountered this problem was that I wanted to transfer some individuals from the other population to the current population and participate in reproduction through transfer learning, but the size of the current population of the next generation could not be changed. That's why the question above is raised. Most people may not have this need.

**Comment by matthieu-vergne** [comment]
I am not familiar with your particular needs and I don't try to solve them. I only wanted to mention that if you can use an existing replacement operator and just add a bit of code around it to do what you want, you can easily make it a new replacement operator through lambdas, without changing anything to the interface.

If you cannot build on an existing one, then you need to make your own implementation, but if it is really simple you can again make it with a lambda. If you want to reuse it elsewhere, a class may be useful.

But in any case, changing a *generic* interface/class to satisfy a *specific* need is a code smell, not a solution.

**Comment by matthieu-vergne** [comment]
If the issue is about the whole algorithm not being suited to a population with a dynamic size, that is another matter which goes beyond this replacement operator. Because it is about the hypotheses the algorithm builds upon. In this case, one should investigate the algorithm to see if it can be generalized on this aspect. If the replacement interface is dedicated to this algorithm, it may change depending on the evolution of the algorithm.

**Comment by dongzhiming** [comment]
Ok, I see. Thank you very much for your constructive comments.
