### ISSUE TITLE
Is proposed SMPSO algorithm an unconstrained multi-objective optimization?

### ISSUE THREAD

**Issue by 3threeFX** [jMetal/jMetal#397]
Hi friends,
First of all thanks for this great job and second unfortunately I have an issue with SMPSO algorithm ... also I have to tell that I'm using .Net package (v4.5 -> that Obviously is not java based & also I know that it discontinued but I have to use it ! ) ...
Anyway I need to know that Is Speed-constrained Multi-objective PSO (known as SMPSO) an unconstrained multi-objective optimization? or not ?

P.S: I read the original paper (SMPSO: A New PSO Meta-heuristic for Multi-objective Optimization) and It's used for unconstrained benchmark problems like ZD1-6 & DTLZ1-7  And there's no point in using this algorithm in constrained issues ... (unless I'm mistaken)
Also I checked the c# code (jmetal\JMetalCSharp\Metaheuristics\SMPSO\SMPSO.cs) and there is a line for Problem.EvaluateConstraints(particle) :

```c#
//Evaluate the new particles in new positions
		for (int i = 0; i < particles.Size(); i++)
		{
			Solution particle = particles.Get(i);
			this.Problem.Evaluate(particle);
			this.Problem.EvaluateConstraints(particle);
		}
```

but indeed it seems there's no limitation in adherence to restrictions because I used it for my constrained problem and Obviously algorithm doesn't' care about the constrain at all ! ( Feasibility Ratio approximately 16% for SMPSO compare to 70% and 80% for NSGA-II or SPEA2 !) 

By the way , any hints and helps are acceptable :)) thanks a lot

Sincerely Yours,
Max

**Comment by matthieu-vergne** [comment]
Since it is about the semantic of the algorithm, I will let that to @ajnebro.

**Comment by 3threeFX** [comment]
@matthieu-vergne  thanks for your quick response ... mean while we wait for @ajnebro , I want to explain what I did:
I believe 3 main methods can Implemented for constrained problem : 1) use penalty function 2) convert constrain to objective function 3) co-evolutionary methods
The first and second options are easy to implement so I try to use an additive penalty function also in another try add new obj function for my constrain based my violation concept and results ==> none of them work fine !! feasibility ratio is the same 15% ... Therefore, I considered the possibility of something else ... 

I checked concept of SMPSO algorithm and especially velocity values of particles and I faced weird things ... my variable lower limits is 10 and upper bounds is 990 for three dimensional direct (x,y,z) and 0to6 for rotation (r) =>x1,y1,z1,r1, x2,y2,z2,r2 , ... , xn,yn,zn,rn

![2020-04-10_20-33-14](https://user-images.githubusercontent.com/63404512/79005984-596a1e80-7b6d-11ea-8bec-14a9c2e7f337.jpg)
lower and upper bounds of my problem

as you seen in beneath image the velocity is changing very sharp(+490 or -490 ! half of distance between lower and upper bounds ) and not smooth move at all ... Think of a particle going through half the variable space in an instant !  As a result, the particles are thrown around very quickly ...

![3](https://user-images.githubusercontent.com/63404512/79006319-24aa9700-7b6e-11ea-9636-7d8c8ad90137.jpg)
speed array -->example  particle 3 

![10](https://user-images.githubusercontent.com/63404512/79006338-2f652c00-7b6e-11ea-8929-f38705a66d03.jpg)
speed array -->example  particle 10 

![19](https://user-images.githubusercontent.com/63404512/79006357-39872a80-7b6e-11ea-9715-4d3aa8c788a6.jpg)
speed array -->example  particle 19 

I believe Solving this problem is closely related to controlling the rate of change speed change  ... many particles want go outside of the variable limitation boundary and just hold on edge of var space ! 
it seems somehow many times velocity calculated is greater than delta ([upper bound - lower bound]/2) or less than -delta

![2020-04-10_21-26-09](https://user-images.githubusercontent.com/63404512/79008451-ae5c6380-7b72-11ea-9b83-56b716acb921.jpg)
original paper equations for speed constrain mechanism

![2020-04-10_20-46-19](https://user-images.githubusercontent.com/63404512/79006942-66880d00-7b6f-11ea-9475-795d63165806.jpg)
default parameters bios

finally what do you think guys ?? am I wrong ? or not ? 
why speed changes fast ? Is this common?

**Comment by ajnebro** [comment]
Hi.
  The anwswer is yes: SMPSO can be used to solve constrained problems. 

  How?. It uses a dominance comparator when updating particles' memory, and that comparator takes into consideration the overall constraint violation:

```java
public class DominanceComparator<S extends Solution<?>> implements Comparator<S>
  ...
  public int compare(S solution1, S solution2) {
    ...
    int result;
    result = constraintViolationComparator.compare(solution1, solution2);
    if (result == 0) {
      result = dominanceTest(solution1, solution2);
    }

    return result;
  }
```

You can take a look to the documentation about constraint handling in the current development version of jMetal here: https://jmetal.readthedocs.io/en/latest/constraints.html

If something is unclear, please let me know.

**Comment by 3threeFX** [comment]
first of all @ajnebro thanks for your response ... I checked and realized that the leader is picked up from non-dominated feasible solutions that's you said and it's correct but it's performance in finding feasible solutions is much lower than others algorithms I used before for this problem (compare to NSGA-II , ssNSGA-II , SPEA2 )
so my problem still remain unsolved ... 
I try to tune the Learning Personal and Global best (selected from leaders) parameters (C1,C2) and Inertia weight (w) to solve the case but I haven't achieved better answers  ... in mean time I want to share some suggestions that might helpful (or not :) ) :

1) In  [updateVelocity()](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/smpso/SMPSO.java#L244) function I think it's correct to generate random number r1,r2 for each var elements something like this : (if I'm not wrong I read a PSO book from one of Kennedy's student that told random number must be generated for all components so I urge you to review this section if it's possible for you and if you have time for this)

```
protected void updateVelocity(List<DoubleSolution> swarm) {
    double r1, r2, c1, c2;
    double wmax, wmin;
    DoubleSolution bestGlobal;

    for (int i = 0; i < swarm.size(); i++) {
      DoubleSolution particle = (DoubleSolution) swarm.get(i).copy();
      DoubleSolution bestParticle = (DoubleSolution) localBest.getAttribute(swarm.get(i)).copy();

      bestGlobal = selectGlobalBest();

       //*** Move randomGenerator for r1,r2 from here to down side ***

      c1 = randomGenerator.nextDouble(c1Min, c1Max);
      c2 = randomGenerator.nextDouble(c2Min, c2Max);
      wmax = weightMax;
      wmin = weightMin;

      for (int var = 0; var < particle.getNumberOfVariables(); var++) {
      //*** Move randomGenerator for r1,r2 to here in the loop ***
      r1 = randomGenerator.nextDouble(r1Min, r1Max);
      r2 = randomGenerator.nextDouble(r2Min, r2Max);

        speed[i][var] =
                velocityConstriction(
                        constrictionCoefficient(c1, c2)
                                * (weightMax * speed[i][var]
                                + c1 * r1 * (bestParticle.getVariable(var) - particle.getVariable(var))
                                + c2 * r2 * (bestGlobal.getVariable(var) - particle.getVariable(var))),
                        deltaMax,
                        deltaMin,
                        var);
      }
    }
```

2) In original paper (SMPSO: A New PSO Meta-heuristic for Multi-objective Optimization) the Khi is define with below equation : 

![Capture](https://user-images.githubusercontent.com/63404512/79037495-da193100-7be6-11ea-81e4-91f1baffe669.PNG)


based on (The Particle Swarm—Explosion, Stability, and Convergence in a Multidimensional Complex Space , Maurice Clerc and James Kennedy) if we choose for example optimum Phi1=Phi2 = 2.05 => Phi = 4.1 => Khi = -0.7298 
what's the point of negative constriction Coefficient ?? it reverse the direction of movement result's vector is derived (from three components)  ... 

in original code the constriction Coefficient for Phi > 4 is :  (rho = Phi = Phi1+Phi2)
`Khi =2 / (2 - rho - Math.sqrt(Math.pow(rho, 2.0) - 4.0 * rho))`

but it isn't better to choose below equation ? 

`Khi =2 / (rho - 2 + Math.sqrt(Math.pow(rho, 2.0) - 4.0 * rho)) `

that returns positive value for  Khi = +0.7298 for  Phi1=Phi2 = 2.05 that means speed vector still In the direction of the vector of last inertia and best practice and global best ...

it might be I'm wrong (badly wrong lol :)) In that case, I apologize for taking your time to review the code ) but I think it's better to tell you these suggestions .

**Comment by 3threeFX** [comment]
In the latter case of my previous comment about negative values of  constrictionCoefficient(c1, c2) I think something like this happen might happen respect to [updateVelocity()](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/smpso/SMPSO.java#L263) :

![llustration-of-the-PSO-velocity-calculation](https://user-images.githubusercontent.com/63404512/79052277-82acac80-7c4a-11ea-9f92-f62bd7abddec.png)

some negative return values from  [constrictionCoefficient(c1, c2)](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/smpso/SMPSO.java#L364)  :

![1](https://user-images.githubusercontent.com/63404512/79052321-e6cf7080-7c4a-11ea-9da9-8606ac1722fe.jpg)
![2](https://user-images.githubusercontent.com/63404512/79052324-eafb8e00-7c4a-11ea-872b-497419b7095f.jpg)
![3](https://user-images.githubusercontent.com/63404512/79052325-ecc55180-7c4a-11ea-8466-28bb57c6f54b.jpg)
![4](https://user-images.githubusercontent.com/63404512/79052326-f058d880-7c4a-11ea-8ee2-712fcfa49360.jpg)

**Comment by ajnebro** [comment]
@3threeFX , sorry for not responding to your messages. I have not forgotten that, but this week is complicated to me and I have time to take a look at them.

**Comment by 3threeFX** [comment]
> 
> 
> @3threeFX , sorry for not responding to your messages. I have not forgotten that, but this week is complicated to me and I have time to take a look at them.

Thanks for your reply Antonio ... I will be waiting for your response

**Comment by ajnebro** [comment]
When designing SMPSO I remember we had to do a lot pilot tests trying to find a proper parameter configuration.

> In updateVelocity() function I think it's correct to generate random number r1,r2 for each var elements in all dimension something like below code ... ( it mentioned in "particle swarm optimization" book , Maurice Clerc 2006 --> 3.2. Two common errors --> page 44 ... e.g. in Matlab implementation using rand(VariableSize) instead of using rand )

I just have made a version of SMPSO with this change and compared it with the original algorithm. By using the ZDT benchmark problems, in all the cases the original SMPSO outperforms the other one. For example, this table shows the hypervolume values:

<img width="367" alt="imagen" src="https://user-images.githubusercontent.com/1889196/81089140-43e1dd80-8efc-11ea-8aad-b640754e3303.png">

**Comment by ajnebro** [comment]
> In original paper (SMPSO: A New PSO Meta-heuristic for Multi-objective Optimization) the Chi is define with below equation :

You are right in that the equation we use is not same. As I mentioned before, we try a lot configurations and we ended up with the current one. We found out that when the particles reached out of the valid ranges of the variables, the best strategy was to reverse the direction.
