### ISSUE TITLE
.dat file jmetal

### ISSUE THREAD

**Issue by shahbanovirk** [jMetal/jMetal#409]
Hello there!
Facing an issue  in generating and locating front file with extension of .dat  while running "NSGAIIComputingReferenceParetoFrontsStudy,java" file.
Please guide me how to generate these .dat files.

**Comment by matthieu-vergne** [comment]
I cannot find this class. Is it from jMetal 4?

**Comment by matthieu-vergne** [comment]
Seems I wasn't up to date.

**Comment by shahbanovirk** [comment]
its in jMetal 6

**Comment by matthieu-vergne** [comment]
6 is not out yet, currently thinking about it. This is still in the lab submodule.

**Comment by matthieu-vergne** [comment]
Looks like a bug to me. It generates CSV files but try to read DAT files. Of course it won't find them.

Since I am not familiar with the experiment stuff I cannot be sure that it is the right thing to do, but changing `GenerateReferenceParetoSetAndFrontFromDoubleSolutions.getNonDominatedSolutions()` at least allowed me to run the whole stuff. If you can change this code, just replace the ".dat" extensions by ".csv" for both `frontFileName` and `paretoSetFileName`. I will let @ajnebro confirm and fix, though.

**Comment by matthieu-vergne** [comment]
Just created a PR on my fix attempt.

**Comment by shahbanovirk** [comment]
@matthieu-vergne 
The changes you suggested has worked for me.Thankyou so much for your help and quick response and sorry about  creating confusion regarding jMetal version.

**Comment by shahbanovirk** [comment]
@matthieu-vergne  I am also facing another issue in creating weight file  for  my problem with 4 objectives for MOEA/d
Could you please help in resolving this issue as well.

**Comment by ajnebro** [comment]
Which is the issue about the 4 objective weight file? Creating the file?

**Comment by shahbanovirk** [comment]
Hi @ajnebro ! Whenever I run Moea/D  it throws file not found exception for file W4D_300.dat. 
Please guide me that how to locate or generate that file.

**Comment by matthieu-vergne** [comment]
When you have exceptions, please share the full exception stack. It tells us exactly where it fails and help to fix.

**Comment by ajnebro** [comment]
Properly defining weight files is a hot research topic. Anyway, I have generated a file for 4 objective problems: https://github.com/jMetal/jMetal/blob/master/resources/weightVectorFiles/moead/W4D_165.dat

This is outside my area of research, so please check to see if the file is correct.

**Comment by shahbanovirk** [comment]
Thank you so much @ajnebro  for  your help.
