### ISSUE TITLE
Implementing a constrained problem using Tanaka.java as a template

### ISSUE THREAD

**Issue by KenMak8** [jMetal/jMetal#417]
Hello,

I'm trying to implement a variant of a constrained problem. Would anyone be able to break down the Tanaka problem from a coding perspective so I can better understand how the constrained problem interface works? 

Thank you!

**Comment by ajnebro** [comment]
Just take a look to this page: https://jmetal.readthedocs.io/en/latest/constraints.html

**Comment by KenMak8** [comment]
Thank you very much @ajnebro 

I just have a couple more questions to clarify my understanding, if you have the time.

If I wanted to define a bound (weight constraint) where exactly would I put this value? 

Where can I input the data set for the variable values (e.g value per item and weight per item)

In the "evaluate"  method of the Srinivas problem, is this what happens?
                   - array f is initialised with space for 2 double values
                   - x1 and x2 are initialised as the x and y values for an individual solution
                   - what does f[0] and f[1] do?
                   - what does solution.setObjective() do?
                   - the solution object is sent to the evaluate constraints class to determine if any violations occur

In the "evaluateConstraints" method of the Srinivas problem, is this what happens?
                   - array "constraint" is initialised with space for 2 double values
                   - x1 and x2 are initialised as the x and y values for an individual solution
                   - what does constraint[0] and constraint[1] do, they look like values the solution must be constrained by
                   - the constraint is passed to the solution for evaluation
