### ISSUE TITLE
Automatic Configuration of NSGA-II Algorithm with jMetal and Irace

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#419]
Hello, I hope all is well,

My queries are about using irace to tunning algorithm parameters. I have seen that jMetal has incorporated some classes to work with irace which I think is a great idea, but I do not understand how it works very well.

My queries:
1. How does irace work with jMetal, how can irace access the jMetal algorithms? Or is it that irace has its own algorithms (NSGA-II, ..)
2. I see that jMetal helps to automatically generate the input file for irace, but does this file have to be exported outside to use with irace independently of jMetal from Eclipse?
3. I think it is necessary to install irace first, but can we tune the problem parameters with algorithms with jMetal from eclipse? If there is a document with the basic steps I would appreciate it 

I have consulted and the paper "Automatic Configuration of NSGA-II with jMetal and irace" and the irace manual, but I need 
the general concept of the operation of the tool and basic steps and since I have no prior knowledge of Irace.
Thanks in advance.

**Comment by ajnebro** [comment]
There is a documentation page about this matter: https://jmetal.readthedocs.io/en/latest/autoconfiguration.html

Please, feel free to contact me if something is not clear or you have any suggestion.
