### ISSUE TITLE
Integer Double Problem

### ISSUE THREAD

**Issue by NicuUlb** [jMetal/jMetal#429]
Hi,
I'm trying to use jMetal for an optimization problem which has individuals whose chromosomes are constructed of both Double and Integer genes. I would like to use NSGAII to obtain some results, but as far as I searched, the support for such problems seems not to be uniform (there seems to be a IntegerDoubleSolution, but there is no IntegerDoubleProblem). Could you please give me some hints on how to bypass this issue?

**Comment by ajnebro** [comment]
The IntegerDoubleSolution class is deprecated. I replaced it by a generic [`CompositeSolution`](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/solution/compositesolution/CompositeSolution.java) class, which is a contaner of solutions.

You can find an example here: https://github.com/jMetal/jMetal/blob/master/jmetal-experimental/src/main/java/org/uma/jmetal/experimental/componentbasedalgorithm/example/multiobjective/nsgaii/NSGAIIWithMixedSolutionEncodingExample.java

The problem used in that example is defined here: https://github.com/jMetal/jMetal/blob/d48c664bf90c57d9e6800ce1c45534fd577a475a/jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/MixedIntegerDoubleProblem.java

Just take into account that I have never used the `CompositeSolution` in any research work. If you try it and something does not work properly, please contact me.

**Comment by NicuUlb** [comment]
Thank you for the resources, they were very helpful and I managed to adapt them to my problem. I especially like the plot of the Pareto front. My last issue is that the evaluation function takes very long to complete, and I was wondering if I could evaluate multiple solutions in parallel, while still keeping the live plotting of the solutions. Is this possible?

**Comment by ajnebro** [comment]
Just take a look to this page: https://jmetal.readthedocs.io/en/latest/parallel.html

**Comment by geniusyko** [comment]
How can I mix variables of different types or how can I set which varibles are discrete and which are contiguous like
[0, 1, 0, 2, 1.2, 0.2, 3.6, 1.5] the first four columns are discrete values and the last four columns are continuous values?
