### ISSUE TITLE
Which version of jMetal is correct about HV calculation ?

### ISSUE THREAD

**Issue by zzdzzdzzdzzd** [jMetal/jMetal#430]
The same experiment : NSGAIII   DTLZ1 with 3 objectives

Jmetal 5.6: HV = 1.12
Jmetal 5.10: HV = 0.79

Is PISAHypervolume class changed?

Thanks!

**Comment by matthieu-vergne** [comment]
The file has been moved to another package and has received a new constructor. Beside that, there is only code formatting changes. You can check that by comparing the two files in the two versions:
```
git diff --ignore-all-space \
  jmetal-5.6:jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/PISAHypervolume.java \
  jmetal-5.10:jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/hypervolume/impl/PISAHypervolume.java
```
The difference of HV probably comes from somewhere else.
