### ISSUE TITLE
dominanceTest method in DominanceComparator class

### ISSUE THREAD

**Issue by Cr0wax** [jMetal/jMetal#431]
Seems like there is an error in during evaluation of dominance between solution - in current code, dominant is the solution with better value on last objective.
Look at the evaluation loop in dominanceTest:
```
for (int i = 0; i < solution1.getNumberOfObjectives(); i++) {
      double value1 = solution1.getObjective(i);
      double value2 = solution2.getObjective(i);
      if (value1 != value2) {
        if (value1 < value2) {
          bestIsOne = 1;
        }
        if (value2 < value1) {
          bestIsTwo = 1;
        }
      }
    }
```

The right code should increment values of _bestIsOne_ and _bestIsTwo_ during the loop, not just assign 1.

**Comment by ajnebro** [comment]
This code is widely used and an incorrect implementation would led to unexpected results. Anyway, that doesn't mean that it has to be bug-free.

Could you give an example showing that it is wrong?.  As I see it, it works properly.

**Comment by Cr0wax** [comment]
Sorry, my bad. It works as supposed. I go through the code again. Using the incrementations will produce a dominated solution for nondominated ones.
