### ISSUE TITLE
Wrong path in an example RNSGAIIWithChartsRunner.java

### ISSUE THREAD

**Issue by TianYuanSX** [jMetal/jMetal#432]
In class `jmetal-example\src\main\java\org\uma\jmetal\example\multiobjective\nsgaii\RNSGAIIWithChartsRunner.java`

The default path of PF (line 78) should be "resources/referenceFrontsCSV/ZDT1.csv" but not "resources/referenceFrontsCSV/ZDT1.pf".

Please fix this issue in future version.

`    String referenceParetoFront = "resources/referenceFrontsCSV/ZDT1.csv" ;

    String problemName ;
    if (args.length == 1) {
      problemName = args[0];
    } else if (args.length == 2) {
      problemName = args[0] ;
      referenceParetoFront = args[1] ;
    } else {
      problemName = "org.uma.jmetal.problem.multiobjective.zdt.ZDT1";
      referenceParetoFront = "resources/referenceFrontsCSV/ZDT1.pf" ; -> "resources/referenceFrontsCSV/ZDT1.csv"
    }`

**Comment by matthieu-vergne** [comment]
I don't know whether it is correct (I let @ajnebro check that).
But for the sake of information, you can directly go to the file on Github and edit it:
![image](https://user-images.githubusercontent.com/1774210/105610922-99c02380-5db2-11eb-9d96-f6eab064655b.png)
It will create a fork with the change and a pull request to integrate it.
I believe it is faster than writing a full description.
Additionally, the change can directly be reviewed and merged, which creates a commit with your name.

**Comment by ajnebro** [comment]
Fixed.
