### ISSUE TITLE
Maven Versioning: beta vs. snapshots

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#44]
Regarding the distribution of jMetal through the Maven central repository, maybe you should consider snapshots instead of beta-dedicated versions. At least, snapshots are intended for the non-stable releases, so you can just redeploy them at any time without changing the version (typically 5.0-SNAPSHOT here) and each snapshot version is kept, so you can refer to a specific snapshot deployed at a specific time (they are stored on the repo with timestamps). The deployment can be performed easily with Maven for both snapshots and stable release:

Snapshot:
- mvn install
- mvn deploy

Release:
- mvn install
- mvn release:prepare
- mvn release:perform
- Validate releases on Sonatype website

When doing the release, it automatically remove the "-SNAPSHOT", commit on Github and pass to the next version and add "-SNAPSHOT". It also manages the dependencies between the modules.

**Comment by ajnebro** [comment]
Thanks for the advice :)
