### ISSUE TITLE
the normalized hypervolume indicator

### ISSUE THREAD

**Issue by MidouDali** [jMetal/jMetal#448]
Hi,
I have a question about the normalized hypervolume indicator. I read in the comments that it is calculated as follows: relative hypervolume = 1 - (HV of the front / HV of the reference front).
Can you tell me please about the reference of this indicator in order to know its definition and its equation.
thank you

**Comment by ajnebro** [comment]
There is not a reference for this indicator, as it consists in a simple formula. For the hypervolume, the implementation in jMetal is based on E. TZitzler's implementation (E. Zitzler, L. Thiele, M. Laumanns, C. M. Foneseca, and V. Grunert da Fonseca. Performance assessment of multiobjective optimizers: An analysis and review. IEEE Transactions on Evolutionary Computation, 7(2):117–132, 2003.").

**Comment by MidouDali** [comment]
thank you,
does it mean that a better algorithm must have low values of this indicator (the normalized hypervolume indicator)?

**Comment by ajnebro** [comment]
The normalized HV should return a value between zero (best indicator value) and one (worst value)

**Comment by MidouDali** [comment]
Thank you,
Can you explain the generalized spread metric please and tell me about its reference?
