### ISSUE TITLE
Can you provide a simple tutorial case for beginners in the newest version

### ISSUE THREAD

**Issue by GuotongWu** [jMetal/jMetal#458]
I'm a beginner for Jmetal. However, I find it's difficult for me to understand the  [newest document](https://jmetal.readthedocs.io/en/latest/about.html). What I need is just a simple case turtorial instead of  mastering the detailed usage of each package. And I read the [older document version](https://jmetal-doc.readthedocs.io/en/latest/), which illustrate how to run a algorithm using IDE and command line respectively. It seems the older one is more friendly for beginners.

**Comment by ajnebro** [comment]
Hi.
  I plan to update the documentation in https://jmetal.readthedocs.io; I will have in mind your comment. Anyway, the getting started guide in https://jmetal-doc.readthedocs.io/en/latest/documentation.html, although has some outdated sections, should be enough to start with. 

  If you intend to use some of the algorithms included in jMetal to optimize a problem, you have many examples in https://github.com/jMetal/jMetal/tree/main/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/examples and in https://github.com/jMetal/jMetal/tree/main/jmetal-component/src/main/java/org/uma/jmetal/component/examples  

  Feel free to contact me if you have any question about how to use jMetal.

**Comment by GuotongWu** [comment]
Thank you for your great contribution to the community and timely response! I have leared a lot with your instruction
