### ISSUE TITLE
Occasional test failure

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#89]
Notice that I have a test which tends to fail sometimes in `jmetal-algorithm`:
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 28.782 sec <<< FAILURE! - in org.uma.jmetal.algorithm.multiobjective.smsemoa.SMSEMOAIT
shouldTheHypervolumeHaveAMininumValue(org.uma.jmetal.algorithm.multiobjective.smsemoa.SMSEMOAIT)  Time elapsed: 8.301 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.uma.jmetal.algorithm.multiobjective.smsemoa.SMSEMOAIT.shouldTheHypervolumeHaveAMininumValue(SMSEMOAIT.java:93)
```

In general it passes, but sometimes it fails.

**Comment by ajnebro** [comment]
Yes, I'm aware of that. 

I have to revise why that happens.

**Comment by matthieu-vergne** [comment]
Did you solve it?

**Comment by ajnebro** [comment]
No and yes. The test was based on solving problem ZDT4, which is difficult to many algorithms, and measuring the quality of the found front by applying the hypervolume quality indicator. If the algorithm is consistent, it should always return a hypervolume greater than the value used in the test, but it is clear that SMS-EMOA sometimes do not achieve such a level.

I have changed ZTD4 by ZDT1, which is a simpler problem.

**Comment by matthieu-vergne** [comment]
I was scared that you were closing issues because they are just old. {'^_^}

**Comment by ajnebro** [comment]
xDDD. Definitely I'm not doing that ;)

Just closing some issues that doesn't seem important right now.
