### ISSUE TITLE
Multiple runs of NSGA-II with ExperimentRunner class

### ISSUE THREAD

**Issue by mrkcse** [jMetal/jMetal#94]
How can I execute multiple runs with the ExperimentRunner class. Can you please give an example for the NSGA-II class. The following code does not work and two of the lines are disabled.  How to pass the algorithm list and problem list to make it working?

.......................................................................................
import java.awt.List;
import java.io.IOException;
import java.util.Arrays;

public class ExperimentRunner {
  public static void main(String[] args) throws JMetalException, IOException {

    ExperimentConfiguration<?> configuration =     		
    		 new ExperimentConfigurationBuilder<Solution<?>>("Experiment")           
          		
    //  .setAlgorithmList(Arrays.asList("NSGAII", "SMPSO", "MOCell", "GDE3"))
    //  .setProblemList(Arrays.asList("ZDT1", "ZDT2", "ZDT3", "ZDT4", "ZDT6"))
      .setExperimentBaseDirectory("/Users/antelverde/Softw/jMetal/jMetalGitHub/pruebas")
      .setOutputParetoFrontFileName("FUN")
      .setOutputParetoSetFileName("VAR")
      .setIndependentRuns(4)
      .build() ;

    ExperimentalStudy study = new ExperimentalStudy.Builder(configuration)
      .build() ;

    study.run();
  }
}

**Comment by ajnebro** [comment]
Hi.
 This class belongs to an incomplete feature: the support for making experimental studies in jMetal5.0.

 It is not usable now.
