### ISSUE TITLE
New features to include in jMetal 5.1

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#95]
This issue is intended to have a todo list with those features that will not be included in jMetal 5.0.
- [x] Manage experiments in a generic way
- https://github.com/jMetal/jMetal/tree/Version5.1/jmetal-core/src/main/java/org/uma/jmetal/util/experiment
- https://github.com/jMetal/jMetal/tree/Version5.1/jmetal-exec/src/main/java/org/uma/jmetal/experiment
- https://github.com/jMetal/jMetal/blob/Version5.1/jmetal-core/src/main/java/org/uma/jmetal/util/parallel/impl/MultithreadedExperimentExecutor.java
- [ ] Retrieve available indicators in a simple way
- [ ] Retrieve available algorithms in a simple way
- [ ] Retrieve available operators in a simple way
- [x] Include algorithm NSGA-III
- [x] Include algorithm MOCHC 
- [x] Include algorithm SMPSOhv
- [ ] Include all the variants of MOCell (only one is available)
- [ ] Include the multithreaded variant MOEA/D
- [ ] Add classes for managing parameters
- https://github.com/jMetal/jMetal/tree/jmetal-5.1/jmetal-core/src/main/java/org/uma/jmetal/parameter
- [ ] Rethink the `Solution` interface
- https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/solution/Solution.java

**Comment by matthieu-vergne** [comment]
You can edit your post to put (with a space between the square brackets):
```
- [ ] Manage experiments in a generic way
- [ ] Retrieve available indicators in a simple way
- [ ] Retrieve available algorithms in a simple way
- [ ] Retrieve available operators in a simple way
```

**Comment by matthieu-vergne** [comment]
OK, you know, so just add the items. {^_^}

**Comment by matthieu-vergne** [comment]
The links are dead (replace `Version5.1` by `jmetal-5.1`).

Regarding the parameters, should I redo a pull request about it?
