### ISSUE TITLE
release time of the newest version of jMetal on sourceforge

### ISSUE THREAD

**Issue by mina111** [jMetal/jMetal#96]
Hi,

May I ask when will you release the latest version of jMetal on http://jmetal.sourceforge.net/? Or you will only publish the code on GitHub?
Today when I open that website, it gives a warning: The sourceforge.net website is temporarily in static offline mode. Only a very limited set of project pages are available until the main website returns to service.

Thanks,
Wenwen

**Comment by ajnebro** [comment]
Dear Wenwen.
  Thanks for reporting that the jMetal web site in SF is out. Anyway, if you are interested in the source code of jMetal 4.5 you can find it in GitHub: https://github.com/jMetal/jMetal/tree/version4.5

  The plan for the new release is to provide also de source code in SF, but the development version will remain in GitHub.

**Comment by ajnebro** [comment]
The download page is still up: https://sourceforge.net/projects/jmetal/

**Comment by matthieu-vergne** [comment]
It seems that Sourceforge had [a big issue on July 17th](http://sourceforge.net/blog/) (4 days ago) and that they are still working on it, with only a few services back (e.g. downloads).

**Comment by mina111** [comment]
Hi both,

Thank you for the download link. It seems the issue of SF hasn't been fixed yet. Anyway, the download works which is good to me. :)

Thanks,
Wenwen
