### ISSUE TITLE
Running programs from the command line

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#98]
When invoking jMetal programs from the command line I always have use de `java` command. My development machine is a MacBook, but I also have access to a Linux one and to a virtual machine with Windows 8.1 (with GitBash installed) to make some tests.

In the case of jMetal 5.0, I set first the `CLASSPATH` environment variable:
```
export CLASSPATH=jmetal-core/target/classes/:jmetal-exec/target/classes/:jmetal-problem/target/classes/:jmetal-algorithm/target/classes/
```
and then I write something like this:

```
java org.uma.jmetal.runner.multiobjective.SMPSORunner org.uma.jmetal.problem.multiobjective.Golinski
```

However, sometimes I have got runtime errors about missing libraries:
```
java org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner ALL jmetal-problem/src/test/resources/pareto_fronts/Kursawe.pf FUN.tsv 

The fronts are NOT NORMALIZED before computing the indicators
EP: 2799.499447785977
HV: 0.0
GD: 381.1994951105707
IGD: 102.76887872890298
IGD+: 3038.206812393222
SPREAD: 0.910670889364176
GSPREAD: 0.9045628203376009
R2: 1464.6004537062856
ER: 1.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
	at org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner.calculateAndPrintIndicators(CommandLineIndicatorRunner.java:131)
	at org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner.main(CommandLineIndicatorRunner.java:48)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

```
Any ideas about the reason of these kinds of errors? My concern is why a particular class (`Pair`) is not found while there are many other dependences.

I've tried the alternative of using `mvn`:
```
mvn -pl jmetal-exec exec:java -Dexec.mainClass="org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner" -Dexec.args="ALL jmetal-problem/src/test/resources/pareto_fronts/Kursawe.pf FUN.tsv"
```
and this works ok, but it is a very cumbersome way of running a program.

**Comment by matthieu-vergne** [comment]
Actually, I have started to implement a [class loader](https://github.com/matthieu-vergne/jMetal/blob/classLoader/jmetal-core/src/main/java/org/uma/jmetal/util/JMetalLoader.java) to retrieve all the quality indicators (and other stuff) without having to explicitly list them somewhere. Currently it works quite well (it properly retrieves quality indicators), but I still need to work on it, so don't take it yet. {^_°}

The point is that I get exactly the same errors, with precisely the same classes. I am still digging in this issue, so I cannot say why it happens, but one thing I noticed is that you do not properly specify your dependences. For instance, from the POM of the core module, you have:
```
<dependency>
	<groupId>junit</groupId>
	<artifactId>junit</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.apache.maven.reporting</groupId>
	<artifactId>maven-reporting-api</artifactId>
</dependency>
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-lang3</artifactId>
</dependency>
<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-math3</artifactId>
	<version>3.3</version>
</dependency>
```
So you can see that some have a specific version while others do not. Maybe this issue could come to the use of different versions in different modules, so it kind of mess up when it compiles a combination of all of that.

I suggest you to revise all your poms to select a precise version for each dependency. When you have a dependency to another of your own module (e.g. algorithm depends on core and problem) just use the exactly same version for all (the SNAPSHOT one). Maven replace them properly when you make the releases.

Also, I think that some dependencies should have a more restricted scope. If I remember well, some testing stuff do not have a scope, so they are kept also in the release (I had exceptions with JUnit classes). So check that too.

Maybe this will fix the problem.

**Comment by ajnebro** [comment]
After reading a bit, it seems that `mvn install` must be executed deploy the project jars in the .m2 directory.

This way, commands like this one now work:
```
mvn -pl jmetal-exec exec:java -Dexec.mainClass="org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner" -Dexec.args="ALL jmetal-problem/src/test/resources/pareto_fronts/ZDT1.pf FUN.tsv" 
```

**Comment by matthieu-vergne** [comment]
OK, but people using the lib won't use it with Maven if they have the JAR, so we should ensure that it works also out of Maven.

**Comment by ajnebro** [comment]
Yes, but then they will have to cope with the jars of the dependences that Maven gets automatically.

At a first glance, having to search for them and addign them in the CLASSPATH is not very attractive. 

Would have sense to create a jar will all the dependencies?

**Comment by matthieu-vergne** [comment]
For the basic JAR built with Maven yes, we need to retrieve all the other JARs, but for instance I am used to export (with Eclipse) the full JAR, which contains everything, so I can use it standalone. I would not be surprised that we can do the same by asking to Maven to build such JARs, although I don't know how. Such a JAR would be way more useful than a JAR which has no dependencies. I think the best would be to add a module which makes one or several dedicated JARs which contain all the dependencies.

Probably this need some thinking and reading, so we can do it after the 5.0 is released. (-> todolist)

**Comment by ajnebro** [comment]
I have modified the pom.xml files of the four sub-projects to generate jar with dependencies when invoking `mvn package`. After including the resulting jars in the CLASSPATH environment every seems to work:
```
> java org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner ALL jmetal-problem/src/test/resources/pareto_fronts/ZDT1.pf FUN.tsv 
The fronts are NOT NORMALIZED before computing the indicators
EP: 0.012667907237592868
HV: 0.6595252297284239
GD: 2.324056706214013E-4
IGD: 1.8924070507719931E-4
IGD+: 0.0037086472613006762
SPREAD: 0.3891725769621227
GSPREAD: 0.29869724328566594
R2: 0.13181208271920977
ER: 1.0
SC(refPF, front): 0.91
SC(front, refPF): 0.0
```

```
> java org.uma.jmetal.runner.multiobjective.NSGAIIRunner 
jul 27, 2015 10:27:38 AM org.uma.jmetal.runner.multiobjective.NSGAIIRunner main
INFORMACIÓN: Total execution time: 682ms
jul 27, 2015 10:27:38 AM org.uma.jmetal.runner.AbstractAlgorithmRunner printFinalSolutionSet
INFORMACIÓN: Random seed: 1437985657723
jul 27, 2015 10:27:38 AM org.uma.jmetal.runner.AbstractAlgorithmRunner printFinalSolutionSet
INFORMACIÓN: Objectives values have been written to file FUN.tsv
jul 27, 2015 10:27:38 AM org.uma.jmetal.runner.AbstractAlgorithmRunner printFinalSolutionSet
INFORMACIÓN: Variables values have been written to file VAR.tsv
jul 27, 2015 10:27:38 AM org.uma.jmetal.runner.AbstractAlgorithmRunner printQualityIndicators
INFORMACIÓN: 
Hypervolume (N) : 0.658530762969838
Hypervolume     : 0.658530762969838
Epsilon (N)     : 0.020698633996647176
Epsilon         : 0.020698633996647176
GD (N)          : 2.2039292342936937E-4
GD              : 2.2039292342936937E-4
IGD (N)         : 1.9847981879383015E-4
IGD             : 1.9847981879383015E-4
IGD+ (N)        : 0.004158207453516806
IGD+            : 0.004158207453516806
Spread (N)      : 0.3993422718135067
Spread          : 0.3993422718135067
R2 (N)          : 0.13207319796614203
R2              : 0.13207319796614203
Error ratio     : 1.0
```

**Comment by matthieu-vergne** [comment]
Could you share your FUN.tsv? I don't have this file and I don't know what to put inside.

**Comment by ajnebro** [comment]
To obtain that file you have to execute an algorithm. I've just written a first description of how to do it: https://github.com/jMetal/jMetalDocumentation/blob/master/running.md

**Comment by matthieu-vergne** [comment]
Thanks. I never touch my classpath, so I used an explicit mention of the JAR:
```
java -cp jmetal-exec/target/jmetal-exec-5.0-Beta-35-SNAPSHOT-jar-with-dependencies.jar org.uma.jmetal.qualityIndicator.CommandLineIndicatorRunner ALL jmetal-problem/src/test/resources/pareto_fronts/ZDT1.pf jmetal-exec/FUN.tsv 
```
and it works too:
```
The fronts are NOT NORMALIZED before computing the indicators
EP: 0.012395707711604587
HV: 0.6596071215396984
GD: 2.5877015814296586E-4
IGD: 1.818754655873446E-4
IGD+: 0.0037047948004080974
SPREAD: 0.3288337056716771
GSPREAD: 0.3455973515141629
R2: 0.13185496556199539
ER: 1.0
SC(refPF, front): 0.92
SC(front, refPF): 0.0
```

**Comment by ajnebro** [comment]
It's a matter of taste ;). I always do:
```export CLASSPATH=jmetal-core/target/jmetal-core-5.0-Beta-35-SNAPSHOT-jar-with-dependencies.jar:jmetal-problem/target/jmetal-problem-5.0-Beta-35-SNAPSHOT-jar-with-dependencies.jar:jmetal-exec/target/jmetal-exec-5.0-Beta-35-SNAPSHOT-jar-with-dependencies.jar:jmetal-problem/target/jmetal-problem-5.0-Beta-35-SNAPSHOT-jar-with-dependencies.jar
```

**Comment by ajnebro** [comment]
The sentence to set the CLASSPATH could also be included in the .profile file, so there would be no need to set it explicitly.

**Comment by matthieu-vergne** [comment]
Hum... taste for using `export` or `-cp`, but not for the content of the classpath: you fail in testing the right stuff with your current classpath. The point is that we would like here to ensure that using a single JAR containing everything works. With your classpath, you cannot ensure that, because you include all the JARs, but whether you use the usual JARs or the ones having all the dependencies, it is the same.

Normally, if you have only the exec JAR, it should work, but if you have only the core one, it should not, because you have no algorithm there. This is important to know, and final users should get the right JAR based on their needs: developers of new algorithms need only the core JAR, people wanting to use implemented algorithms need the algorithm JAR, people who want to try jMetal with its own features need the exec JAR, etc.

Using `export` is a good idea when you plan to do a lot of commands with the exactly same classpath, but it becomes a trap when you just aggregate everything in your classpath to use many commands which should use different classpaths, because the missing stuff in one is provided by another, so no exception is thrown while it should. For a final user, it should be always the same, but in our case, we have to pay attention to not hide the problems like that. {'^_^}

**Comment by ajnebro** [comment]
I agree. I was exposing my personal preferences ;).

The point is to explain all the options in the documentation to allow the users to decide.
